In [256]:
import pandas as pd
import numpy as np

df.shape

In [257]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\The Firm Adoption of Technology (FAT) Survey, 2021-2023\fat_india_disclosure.csv"
)

In [258]:
df.shape

(1519, 987)

In [259]:
df.head()

,firm_id,s3a,s3b,s3c,s4,s4a,s7,a3a,a3b,a3c,...,c3_0a2,s1a_rev,s1b,s1c,d8a,d8b,d8c,d8d,d8e,d8f
0,2000030,1,2,2,2,NaN,12,100,0,0,...,NaN,11. Leather and Footwear,Small (5-19),Tamil Nadu,Lack of technical skills,Lack of knowledge on acquiring,Consumer preferences do not value quality of p...,Consumer preferences do not value quality of p...,Lack of technical skills,Too costly or not convinced of the economic be...
1,2000031,1,2,2,2,NaN,15,100,0,0,...,NaN,6. Pharmaceutical,Small (5-19),Uttar Pradesh,Uncertainty of demand,Too costly or not convinced of the economic be...,Lack of information,Lack of information,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...
2,2000110,1,2,2,2,NaN,17,100,0,0,...,Food Safety and Standards Authority of India (...,3. Food Processing,Small (5-19),Uttar Pradesh,Lack of information,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...,Too costly or not convinced of the economic be...,Lack of technical skills,It is difficult or costly to comply with gover...
3,2000515,1,2,2,2,NaN,210,100,0,0,...,NaN,4. Wearing Apparel,Large (100+),Uttar Pradesh,Difficulty in obtaining financing,Uncertainty of demand,Consumer preferences do not value quality of p...,Lack of technical skills,Consumer preferences do not value quality of p...,Lack of information
4,2000768,1,2,2,2,NaN,44,100,0,0,...,NaN,4. Wearing Apparel,Small (5-19),Uttar Pradesh,Difficulty in obtaining financing,Lack of technical skills,Lack of information,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...,Lack of knowledge on acquiring

In [260]:
df.columns.tolist()

['firm_id',
 's3a',
 's3b',
 's3c',
 's4',
 's4a',
 's7',
 'a3a',
 'a3b',
 'a3c',
 'a3d',
 'a4a',
 'a4b',
 'a4c',
 'a4d',
 'a4e',
 'a4f',
 'a5a',
 'a6',
 'a7a',
 'a7b',
 'a7c',
 'a7d',
 'b1a',
 'b1b',
 'b1c',
 'b1d',
 'b1e',
 'b2a',
 'b2b',
 'b2c',
 'b3a',
 'b3b',
 'b4a',
 'b4b',
 'b5a',
 'b5b',
 'b5c',
 'b5d',
 'b5e',
 'b5f',
 'b5g',
 'b5h',
 'b6a',
 'b7a',
 'b7b',
 'b8a1',
 'b8a2',
 'b8a3',
 'b8a4',
 'b8a5',
 'b8a6',
 'b8b',
 'b8c',
 'b9a1',
 'b9a2',
 'b9a3',
 'b9a4',
 'b9a5',
 'b9a6',
 'b9b',
 'b9c',
 'b10a1',
 'b10a2',
 'b10a3',
 'b10a4',
 'b10a5',
 'b10a6',
 'b10a',
 'b10b',
 'b10c',
 'b11a1',
 'b11a2',
 'b11a3',
 'b11a4',
 'b11a5',
 'b11a6',
 'b11b',
 'b11c',
 'b12a1',
 'b12a2',
 'b12a3',
 'b12a4',
 'b12a5',
 'b12a6',
 'b12a7',
 'b12b',
 'b12c',
 'b13a',
 'b13b1',
 'b13b2',
 'b13b3',
 'b13b4',
 'b13b5',
 'b13b6',
 'b13b7',
 'b13c',
 'b13d',
 'b13e1',
 'b13e2',
 'b13e3',
 'b14a1',
 'b14a2',
 'b14a3',
 'b14a4',
 'b14a5',
 'b14a6',
 'b14a7',
 'b14a8',
 'b14b',
 'b14c',
 'b15a1',
 'b15a2',
 'b15a3',
 'b15a4',
 'b15a5',
 'b15b',
 'b15c',
 'b15c1',
 'b15c2',
 'b15c3',
 'b15c4',
 'c1_0a1',
 'c1_0a2',
 'c1_0a3',
 'c1_0a4',
 'c1_0a5',
 'c1_0a6',
 'c1_0a7',
 'c1_0b1',
 'c1_0c1',
 'c1_0c2',
 'c1_0c3',
 'c1_0c4',
 'c1_0c5',
 'c1_0c6',
 'c1_0c7',
 'c1_0d1',
 'c1_0d2',
 'c1_1a1',
 'c1_1a2',
 'c1_1a3',
 'c1_1b1',
 'c1_1b2',
 'c1_1b3',
 'c1_1b4',
 'c1_1b5',
 'c1_1c',
 'c1_1d',
 'c1_2a1',
 'c1_2b1',
 'c1_2b2',
 'c1_2b3',
 'c1_2b4',
 'c1_2b5',
 'c1_2b6',
 'c1_2b7',
 'c1_2c',
 'c1_2d',
 'c1_3a1',
 'c1_3a2',
 'c1_3a3',
 'c1_3b1',
 'c1_3b2',
 'c1_3b3',
 'c1_3b4',
 'c1_3b5',
 'c1_3b6',
 'c1_3c',
 'c1_3d',
 'c1_3e',
 'c1_4a1',
 'c1_4a2',
 'c1_4a3',
 'c1_4b1',
 'c1_4b2',
 'c1_4b3',
 'c1_4b4',
 'c1_4b5',
 'c1_4b6',
 'c1_4c',
 'c1_4d',
 'c1_5a1',
 'c1_5a2',
 'c1_5a3',
 'c1_5b1',
 'c1_5b2',
 'c1_5b3',
 'c1_5b4',
 'c1_5b5',
 'c1_5b6',
 'c1_5c',
 'c1_5d',
 'c1_6a1',
 'c1_6a2',
 'c1_6a3',
 'c1_6b1',
 'c1_6b2',
 'c1_6b3',
 'c1_6b4',
 'c1_6b5',
 'c1_6c',
 'c1_6d',
 'c2_0a1',
 'c2_0a2',
 'c2_0a3',
 'c2_0a4',
 'c2_0a5',
 'c2_0a6',
 'c2_0a7',
 'c2_0b',
 'c2_0c1',
 'c2_0c2',
 'c2_0c3',
 'c2_0c4',
 'c2_0d',
 'c2_1a1',
 'c2_1a2',
 'c2_1a3',
 'c2_1b1',
 'c2_1b2',
 'c2_1b3',
 'c2_1b4',
 'c2_1b5',
 'c2_1c',
 'c2_1d',
 'c2_2a1',
 'c2_2a2',
 'c2_2a3',
 'c2_2b1',
 'c2_2b2',
 'c2_2b3',
 'c2_2b4',
 'c2_2b5',
 'c2_2b6',
 'c2_2b7',
 'c2_2b8',
 'c2_2c',
 'c2_2d',
 'c2_3a1',
 'c2_3a2',
 'c2_3a3',
 'c2_3b1',
 'c2_3b2',
 'c2_3b3',
 'c2_3b4',
 'c2_3b5',
 'c2_3b6',
 'c2_3c',
 'c2_3d',
 'c2_4a1',
 'c2_4a2',
 'c2_4a3',
 'c2_4b1',
 'c2_4b2',
 'c2_4b3',
 'c2_4b4',
 'c2_4b5',
 'c2_4b6',
 'c2_4b7',
 'c2_4b8',
 'c2_4c',
 'c2_4d',
 'c2_5a1',
 'c2_5a2',
 'c2_5a3',
 'c2_5b1',
 'c2_5b2',
 'c2_5b3',
 'c2_5b4',
 'c2_5b5',
 'c2_5c',
 'c2_5d',
 'c3_0a1',
 'c3_0b1',
 'c3_0b2',
 'c3_1a1',
 'c3_1a2',
 'c3_1a3',
 'c3_1b1',
 'c3_1b2',
 'c3_1b3',
 'c3_1b4',
 'c3_1b5',
 'c3_1c',
 'c3_1d',
 'c3_2a1',
 'c3_2a2',
 'c3_2a3',
 'c3_2b1',
 'c3_2b2',
 'c3_2b3',
 'c3_2b4',
 'c3_2b5',
 'c3_2c',
 'c3_2d',
 'c3_3a1',
 'c3_3a2',
 'c3_3a3',
 'c3_3b1',
 'c3_3b2',
 'c3_3b3',
 'c3_3b4',
 'c3_3b5',
 'c3_3c',
 'c3_3d',
 'c3_4a1',
 'c3_4a2',
 'c3_4a3',
 'c3_4b1',
 'c3_4b2',
 'c3_4b3',
 'c3_4b4',
 'c3_4b5',
 'c3_4c',
 'c3_4d',
 'c3_5a1',
 'c3_5a2',
 'c3_5a3',
 'c3_5b1',
 'c3_5b2',
 'c3_5b3',
 'c3_5b4',
 'c3_5b5',
 'c3_5c',
 'c3_5d',
 'c4_0a1',
 'c4_0a2',
 'c4_0a3',
 'c4_0a4',
 'c4_0b1',
 'c4_0b2',
 'c4_0b3',
 'c4_0b4',
 'c4_0b5',
 'c4_0c1',
 'c4_0c2',
 'c4_0c3',
 'c4_0c4',
 'c4_0c5',
 'c4_1a1',
 'c4_1a2',
 'c4_1a3',
 'c4_1a4',
 'c4_1a5',
 'c4_1b1',
 'c4_1b2',
 'c4_1b3',
 'c4_1b4',
 'c4_1c',
 'c4_1d',
 'c4_2a1',
 'c4_2a2',
 'c4_2a3',
 'c4_2b1',
 'c4_2b2',
 'c4_2b3',
 'c4_2b4',
 'c4_2b5',
 'c4_2b6',
 'c4_2c',
 'c4_2d',
 'c4_3a1',
 'c4_3a2',
 'c4_3a3',
 'c4_3b1',
 'c4_3b2',
 'c4_3b3',
 'c4_3b4',
 'c4_3b5',
 'c4_3b6',
 'c4_3c',
 'c4_3d',
 'c4_4a1',
 'c4_4a2',
 'c4_4a3',
 'c4_4b1',
 'c4_4b2',
 'c4_4b3',
 'c4_4b4',
 'c4_4b5',
 'c4_4b6',
 'c4_4c',
 'c4_4d',
 'c5_1a1',
 'c5_1a2',
 'c5_1a3',
 'c5_1b1',
 'c5_1b2',
 'c5_1b3',
 'c5_1b4',
 'c5_1b5',
 'c5_1b6',
 'c5_1b7',
 'c5_1c',
 'c5_1d',
 'c5_2a1',
 'c5_2a2',
 'c5_2a3',
 'c5_2b1',
 'c5_2b2',
 'c5_2b3',
 'c5_2b4',
 'c5_2b5',
 'c5_2b6',
 'c5_2b7',
 'c5_2c',
 'c5_2d',
 'c5_3a1',
 'c5_3a2',
 'c5_3a3',
 'c5_3b1',
 'c5_3b2',
 'c5_3b3',
 'c5_3b4',
 'c5_3b5',
 'c5_3c',
 'c5_3d',
 'c5_4a1',
 'c5_4a2',
 'c5_4a3',
 'c5_4b1',
 'c5_4b2',
 'c5_4b3',
 'c5_4b4',
 'c5_4b5',
 'c5_4c',
 'c5_4d',
 'c5_5a1',
 'c5_5a2',
 'c5_5a3',
 'c5_5b1',
 'c5_5b2',
 'c5_5b3',
 'c5_5b4',
 'c5_5c',
 'c5_5d',
 'c6_0a1',
 'c6_0a2',
 'c6_0a3',
 'c6_0a4',
 'c6_0b1',
 'c6_0c1',
 'c6_0c2',
 'c6_1a1',
 'c6_1a2',
 'c6_1a3',
 'c6_1b1',
 'c6_1b2',
 'c6_1b3',
 'c6_1b4',
 'c6_1b5',
 'c6_1c',
 'c6_1d',
 'c6_2b1',
 'c6_2b2',
 'c6_2b3',
 'c6_2b4',
 'c6_2b5',
 'c6_2c',
 'c6_2d',
 'c6_3b1',
 'c6_3b2',
 'c6_3b3',
 'c6_3b4',
 'c6_3b5',
 'c6_3b6',
 'c6_3c',
 'c6_3d',
 'c6_4a1',
 'c6_4a2',
 'c6_4a3',
 'c6_4b1',
 'c6_4b2',
 'c6_4b3',
 'c6_4b4',
 'c6_4b5',
 'c6_4c',
 'c6_4d',
 'c6_5a1',
 'c6_5a2',
 'c6_5a3',
 'c6_5b1',
 'c6_5b2',
 'c6_5b3',
 'c6_5b4',
 'c6_5c',
 'c6_5d',
 'c6_6a1',
 'c6_6a2',
 'c6_6a3',
 'c6_6b1',
 'c6_6b2',
 'c6_6b3',
 'c6_6b4',
 'c6_6c',
 'c6_6d',
 'c7_1a1',
 'c7_1a2',
 'c7_1a3',
 'c7_1b1',
 'c7_1b2',
 'c7_1b3',
 'c7_1b4',
 'c7_1b5',
 'c7_1b6',
 'c7_1c',
 'c7_1d',
 'c7_2a1',
 'c7_2a2',
 'c7_2a3',
 'c7_2b1',
 'c7_2b2',
 'c7_2b3',
 'c7_2b4',
 'c7_2b5',
 'c7_2b6',
 'c7_2c',
 'c7_2d',
 'c7_2da',
 'c7_2db',
 'c7_3a1',
 'c7_3a2',
 'c7_3a3',
 'c7_3b1',
 'c7_3b2',
 'c7_3b3',
 'c7_3b4',
 'c7_3b5',
 'c7_3c',
 'c7_3d',
 'c7_4a1',
 'c7_4a2',
 'c7_4a3',
 'c7_4b1',
 'c7_4b2',
 'c7_4b3',
 'c7_4b4',
 'c7_4b5',
 'c7_4b6',
 'c7_4c',
 'c7_4d',
 'c7_5a1',
 'c7_5a2',
 'c7_5a3',
 'c7_5b1',
 'c7_5b2',
 'c7_5b3',
 'c7_5b4',
 'c7_5b5',
 'c7_5b6',
 'c7_5b7',
 'c7_5c',
 'c7_5d',
 'c8_0a',
 'c8_0b',
 'c8_0c',
 'c8_1a1',
 'c8_1a2',
 'c8_1a3',
 'c8_1b1',
 'c8_1b2',
 'c8_1b3',
 'c8_1b4_ind',
 'c8_1b6',
 'c8_1c',
 'c8_1d',
 'c8_2a1',
 'c8_2a2',
 'c8_2a3',
 'c8_2b1',
 'c8_2b2',
 'c8_2b3',
 'c8_2b4',
 'c8_2b5',
 'c8_2b6',
 'c8_2b7',
 'c8_2c',
 'c8_2d',
 'c8_3a1',
 'c8_3a2',
 'c8_3a3',
 'c8_3b1',
 'c8_3b2',
 'c8_3b3',
 'c8_3b4',
 'c8_3b5',
 'c8_3c',
 'c8_3d',
 'c8_4a1',
 'c8_4a2',
 'c8_4a3',
 'c8_4b1',
 'c8_4b2',
 'c8_4b3',
 'c8_4b4',
 'c8_4b5',
 'c8_4c',
 'c8_4d',
 'c8_5a1',
 'c8_5a2',
 'c8_5a3',
 'c8_5b1',
 'c8_5b2',
 'c8_5b3',
 'c8_5b4',
 'c8_5c',
 'c8_5d',
 'c9_0a1',
 'c9_0a2',
 'c9_0a3',
 'c9_0b1',
 'c9_0b2',
 'c9_0b3',
 'c9_0b4',
 'c9_0b5',
 'c9_0b6',
 'c9_0b7',
 'c9_0b8',
 'c9_0b9',
 'c9_0b10',
 'c9_0c1',
 'c9_0c2',
 'c9_1a1',
 'c9_1a2',
 'c9_1a3',
 'c9_1b1',
 'c9_1b2',
 'c9_1b3',
 'c9_1b4',
 'c9_1b5',
 'c9_1c',
 'c9_1d',
 'c9_2a1',
 'c9_2a2',
 'c9_2a3',
 'c9_2b1',
 'c9_2b2',
 'c9_2b3',
 'c9_2b4',
 'c9_2b5',
 'c9_2b6',
 'c9_2c',
 'c9_2d',
 'c9_3a1',
 'c9_3a2',
 'c9_3a3',
 'c9_3b1',
 'c9_3b2',
 'c9_3b3',
 'c9_3b4',
 'c9_3b5',
 'c9_3b6',
 'c9_3c',
 'c9_3d',
 'c9_4a1',
 'c9_4a2',
 'c9_4a3',
 'c9_4b1',
 'c9_4b2',
 'c9_4b3',
 'c9_4b4',
 'c9_4b5',
 'c9_4b6',
 'c9_4c',
 'c9_4d',
 'c9_5a1',
 'c9_5a2',
 'c9_5a3',
 'c9_5b1',
 'c9_5b2',
 'c9_5b3',
 'c9_5b4',
 'c9_5b5',
 'c9_5c',
 'c9_5d',
 'c10_0',
 'c10_0a',
 'c10_0b',
 'c10_0c',
 'c10_0d',
 'c10_1a1',
 'c10_1b1',
 'c10_1a2',
 'c10_1b2',
 'c10_1a3',
 'c10_1b3',
 'c10_1a4',
 'c10_1b4',
 'c10_1a5',
 'c10_1b5',
 'c10_1a6',
 'c10_1b6',
 'c10_1a7',
 'c10_1b7',
 'c10_1a8',
 'c10_1b8',
 'c10_1a9',
 'c10_1b9',
 'c10_1a11',
 'c10_1b11',
 'c10_1a12',
 'c10_1b12',
 'c10_2a1',
 'c10_2a2',
 'c10_2a3',
 'c10_2b1',
 'c10_2b2',
 'c10_2b3',
 'c10_2b4',
 'c10_2b5',
 'c10_2c',
 'c10_2d',
 'c10_3a1',
 'c10_3a2',
 'c10_3a3',
 'c10_3b1',
 'c10_3b2',
 'c10_3b3',
 'c10_3b4',
 'c10_3b5',
 'c10_3c',
 'c10_3d',
 'c10_4a1',
 'c10_4b1',
 'c10_4b2',
 'c10_4c1',
 'c10_4c2',
 'c10_4c3',
 'c10_4d',
 'c10_5a1',
 'c10_5a2',
 'c10_5b1',
 'c10_5b2',
 'c10_5c1',
 'c10_5c2',
 'c10_5d1',
 'c10_5d2',
 'c11_01a',
 'c11_01b',
 'c11_01c',
 'c11_01d',
 'c11_01e',
 'c11_01f',
 'c11_02a',
 'c11_02b',
 'c11_02c',
 'c11_02d',
 'c11_02e',
 'c11_03a',
 'c11_03b',
 'c11_03c',
 'c11_03d',
 'c11_03e',
 'c11_03f',
 'c11_1a1',
 'c11_1a2',
 'c11_1a3',
 'c11_1a4',
 'c11_1a5',
 'c11_1b1',
 'c11_1b2',
 'c11_1b3',
 'c11_1b4',
 'c11_1c',
 'c11_1d',
 'c11_2a1',
 'c11_2a2',
 'c11_2a3',
 'c11_2b1',
 'c11_2b2',
 'c11_2b3',
 'c11_2b4',
 'c11_2b5',
 'c11_2b6',
 'c11_2c',
 'c11_2d',
 'c11_3a1',
 'c11_3a2',
 'c11_3a3',
 'c11_3b1',
 'c11_3b2',
 'c11_3b3',
 'c11_3b4',
 'c11_3b5',
 'c11_3b6',
 'c11_3c',
 'c11_3d',
 'c11_4a1',
 'c11_4a2',
 'c11_4a3',
 'c11_4b1',
 'c11_4b2',
 'c11_4b3',
 'c11_4b4',
 'c11_4b5',
 'c11_4b6',
 'c11_4c',
 'c11_4d',
 'c12_0',
 'c12_0a',
 'c12_0b',
 'c12_0c',
 'c12_0d',
 'c12_0e',
 'c12_0f',
 'c12_0g',
 'c12_0h',
 'c12_0i',
 'c12_0j',
 'c12_0k',
 'c12_1a1',
 'c12_1a2',
 'c12_1a3',
 'c12_1b1',
 'c12_1b2',
 'c12_1b3',
 'c12_1b4',
 'c12_1b5',
 'c12_1b6',
 'c12_1c',
 'c12_1d',
 'c12_1e1',
 'c12_1e2',
 'c12_1e3',
 'c12_1e4_1',
 'c12_1e4_2',
 'c12_1e4_3',
 'c12_1e4_4',
 'c12_1e4_5',
 'c12_1e5',
 'c12_2a1',
 'c12_2a2',
 'c12_2a3',
 'c12_2b1',
 'c12_2b2',
 'c12_2b3',
 'c12_2b4',
 'c12_2b5',
 'c12_2b6',
 'c12_2c',
 'c12_2d',
 'c12_2da',
 'c12_2db',
 'c12_3a1',
 'c12_3a2',
 'c12_3a3',
 'c12_3b1',
 'c12_3b2',
 'c12_3b3',
 'c12_3b4',
 'c12_3b5',
 'c12_3b6',
 'c12_3c',
 'c12_3d',
 'c12_3e1',
 'c12_3e2',
 'c12_4a1',
 'c12_4a2',
 'c12_4a3',
 'c12_4b1',
 'c12_4b2',
 'c12_4b3',
 'c12_4b4',
 'c12_4b5',
 'c12_4c',
 'c12_4d',
 'c12_5a1',
 'c12_5a2',
 'c12_5a3',
 'c12_5b1',
 'c12_5b2',
 'c12_5b3',
 'c12_5b4',
 'c12_5b5',
 'c12_5b6',
 'c12_5c',
 'c12_5d',
 'd1a',
 'd1b',
 'd1c',
 'd1d',
 'd1e',
 'd2a',
 'd2b',
 'd2c',
 'd2d',
 'd2e',
 'd3a',
 'd3b',
 'd3c',
 'd4a',
 'd4b',
 'd4c',
 'd4d',
 'd5a',
 'd5b',
 'd5c',
 'd5d',
 'd5e',
 'd5f',
 'd6a',
 'd6b',
 'd6c',
 'd6d',
 'd6e',
 'd7a',
 'd7b',
 'd7c',
 'e1a',
 'e1b',
 'e1c',
 'e1d',
 'e1e',
 'e1f',
 'e2a',
 'e2b',
 'e2c',
 'e2d',
 'e2e',
 'e2f',
 'e3a',
 'e3b',
 'e3c',
 'e3d',
 'e3e',
 'e3f',
 'e4a',
 'e4b',
 'e4c',
 'e4d',
 'e4e',
 'e4f',
 'e5a',
 'e5b',
 'e5c',
 'e5d',
 'e5e',
 'e5f',
 'e3g',
 'e3h',
 'e6a',
 'e6b',
 'e7a',
 'e7b',
 'e7c',
 'e7d',
 'e8a',
 'e8b',
 'e9a',
 'e9b',
 'e9c',
 'e9d',
 'e9e',
 'e9f',
 'e10a',
 'e10b',
 'c12_6a1',
 'c12_6a2',
 'c12_6b1',
 'c12_6b2',
 'c12_6c1',
 'c12_6c2',
 'c12_6d1',
 'c12_6d2',
 'country',
 'country_code',
 'firmid',
 's1b_rev',
 's1c_rev',
 'formality',
 'base_wt',
 'survey_year',
 'ref_year1',
 'ref_year2',
 's2f',
 's2e',
 'c3_0a2',
 's1a_rev',
 's1b',
 's1c',
 'd8a',
 'd8b',
 'd8c',
 'd8d',
 'd8e',
 'd8f']

In [261]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1519 entries, 0 to 1518
Columns: 987 entries, firm_id to d8f
dtypes: float64(822), int64(148), str(17)
memory usage: 11.4 MB

In [262]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing.head(20)

c1_1d     1519
c9_0b7    1519
c1_1c     1519
c1_0a7    1519
c1_0a6    1519
c1_0a5    1519
c1_0a4    1519
c1_0a3    1519
c1_0a2    1519
c1_0a1    1519
c1_2b1    1519
c1_2a1    1519
c1_0c3    1519
c1_0b1    1519
c1_0c1    1519
c1_0c2    1519
c1_3b2    1519
c1_0c4    1519
c1_3b3    1519
c1_1a3    1519
dtype: int64

In [263]:
df.isnull().sum().sum()

np.int64(1149926)

In [264]:
empty_columns = df.columns[df.isnull().all()]

len(empty_columns)

157

In [265]:
empty_columns.tolist()

['c1_0a1',
 'c1_0a2',
 'c1_0a3',
 'c1_0a4',
 'c1_0a5',
 'c1_0a6',
 'c1_0a7',
 'c1_0b1',
 'c1_0c1',
 'c1_0c2',
 'c1_0c3',
 'c1_0c4',
 'c1_0c5',
 'c1_0c6',
 'c1_0c7',
 'c1_0d1',
 'c1_0d2',
 'c1_1a1',
 'c1_1a2',
 'c1_1a3',
 'c1_1b1',
 'c1_1b2',
 'c1_1b3',
 'c1_1b4',
 'c1_1b5',
 'c1_1c',
 'c1_1d',
 'c1_2a1',
 'c1_2b1',
 'c1_2b2',
 'c1_2b3',
 'c1_2b4',
 'c1_2b5',
 'c1_2b6',
 'c1_2b7',
 'c1_2c',
 'c1_2d',
 'c1_3a1',
 'c1_3a2',
 'c1_3a3',
 'c1_3b1',
 'c1_3b2',
 'c1_3b3',
 'c1_3b4',
 'c1_3b5',
 'c1_3b6',
 'c1_3c',
 'c1_3d',
 'c1_3e',
 'c1_4a1',
 'c1_4a2',
 'c1_4a3',
 'c1_4b1',
 'c1_4b2',
 'c1_4b3',
 'c1_4b4',
 'c1_4b5',
 'c1_4b6',
 'c1_4c',
 'c1_4d',
 'c1_5a1',
 'c1_5a2',
 'c1_5a3',
 'c1_5b1',
 'c1_5b2',
 'c1_5b3',
 'c1_5b4',
 'c1_5b5',
 'c1_5b6',
 'c1_5c',
 'c1_5d',
 'c1_6a1',
 'c1_6a2',
 'c1_6a3',
 'c1_6b1',
 'c1_6b2',
 'c1_6b3',
 'c1_6b4',
 'c1_6b5',
 'c1_6c',
 'c1_6d',
 'c2_0a1',
 'c2_0a2',
 'c2_0a3',
 'c2_0a4',
 'c2_0a5',
 'c2_0a6',
 'c2_0a7',
 'c2_0b',
 'c2_0c1',
 'c2_0c2',
 'c2_0c3',
 'c2_0c4',
 'c2_0d',
 'c2_1a1',
 'c2_1a2',
 'c2_1a3',
 'c2_1b1',
 'c2_1b2',
 'c2_1b3',
 'c2_1b4',
 'c2_1b5',
 'c2_1c',
 'c2_1d',
 'c2_2a1',
 'c2_2a2',
 'c2_2a3',
 'c2_2b1',
 'c2_2b2',
 'c2_2b3',
 'c2_2b4',
 'c2_2b5',
 'c2_2b6',
 'c2_2b7',
 'c2_2b8',
 'c2_2c',
 'c2_2d',
 'c2_3a1',
 'c2_3a2',
 'c2_3a3',
 'c2_3b1',
 'c2_3b2',
 'c2_3b3',
 'c2_3b4',
 'c2_3b5',
 'c2_3b6',
 'c2_3c',
 'c2_3d',
 'c2_4a1',
 'c2_4a2',
 'c2_4a3',
 'c2_4b1',
 'c2_4b2',
 'c2_4b3',
 'c2_4b4',
 'c2_4b5',
 'c2_4b6',
 'c2_4b7',
 'c2_4b8',
 'c2_4c',
 'c2_4d',
 'c2_5a1',
 'c2_5a2',
 'c2_5a3',
 'c2_5b1',
 'c2_5b2',
 'c2_5b3',
 'c2_5b4',
 'c2_5b5',
 'c2_5c',
 'c2_5d',
 'c4_3a2',
 'c4_4a2',
 'c6_5a2',
 'c6_6a2',
 'c9_0b7',
 'c12_1a2']

In [266]:
empty_columns = df.columns[df.isnull().all()]

len(empty_columns)

157

In [267]:
df_clean = df.drop(columns=empty_columns)

In [268]:
df_clean.shape

(1519, 830)

In [269]:
df_clean.isnull().sum().sum()

np.int64(911443)

In [270]:
df_clean = df.drop(columns=empty_columns)

In [271]:
df_clean.shape

(1519, 830)

In [272]:
df_clean.isnull().sum().sum()

np.int64(911443)

In [273]:
missing_clean = df_clean.isnull().sum()

missing_clean = missing_clean[missing_clean > 0].sort_values(ascending=False)

missing_clean.head(20)

c6_1a2     1518
c4_2a2     1518
c12_5a2    1518
c12_3a2    1518
c10_3a2    1518
c10_3a3    1518
c3_1a2     1517
c3_4a2     1517
c3_5a2     1517
c3_3a2     1517
c8_3a3     1517
c12_3a3    1517
c12_4a2    1517
c12_5d     1516
c3_2a2     1516
c12_2a2    1516
c12_4d     1516
c12_1a3    1516
c6_4a2     1516
c11_2a2    1516
dtype: int64

In [274]:
missing_clean.shape

(662,)

In [275]:
missing_percentage = (
    df_clean.isnull().sum() / len(df_clean)
) * 100

missing_percentage = (
    missing_percentage[missing_percentage > 0]
    .sort_values(ascending=False)
)

missing_percentage.head(20)

c6_1a2     99.934167
c4_2a2     99.934167
c12_5a2    99.934167
c12_3a2    99.934167
c10_3a2    99.934167
c10_3a3    99.934167
c3_1a2     99.868334
c3_4a2     99.868334
c3_5a2     99.868334
c3_3a2     99.868334
c8_3a3     99.868334
c12_3a3    99.868334
c12_4a2    99.868334
c12_5d     99.802502
c3_2a2     99.802502
c12_2a2    99.802502
c12_4d     99.802502
c12_1a3    99.802502
c6_4a2     99.802502
c11_2a2    99.802502
dtype: float64

In [276]:
missing_percentage.shape

(662,)

In [277]:
very_sparse = missing_percentage[missing_percentage > 95]

len(very_sparse)

268

In [278]:
very_sparse.head(30)

c6_1a2     99.934167
c4_2a2     99.934167
c12_5a2    99.934167
c12_3a2    99.934167
c10_3a2    99.934167
c10_3a3    99.934167
c3_1a2     99.868334
c3_4a2     99.868334
c3_5a2     99.868334
c3_3a2     99.868334
c8_3a3     99.868334
c12_3a3    99.868334
c12_4a2    99.868334
c12_5d     99.802502
c3_2a2     99.802502
c12_2a2    99.802502
c12_4d     99.802502
c12_1a3    99.802502
c6_4a2     99.802502
c11_2a2    99.802502
c11_4a2    99.736669
c5_5a2     99.736669
c12_2d     99.736669
c5_3d      99.670836
c8_4a3     99.670836
c12_2a3    99.670836
c6_6a3     99.605003
c3_5a3     99.539171
c8_3a2     99.539171
c11_3a2    99.539171
dtype: float64

In [279]:
fintech_candidates = [
    "s7",
    "a5a",
    "a6",
    "b5a",
    "b5f",
    "b5g",
    "b5h",
    "b13b4",
    "b13b5",
    "b14a4",
    "b14a5",
    "b14a6",
    "d3a",
    "d3c",
    "d7a",
    "d7b",
    "d8a"
]

df_clean[fintech_candidates].head()

,s7,a5a,a6,b5a,b5f,b5g,b5h,b13b4,b13b5,b14a4,b14a5,b14a6,d3a,d3c,d7a,d7b,d8a
0,12,11,2004,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Lack of technical skills
1,15,6,1953,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Uncertainty of demand
2,17,3,1981,1,1.0,1,2.0,2,2,2,2,2,1,1,1,1,Lack of information
3,210,4,2005,1,2.0,1,2.0,2,2,1,1,1,2,-9,2,2,Difficulty in obtaining financing
4,44,4,2008,1,2.0,1,2.0,2,2,2,1,1,2,0,2,2,Difficulty in obtaining financing

In [280]:
df_clean[fintech_candidates].isnull().sum()

s7        0
a5a       0
a6        0
b5a       0
b5f      17
b5g       0
b5h      17
b13b4     0
b13b5     0
b14a4     0
b14a5     0
b14a6     0
d3a       0
d3c       0
d7a       0
d7b       0
d8a       0
dtype: int64

In [281]:
df_clean[fintech_candidates].isnull().mean() * 100

s7       0.000000
a5a      0.000000
a6       0.000000
b5a      0.000000
b5f      1.119157
b5g      0.000000
b5h      1.119157
b13b4    0.000000
b13b5    0.000000
b14a4    0.000000
b14a5    0.000000
b14a6    0.000000
d3a      0.000000
d3c      0.000000
d7a      0.000000
d7b      0.000000
d8a      0.000000
dtype: float64

In [282]:
for col in fintech_candidates:
    print(f"\n{col}")
    print(df_clean[col].value_counts(dropna=False).sort_index())

s7
s7
5       28
6       43
7       36
8       49
9       24
        ..
1800     1
2000     1
2750     1
3000     1
4000     1
Name: count, Length: 149, dtype: int64

a5a
a5a
3      122
4      129
5      117
6      117
7      196
8      120
9       80
10     121
11     120
12      38
101    186
102    173
Name: count, dtype: int64

a6
a6
-9        7
 1844     1
 1846     1
 1859     2
 1865     1
         ..
 2013    25
 2014    29
 2015    27
 2016    11
 2017     7
Name: count, Length: 105, dtype: int64

b5a
b5a
1    1502
2      17
Name: count, dtype: int64

b5f
b5f
1.0    682
2.0    820
NaN     17
Name: count, dtype: int64

b5g
b5g
-9       1
 1    1338
 2     180
Name: count, dtype: int64

b5h
b5h
-9.0       2
 1.0     225
 2.0    1275
 NaN      17
Name: count, dtype: int64

b13b4
b13b4
-9       3
 1      98
 2    1418
Name: count, dtype: int64

b13b5
b13b5
-9       1
 1     244
 2    1274
Name: count, dtype: int64

b14a4
b14a4
-9      2
 1    932
 2    585
Name: count, dtype: int64

b14a5
b14a5
-9       1
 1    1066
 2     452
Name: count, dtype: int64

b14a6
b14a6
-9      2
 1    854
 2    663
Name: count, dtype: int64

d3a
d3a
-9      61
 1     437
 2    1021
Name: count, dtype: int64

d3c
d3c
-9     182
 0     786
 1     198
 2     251
 3      34
 4      16
 5      14
 6       1
 7      16
 8       8
 10     10
 15      1
 18      1
 31      1
Name: count, dtype: int64

d7a
d7a
1    1140
2     379
Name: count, dtype: int64

d7b
d7b
-9      23
 1     436
 2    1060
Name: count, dtype: int64

d8a
d8a
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
Don't know                                                          11
Electricity, water, or Internet connection are too expensive         4
It is difficult or costly to comply with government regulations     29
Lack of information                                                282
Lack of knowledge on acquiring                                      19
Lack of technical skills                                           248
Other                                                                9
Too costly or not convinced of the economic benefit                333
Uncertainty of demand                                              464
Name: count, dtype: int64

In [283]:
for col in fintech_candidates:
    print(f"\n{col}")
    print(df_clean[col].value_counts(dropna=False).sort_index())

s7
s7
5       28
6       43
7       36
8       49
9       24
        ..
1800     1
2000     1
2750     1
3000     1
4000     1
Name: count, Length: 149, dtype: int64

a5a
a5a
3      122
4      129
5      117
6      117
7      196
8      120
9       80
10     121
11     120
12      38
101    186
102    173
Name: count, dtype: int64

a6
a6
-9        7
 1844     1
 1846     1
 1859     2
 1865     1
         ..
 2013    25
 2014    29
 2015    27
 2016    11
 2017     7
Name: count, Length: 105, dtype: int64

b5a
b5a
1    1502
2      17
Name: count, dtype: int64

b5f
b5f
1.0    682
2.0    820
NaN     17
Name: count, dtype: int64

b5g
b5g
-9       1
 1    1338
 2     180
Name: count, dtype: int64

b5h
b5h
-9.0       2
 1.0     225
 2.0    1275
 NaN      17
Name: count, dtype: int64

b13b4
b13b4
-9       3
 1      98
 2    1418
Name: count, dtype: int64

b13b5
b13b5
-9       1
 1     244
 2    1274
Name: count, dtype: int64

b14a4
b14a4
-9      2
 1    932
 2    585
Name: count, dtype: int64

b14a5
b14a5
-9       1
 1    1066
 2     452
Name: count, dtype: int64

b14a6
b14a6
-9      2
 1    854
 2    663
Name: count, dtype: int64

d3a
d3a
-9      61
 1     437
 2    1021
Name: count, dtype: int64

d3c
d3c
-9     182
 0     786
 1     198
 2     251
 3      34
 4      16
 5      14
 6       1
 7      16
 8       8
 10     10
 15      1
 18      1
 31      1
Name: count, dtype: int64

d7a
d7a
1    1140
2     379
Name: count, dtype: int64

d7b
d7b
-9      23
 1     436
 2    1060
Name: count, dtype: int64

d8a
d8a
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
Don't know                                                          11
Electricity, water, or Internet connection are too expensive         4
It is difficult or costly to comply with government regulations     29
Lack of information                                                282
Lack of knowledge on acquiring                                      19
Lack of technical skills                                           248
Other                                                                9
Too costly or not convinced of the economic benefit                333
Uncertainty of demand                                              464
Name: count, dtype: int64

In [284]:
df.shape

(1519, 987)

In [285]:
df_clean = df.drop(columns=empty_columns)

In [286]:
df_clean.shape

(1519, 830)

In [287]:
df_clean["b14a5"].value_counts(dropna=False)

b14a5
 1    1066
 2     452
-9       1
Name: count, dtype: int64

In [288]:
df_clean["b14a5_decoded"] = df_clean["b14a5"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\3485523185.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b14a5_decoded"] = df_clean["b14a5"].map({

In [289]:
df_clean[["b14a5", "b14a5_decoded"]].head(20)

    b14a5 b14a5_decoded
0       2            No
1       2            No
2       2            No
3       1           Yes
4       1           Yes
5       1           Yes
6       1           Yes
7       1           Yes
8       1           Yes
9       2            No
10      1           Yes
11      2            No
12      1           Yes
13      1           Yes
14      2            No
15      1           Yes
16      1           Yes
17      1           Yes
18      1           Yes
19      1           Yes

In [290]:
df_clean["b14a4_decoded"] = df_clean["b14a4"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\1166837190.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b14a4_decoded"] = df_clean["b14a4"].map({

In [291]:
df_clean[["b14a4", "b14a4_decoded"]].head(20)

    b14a4 b14a4_decoded
0       2            No
1       2            No
2       2            No
3       1           Yes
4       2            No
5       2            No
6       2            No
7       2            No
8       1           Yes
9       2            No
10      1           Yes
11      1           Yes
12      1           Yes
13      2            No
14      1           Yes
15      2            No
16      2            No
17      1           Yes
18      2            No
19      1           Yes

In [292]:
df_clean["b14a6_decoded"] = df_clean["b14a6"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\4061770285.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b14a6_decoded"] = df_clean["b14a6"].map({

In [293]:
df_clean[["b14a4", "b14a4_decoded",
          "b14a5", "b14a5_decoded",
          "b14a6", "b14a6_decoded"]].head(20)

    b14a4 b14a4_decoded  b14a5 b14a5_decoded  b14a6 b14a6_decoded
0       2            No      2            No      2            No
1       2            No      2            No      2            No
2       2            No      2            No      2            No
3       1           Yes      1           Yes      1           Yes
4       2            No      1           Yes      1           Yes
5       2            No      1           Yes      1           Yes
6       2            No      1           Yes      1           Yes
7       2            No      1           Yes      2            No
8       1           Yes      1           Yes      2            No
9       2            No      2            No      2            No
10      1           Yes      1           Yes      1           Yes
11      1           Yes      2            No      2            No
12      1           Yes      1           Yes      1           Yes
13      2            No      1           Yes      1           Yes
14      1           Yes      2            No      1           Yes
15      2            No      1           Yes      2            No
16      2            No      1           Yes      1           Yes
17      1           Yes      1           Yes      2            No
18      2            No      1           Yes      2            No
19      1           Yes      1           Yes      1           Yes

In [294]:
df_clean["b14a4_decoded"] = df_clean["b14a4"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

In [295]:
df_clean["b14a5_decoded"] = df_clean["b14a5"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

In [296]:
df_clean["b14a6_decoded"] = df_clean["b14a6"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

In [297]:
df_clean[[
    "b14a4", "b14a4_decoded",
    "b14a5", "b14a5_decoded",
    "b14a6", "b14a6_decoded"
]].head(20)

    b14a4 b14a4_decoded  b14a5 b14a5_decoded  b14a6 b14a6_decoded
0       2            No      2            No      2            No
1       2            No      2            No      2            No
2       2            No      2            No      2            No
3       1           Yes      1           Yes      1           Yes
4       2            No      1           Yes      1           Yes
5       2            No      1           Yes      1           Yes
6       2            No      1           Yes      1           Yes
7       2            No      1           Yes      2            No
8       1           Yes      1           Yes      2            No
9       2            No      2            No      2            No
10      1           Yes      1           Yes      1           Yes
11      1           Yes      2            No      2            No
12      1           Yes      1           Yes      1           Yes
13      2            No      1           Yes      1           Yes
14      1           Yes      2            No      1           Yes
15      2            No      1           Yes      2            No
16      2            No      1           Yes      1           Yes
17      1           Yes      1           Yes      2            No
18      2            No      1           Yes      2            No
19      1           Yes      1           Yes      1           Yes

In [298]:
df_clean["b5a_decoded"] = df_clean["b5a"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\1982178111.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b5a_decoded"] = df_clean["b5a"].map({

In [299]:
df_clean[["b5a", "b5a_decoded"]].head(10)

   b5a b5a_decoded
0    1         Yes
1    1         Yes
2    1         Yes
3    1         Yes
4    1         Yes
5    1         Yes
6    1         Yes
7    1         Yes
8    1         Yes
9    1         Yes

In [300]:
df_clean["b5f_decoded"] = df_clean["b5f"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\1090504605.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b5f_decoded"] = df_clean["b5f"].map({

In [301]:
df_clean[["b5f", "b5f_decoded"]].head(20)

    b5f b5f_decoded
0   2.0          No
1   2.0          No
2   1.0         Yes
3   2.0          No
4   2.0          No
5   2.0          No
6   2.0          No
7   1.0         Yes
8   2.0          No
9   2.0          No
10  2.0          No
11  2.0          No
12  1.0         Yes
13  1.0         Yes
14  2.0          No
15  2.0          No
16  1.0         Yes
17  1.0         Yes
18  2.0          No
19  1.0         Yes

In [302]:
df_clean["b5g_decoded"] = df_clean["b5g"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\1680735380.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b5g_decoded"] = df_clean["b5g"].map({

In [303]:
df_clean[["b5g", "b5g_decoded"]].head(20)

    b5g b5g_decoded
0     1         Yes
1     1         Yes
2     1         Yes
3     1         Yes
4     1         Yes
5     1         Yes
6     1         Yes
7     1         Yes
8     1         Yes
9     1         Yes
10    1         Yes
11    2          No
12    1         Yes
13    1         Yes
14    1         Yes
15    2          No
16    1         Yes
17    1         Yes
18    1         Yes
19    1         Yes

In [304]:
df_clean["b5h_decoded"] = df_clean["b5h"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\238235568.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b5h_decoded"] = df_clean["b5h"].map({

In [305]:
df_clean["b5h_decoded"] = df_clean["b5h"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

In [306]:
df_clean[["b5h", "b5h_decoded"]].head(20)

    b5h b5h_decoded
0   2.0          No
1   2.0          No
2   2.0          No
3   2.0          No
4   2.0          No
5   2.0          No
6   2.0          No
7   2.0          No
8   2.0          No
9   2.0          No
10  2.0          No
11  2.0          No
12  2.0          No
13  2.0          No
14  2.0          No
15  2.0          No
16  2.0          No
17  1.0         Yes
18  2.0          No
19  2.0          No

In [307]:
df_clean.to_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv",
    index=False
)

In [308]:
import pandas as pd

df_clean = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"
)

In [309]:
df_clean.shape

(1519, 837)

In [310]:
df_clean[[
    "b14a4_decoded",
    "b14a5_decoded",
    "b14a6_decoded",
    "b5a_decoded",
    "b5f_decoded",
    "b5g_decoded",
    "b5h_decoded"
]].head(10)

,b14a4_decoded,b14a5_decoded,b14a6_decoded,b5a_decoded,b5f_decoded,b5g_decoded,b5h_decoded
0,No,No,No,Yes,No,Yes,No
1,No,No,No,Yes,No,Yes,No
2,No,No,No,Yes,Yes,Yes,No
3,Yes,Yes,Yes,Yes,No,Yes,No
4,No,Yes,Yes,Yes,No,Yes,No
5,No,Yes,Yes,Yes,No,Yes,No
6,No,Yes,Yes,Yes,No,Yes,No
7,No,Yes,No,Yes,Yes,Yes,No
8,Yes,Yes,No,Yes,No,Yes,No
9,No,No,No,Yes,No,Yes,No

In [311]:
df_clean.head(3)

,firm_id,s3a,s3b,s3c,s4,s4a,s7,a3a,a3b,a3c,...,d8d,d8e,d8f,b14a5_decoded,b14a4_decoded,b14a6_decoded,b5a_decoded,b5f_decoded,b5g_decoded,b5h_decoded
0,2000030,1,2,2,2,NaN,12,100,0,0,...,Consumer preferences do not value quality of p...,Lack of technical skills,Too costly or not convinced of the economic be...,No,No,No,Yes,No,Yes,No
1,2000031,1,2,2,2,NaN,15,100,0,0,...,Lack of information,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...,No,No,No,Yes,No,Yes,No
2,2000110,1,2,2,2,NaN,17,100,0,0,...,Too costly or not convinced of the economic be...,Lack of technical skills,It is difficult or costly to comply with gover...,No,No,No,Yes,Yes,Yes,No

In [312]:
df_clean[
    ["b14a4_decoded", "b14a5_decoded", "b14a6_decoded"]
].value_counts()

b14a4_decoded  b14a5_decoded  b14a6_decoded
Yes            Yes            Yes              494
                              No               202
No             Yes            Yes              186
                              No               182
               No             No               161
Yes            No             Yes              118
                              No               116
No             No             Yes               56
Yes            Don't Know     Don't Know         1
               Yes            Don't Know         1
Don't Know     Yes            No                 1
               No             No                 1
Name: count, dtype: int64

In [313]:
df_clean[["b13b4", "b13b5"]].value_counts(dropna=False)

b13b4  b13b5
 2      2       1224
        1        193
 1      1         50
        2         48
-9      2          2
        1          1
 2     -9          1
Name: count, dtype: int64

In [314]:
df_clean["b13b4_decoded"] = df_clean["b13b4"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

df_clean["b13b5_decoded"] = df_clean["b13b5"].map({
    1: "Yes",
    2: "No",
    -9: "Don't Know",
    -7: "Not Applicable"
})

df_clean[
    ["b13b4", "b13b4_decoded", "b13b5", "b13b5_decoded"]
].head(10)

C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\2892811817.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b13b4_decoded"] = df_clean["b13b4"].map({
C:\Users\Krishna\AppData\Local\Temp\ipykernel_2340\2892811817.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean["b13b5_decoded"] = df_clean["b13b5"].map({

   b13b4 b13b4_decoded  b13b5 b13b5_decoded
0      2            No      2            No
1      2            No      2            No
2      2            No      2            No
3      2            No      2            No
4      2            No      2            No
5      2            No      2            No
6      2            No      2            No
7      2            No      1           Yes
8      2            No      2            No
9      2            No      2            No

In [315]:
print("b13b4 - Online Sales through External Digital Platforms")
print(df_clean["b13b4_decoded"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("b13b5 - Online Sales through Own Website")
print(df_clean["b13b5_decoded"].value_counts(dropna=False))

b13b4 - Online Sales through External Digital Platforms
b13b4_decoded
No            1418
Yes             98
Don't Know       3
Name: count, dtype: int64

-----------------------------------

b13b5 - Online Sales through Own Website
b13b5_decoded
No            1274
Yes            244
Don't Know       1
Name: count, dtype: int64

In [316]:
print("b14a4 - Card Payments")
print(df_clean["b14a4_decoded"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("b14a5 - Online/Electronic Payments")
print(df_clean["b14a5_decoded"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("b14a6 - Online Platform Payments")
print(df_clean["b14a6_decoded"].value_counts(dropna=False))

b14a4 - Card Payments
b14a4_decoded
Yes           932
No            585
Don't Know      2
Name: count, dtype: int64

-----------------------------------

b14a5 - Online/Electronic Payments
b14a5_decoded
Yes           1066
No             452
Don't Know       1
Name: count, dtype: int64

-----------------------------------

b14a6 - Online Platform Payments
b14a6_decoded
Yes           854
No            663
Don't Know      2
Name: count, dtype: int64

In [317]:
print("d3a - Loan for machinery/equipment/software")
print(df_clean["d3a"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("d3c - Needed to borrow but could not get it")
print(df_clean["d3c"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("d7a - Government support awareness")
print(df_clean["d7a"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("d7b - Benefited from government support")
print(df_clean["d7b"].value_counts(dropna=False))

print("\n-----------------------------------\n")

print("d8a - Main technology adoption obstacle")
print(df_clean["d8a"].value_counts(dropna=False))

d3a - Loan for machinery/equipment/software
d3a
 2    1021
 1     437
-9      61
Name: count, dtype: int64

-----------------------------------

d3c - Needed to borrow but could not get it
d3c
 0     786
 2     251
 1     198
-9     182
 3      34
 7      16
 4      16
 5      14
 10     10
 8       8
 15      1
 18      1
 31      1
 6       1
Name: count, dtype: int64

-----------------------------------

d7a - Government support awareness
d7a
1    1140
2     379
Name: count, dtype: int64

-----------------------------------

d7b - Benefited from government support
d7b
 2    1060
 1     436
-9      23
Name: count, dtype: int64

-----------------------------------

d8a - Main technology adoption obstacle
d8a
Uncertainty of demand                                              464
Too costly or not convinced of the economic benefit                333
Lack of information                                                282
Lack of technical skills                                           248
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
It is difficult or costly to comply with government regulations     29
Lack of knowledge on acquiring                                      19
Don't know                                                          11
Other                                                                9
Electricity, water, or Internet connection are too expensive         4
Name: count, dtype: int64

In [318]:
selected_columns = [
    "s7",
    "a5a",
    "a6",
    "b5a",
    "b5f",
    "b5g",
    "b5h",
    "b13b4",
    "b13b5",
    "b14a4",
    "b14a5",
    "b14a6",
    "d3a",
    "d3c",
    "d7a",
    "d7b",
    "d8a"
]

selected_df = df_clean[selected_columns].copy()

print("Shape:", selected_df.shape)

selected_df.head()

Shape: (1519, 17)

,s7,a5a,a6,b5a,b5f,b5g,b5h,b13b4,b13b5,b14a4,b14a5,b14a6,d3a,d3c,d7a,d7b,d8a
0,12,11,2004,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Lack of technical skills
1,15,6,1953,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Uncertainty of demand
2,17,3,1981,1,1.0,1,2.0,2,2,2,2,2,1,1,1,1,Lack of information
3,210,4,2005,1,2.0,1,2.0,2,2,1,1,1,2,-9,2,2,Difficulty in obtaining financing
4,44,4,2008,1,2.0,1,2.0,2,2,2,1,1,2,0,2,2,Difficulty in obtaining financing

In [319]:
ml_df = selected_df.copy()

print("ML working dataset shape:", ml_df.shape)
ml_df.head()

ML working dataset shape: (1519, 17)

,s7,a5a,a6,b5a,b5f,b5g,b5h,b13b4,b13b5,b14a4,b14a5,b14a6,d3a,d3c,d7a,d7b,d8a
0,12,11,2004,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Lack of technical skills
1,15,6,1953,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Uncertainty of demand
2,17,3,1981,1,1.0,1,2.0,2,2,2,2,2,1,1,1,1,Lack of information
3,210,4,2005,1,2.0,1,2.0,2,2,1,1,1,2,-9,2,2,Difficulty in obtaining financing
4,44,4,2008,1,2.0,1,2.0,2,2,2,1,1,2,0,2,2,Difficulty in obtaining financing

In [320]:
ml_df = selected_df.copy()

print("ML working dataset shape:", ml_df.shape)
ml_df.head()

ML working dataset shape: (1519, 17)

,s7,a5a,a6,b5a,b5f,b5g,b5h,b13b4,b13b5,b14a4,b14a5,b14a6,d3a,d3c,d7a,d7b,d8a
0,12,11,2004,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Lack of technical skills
1,15,6,1953,1,2.0,1,2.0,2,2,2,2,2,2,0,1,2,Uncertainty of demand
2,17,3,1981,1,1.0,1,2.0,2,2,2,2,2,1,1,1,1,Lack of information
3,210,4,2005,1,2.0,1,2.0,2,2,1,1,1,2,-9,2,2,Difficulty in obtaining financing
4,44,4,2008,1,2.0,1,2.0,2,2,2,1,1,2,0,2,2,Difficulty in obtaining financing

In [321]:
# Check special -9 values in our selected dataset

for col in ml_df.columns:
    count = (ml_df[col] == -9).sum()
    if count > 0:
        print(col, "→", count, "rows with -9")

a6 → 7 rows with -9
b5g → 1 rows with -9
b5h → 2 rows with -9
b13b4 → 3 rows with -9
b13b5 → 1 rows with -9
b14a4 → 2 rows with -9
b14a5 → 1 rows with -9
b14a6 → 2 rows with -9
d3a → 61 rows with -9
d3c → 182 rows with -9
d7b → 23 rows with -9

In [322]:
# Convert special -9 codes to missing values

ml_df = ml_df.replace(-9, float("nan"))

print("Total missing values:", ml_df.isnull().sum().sum())

Total missing values: 319

In [323]:
ml_df = ml_df.replace(-9, float("nan"))

In [324]:
yes_no_columns = [
    "b5a", "b5f", "b5g", "b5h",
    "b13b4", "b13b5",
    "b14a4", "b14a5", "b14a6",
    "d3a", "d7a", "d7b"
]

for col in yes_no_columns:
    ml_df[col] = ml_df[col].map({
        1: 1,
        2: 0
    })

print(ml_df.head())

    s7  a5a      a6  b5a  b5f  b5g  b5h  b13b4  b13b5  b14a4  b14a5  b14a6  \
0   12   11  2004.0    1  0.0  1.0  0.0    0.0    0.0    0.0    0.0    0.0
1   15    6  1953.0    1  0.0  1.0  0.0    0.0    0.0    0.0    0.0    0.0
2   17    3  1981.0    1  1.0  1.0  0.0    0.0    0.0    0.0    0.0    0.0
3  210    4  2005.0    1  0.0  1.0  0.0    0.0    0.0    1.0    1.0    1.0
4   44    4  2008.0    1  0.0  1.0  0.0    0.0    0.0    0.0    1.0    1.0

   d3a  d3c  d7a  d7b                                d8a
0  0.0  0.0    1  0.0           Lack of technical skills
1  0.0  0.0    1  0.0              Uncertainty of demand
2  1.0  1.0    1  1.0                Lack of information
3  0.0  NaN    0  0.0  Difficulty in obtaining financing
4  0.0  0.0    0  0.0  Difficulty in obtaining financing

In [325]:
payment_cols = ["b14a4", "b14a5", "b14a6"]

ml_df["FinTech_Adoption"] = (
    ml_df[payment_cols]
    .fillna(0)
    .max(axis=1)
    .astype(int)
)

print(ml_df["FinTech_Adoption"].value_counts())

FinTech_Adoption
1    1357
0     162
Name: count, dtype: int64

In [326]:
print(ml_df["FinTech_Adoption"].value_counts(normalize=True) * 100)

FinTech_Adoption
1    89.335089
0    10.664911
Name: proportion, dtype: float64

In [327]:
payment_cols = ["b14a4", "b14a5", "b14a6"]

# Keep only firms with known answers for all 3 payment variables
ml_df = ml_df.dropna(subset=payment_cols).copy()

# 1 = FinTech adopted, 0 = Not adopted
ml_df["FinTech_Adoption"] = (
    ml_df[payment_cols].max(axis=1).astype(int)
)

print("Total records:", len(ml_df))
print("\nClass distribution:")
print(ml_df["FinTech_Adoption"].value_counts())

Total records: 1515

Class distribution:
FinTech_Adoption
1    1354
0     161
Name: count, dtype: int64

In [328]:
print(
    ml_df["FinTech_Adoption"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

FinTech_Adoption
1    89.37
0    10.63
Name: proportion, dtype: float64

In [329]:
from sklearn.model_selection import train_test_split

# Features
X = ml_df.drop(columns=["FinTech_Adoption", "d8a"])

# Target
y = ml_df["FinTech_Adoption"]

# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training records:", len(X_train))
print("Testing records:", len(X_test))

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

Training records: 1212
Testing records: 303

Training class distribution:
FinTech_Adoption
1    1083
0     129
Name: count, dtype: int64

Testing class distribution:
FinTech_Adoption
1    271
0     32
Name: count, dtype: int64

In [330]:
final_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv"

ml_df.to_csv(final_path, index=False)

print("Dataset saved successfully!")
print(final_path)

Dataset saved successfully!
E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv

In [331]:
final_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv"

ml_df.to_csv(final_path, index=False)

print("Dataset saved successfully!")
print(final_path)
print("Shape:", ml_df.shape)

Dataset saved successfully!
E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv
Shape: (1515, 18)

In [332]:
final_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv"

ml_df.to_csv(final_path, index=False)

print("Dataset saved successfully!")
print(final_path)
print("Shape:", ml_df.shape)

Dataset saved successfully!
E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv
Shape: (1515, 18)

In [333]:
final_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv"

ml_df.to_csv(final_path, index=False)

print("Dataset saved successfully!")
print(final_path)
print("Shape:", ml_df.shape)

Dataset saved successfully!
E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv
Shape: (1515, 18)

In [334]:
import pandas as pd

file_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_dataset.csv"

ml_df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", ml_df.shape)
print("\nColumns:")
print(ml_df.columns.tolist())

Dataset loaded successfully!
Shape: (1515, 18)

Columns:
['s7', 'a5a', 'a6', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'b14a4', 'b14a5', 'b14a6', 'd3a', 'd3c', 'd7a', 'd7b', 'd8a', 'FinTech_Adoption']

In [335]:
print("DATASET HEALTH CHECK")
print("=" * 50)

print("Number of rows:", ml_df.shape[0])
print("Number of columns:", ml_df.shape[1])

print("\nData Types:")
print(ml_df.dtypes)

print("\nMissing Values:")
print(ml_df.isnull().sum())

print("\nTotal Missing Values:", ml_df.isnull().sum().sum())

print("\nDuplicate Rows:", ml_df.duplicated().sum())

DATASET HEALTH CHECK
==================================================
Number of rows: 1515
Number of columns: 18

Data Types:
s7                    int64
a5a                   int64
a6                  float64
b5a                   int64
b5f                 float64
b5g                 float64
b5h                 float64
b13b4               float64
b13b5               float64
b14a4               float64
b14a5               float64
b14a6               float64
d3a                 float64
d3c                 float64
d7a                   int64
d7b                 float64
d8a                     str
FinTech_Adoption      int64
dtype: object

Missing Values:
s7                    0
a5a                   0
a6                    7
b5a                   0
b5f                  17
b5g                   1
b5h                  19
b13b4                 3
b13b5                 1
b14a4                 0
b14a5                 0
b14a6                 0
d3a                  60
d3c                 178
d7a                   0
d7b                  22
d8a                   0
FinTech_Adoption      0
dtype: int64

Total Missing Values: 308

Duplicate Rows: 2

In [336]:
duplicate_rows = ml_df[ml_df.duplicated(keep=False)]

print("Duplicate rows found:", len(duplicate_rows))
print("\nDuplicate records:")
display(duplicate_rows)

Duplicate rows found: 4

Duplicate records:

,s7,a5a,a6,b5a,b5f,b5g,b5h,b13b4,b13b5,b14a4,b14a5,b14a6,d3a,d3c,d7a,d7b,d8a,FinTech_Adoption
452,15,11,2004.0,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1,0.0,Lack of technical skills,1
530,15,11,2004.0,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1,0.0,Lack of technical skills,1
954,120,7,2002.0,1,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1,0.0,Lack of technical skills,1
1107,120,7,2002.0,1,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1,0.0,Lack of technical skills,1

In [337]:
# Remove completely identical rows
before = len(ml_df)

ml_df = ml_df.drop_duplicates().copy()

after = len(ml_df)

print("Duplicate rows removed:", before - after)
print("Dataset shape after removing duplicates:", ml_df.shape)

Duplicate rows removed: 2
Dataset shape after removing duplicates: (1513, 18)

In [338]:
print("FinTech Adoption - Class Distribution")
print("=" * 50)

class_counts = ml_df["FinTech_Adoption"].value_counts().sort_index()

print(class_counts)

print("\nClass Percentage:")
print((ml_df["FinTech_Adoption"].value_counts(normalize=True).sort_index() * 100).round(2))

FinTech Adoption - Class Distribution
==================================================
FinTech_Adoption
0     161
1    1352
Name: count, dtype: int64

Class Percentage:
FinTech_Adoption
0    10.64
1    89.36
Name: proportion, dtype: float64

In [339]:
print("FEATURE OVERVIEW")
print("=" * 70)

for col in ml_df.columns:
    print(f"\n{col}")
    print("Data type:", ml_df[col].dtype)
    print("Unique values:", ml_df[col].nunique())
    print("Sample values:")
    print(ml_df[col].dropna().unique()[:10])

FEATURE OVERVIEW
======================================================================

s7
Data type: int64
Unique values: 149
Sample values:
[ 12  15  17 210  44  10  56  80  28  25]

a5a
Data type: int64
Unique values: 12
Sample values:
[ 11   6   3   4 101   5 102   7   8  10]

a6
Data type: float64
Unique values: 104
Sample values:
[2004. 1953. 1981. 2005. 2008. 1987. 1984. 1983. 1966. 1989.]

b5a
Data type: int64
Unique values: 2
Sample values:
[1 0]

b5f
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b5g
Data type: float64
Unique values: 2
Sample values:
[1. 0.]

b5h
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b13b4
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b13b5
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b14a4
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b14a5
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

b14a6
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

d3a
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

d3c
Data type: float64
Unique values: 13
Sample values:
[ 0.  1.  2.  3.  7. 10.  5.  4. 15.  8.]

d7a
Data type: int64
Unique values: 2
Sample values:
[1 0]

d7b
Data type: float64
Unique values: 2
Sample values:
[0. 1.]

d8a
Data type: str
Unique values: 11
Sample values:
<StringArray>
[                                       'Lack of technical skills',
                                           'Uncertainty of demand',
                                             'Lack of information',
                               'Difficulty in obtaining financing',
             'Too costly or not convinced of the economic benefit',
           'Consumer preferences do not value quality of products',
                                  'Lack of knowledge on acquiring',
 'It is difficult or costly to comply with government regulations',
    'Electricity, water, or Internet connection are too expensive',
                                                           'Other']
Length: 10, dtype: str

FinTech_Adoption
Data type: int64
Unique values: 2
Sample values:
[0 1]

In [340]:
import pandas as pd

file_path = r"E:\Pep_Projectdetails\selected_dataset\The Firm Adoption of Technology, 2021-2023\fat_india_disclosure.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Pep_Projectdetails\\selected_dataset\\The Firm Adoption of Technology, 2021-2023\\fat_india_disclosure.csv'

In [341]:
import os

folder_path = r"E:\Pep_Projectdetails\selected_dataset\The Firm Adoption of Technology, 2021-2023"

print("Folder exists:", os.path.exists(folder_path))

if os.path.exists(folder_path):
    print("\nFiles inside the folder:")
    for file in os.listdir(folder_path):
        print(file)

Folder exists: False

In [342]:
import os

folder_path = r"E:\Pep_Projectdetails\selected_dataset"

print("Folder exists:", os.path.exists(folder_path))

if os.path.exists(folder_path):
    print("\nItems inside selected_dataset:")
    for item in os.listdir(folder_path):
        print(item)

Folder exists: True

Items inside selected_dataset:
fat_india_working.csv
feature_mapping_v1.csv
fintech_ml_dataset.csv
fintech_ml_dataset_v1.csv
fintech_policy_analysis_v1.csv
The Firm Adoption of Technology (FAT) Survey, 2021-2023
The Firm Adoption of Technology (FAT) Survey, 2021-2023.zip

In [343]:
import pandas as pd

file_path = r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (1519, 837)

In [344]:
additional_features = [
    "a7a", "a7b", "a7c", "a7d",
    "e1a", "e3g", "e4c",
    "d3b", "d5e", "d7c",
    "b5b", "b5c", "b5d", "b5e",
    "b13a",
    "d8b", "d8c"
]

print("Variable availability:")
print("=" * 50)

for col in additional_features:
    if col in df.columns:
        print(f"✓ {col}  → Available")
    else:
        print(f"✗ {col}  → NOT available")

Variable availability:
==================================================
✓ a7a  → Available
✓ a7b  → Available
✓ a7c  → Available
✓ a7d  → Available
✓ e1a  → Available
✓ e3g  → Available
✓ e4c  → Available
✓ d3b  → Available
✓ d5e  → Available
✓ d7c  → Available
✓ b5b  → Available
✓ b5c  → Available
✓ b5d  → Available
✓ b5e  → Available
✓ b13a  → Available
✓ d8b  → Available
✓ d8c  → Available

In [345]:
additional_features = [
    "a7a", "a7b", "a7c", "a7d",
    "e1a", "e3g", "e4c",
    "d3b", "d5e", "d7c",
    "b5b", "b5c", "b5d", "b5e",
    "b13a",
    "d8b", "d8c"
]

for col in additional_features:
    print("\n" + "=" * 60)
    print(f"{col}")
    print("Data type:", df[col].dtype)
    print("Non-missing:", df[col].notna().sum())
    print("Missing:", df[col].isna().sum())
    print("Unique values:", df[col].nunique(dropna=True))
    print("Top values:")
    print(df[col].value_counts(dropna=False).head(10))

============================================================
a7a
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 43
Top values:
a7a
15    188
20    151
10    144
5     112
8      83
12     72
25     70
30     59
7      52
6      50
Name: count, dtype: int64

============================================================
a7b
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 2
Top values:
a7b
2    1430
1      89
Name: count, dtype: int64

============================================================
a7c
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 6
Top values:
a7c
 4    812
 5    569
 3    116
 6     11
 2      8
-9      3
Name: count, dtype: int64

============================================================
a7d
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 3
Top values:
a7d
 2    1457
 1      59
-9       3
Name: count, dtype: int64

============================================================
e1a
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 139
Top values:
e1a
10    102
15     93
20     78
12     72
30     70
8      64
25     60
50     47
6      46
40     45
Name: count, dtype: int64

============================================================
e3g
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 3
Top values:
e3g
 2    1390
 1     126
-9       3
Name: count, dtype: int64

============================================================
e4c
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 49
Top values:
e4c
1     364
2     287
0     218
5     125
3     106
10     86
4      70
20     28
8      27
15     21
Name: count, dtype: int64

============================================================
d3b
Data type: float64
Non-missing: 437
Missing: 1082
Unique values: 13
Top values:
d3b
 NaN     1082
 12.0      90
 9.0       72
 7.0       49
 8.0       48
 10.0      46
 15.0      30
-9.0       28
 6.0       26
 11.0      25
Name: count, dtype: int64

============================================================
d5e
Data type: float64
Non-missing: 1131
Missing: 388
Unique values: 6
Top values:
d5e
 4.0    473
 NaN    388
 2.0    384
 1.0    154
 3.0    107
-9.0     11
 5.0      2
Name: count, dtype: int64

============================================================
d7c
Data type: float64
Non-missing: 436
Missing: 1083
Unique values: 6
Top values:
d7c
NaN    1083
3.0     167
5.0     145
2.0      57
1.0      45
4.0      13
6.0       9
Name: count, dtype: int64

============================================================
b5b
Data type: float64
Non-missing: 1502
Missing: 17
Unique values: 6
Top values:
b5b
3.0    926
2.0    356
5.0    114
1.0     54
6.0     30
4.0     22
NaN     17
Name: count, dtype: int64

============================================================
b5c
Data type: float64
Non-missing: 1502
Missing: 17
Unique values: 14
Top values:
b5c
 1.0      602
 2.0      289
-100.0    144
 5.0      136
 0.0      107
 3.0      102
 4.0       48
-9.0       29
 10.0      18
 NaN       17
Name: count, dtype: int64

============================================================
b5d
Data type: float64
Non-missing: 1366
Missing: 153
Unique values: 10
Top values:
b5d
 0.0     960
 1.0     287
 NaN     153
 2.0      83
 3.0      16
 4.0       8
 5.0       4
 24.0      3
 6.0       2
-9.0       2
Name: count, dtype: int64

============================================================
b5e
Data type: float64
Non-missing: 1366
Missing: 153
Unique values: 19
Top values:
b5e
15.0    322
30.0    311
10.0    178
NaN     153
20.0    146
1.0     140
25.0     69
0.0      66
5.0      40
40.0     36
Name: count, dtype: int64

============================================================
b13a
Data type: int64
Non-missing: 1519
Missing: 0
Unique values: 2
Top values:
b13a
1    1251
2     268
Name: count, dtype: int64

============================================================
d8b
Data type: str
Non-missing: 1519
Missing: 0
Unique values: 11
Top values:
d8b
Consumer preferences do not value quality of products              277
Too costly or not convinced of the economic benefit                272
Lack of technical skills                                           260
Uncertainty of demand                                              196
Difficulty in obtaining financing                                  155
Lack of information                                                152
Lack of knowledge on acquiring                                      90
It is difficult or costly to comply with government regulations     67
Electricity, water, or Internet connection are too expensive        23
Don't know                                                          17
Name: count, dtype: int64

============================================================
d8c
Data type: str
Non-missing: 1519
Missing: 0
Unique values: 11
Top values:
d8c
Difficulty in obtaining financing                                  237
Consumer preferences do not value quality of products              226
Lack of knowledge on acquiring                                     214
Too costly or not convinced of the economic benefit                193
Lack of technical skills                                           181
It is difficult or costly to comply with government regulations    143
Lack of information                                                137
Uncertainty of demand                                               90
Electricity, water, or Internet connection are too expensive        49
Don't know                                                          29
Name: count, dtype: int64

In [346]:
categorical_check = [
    "a7b",
    "a7c",
    "a7d",
    "e3g",
    "b5b",
    "b13a",
    "d5e",
    "d7c"
]

for col in categorical_check:
    print("\n" + "=" * 60)
    print(f"{col}")
    print(df[col].value_counts(dropna=False).sort_index())

============================================================
a7b
a7b
1      89
2    1430
Name: count, dtype: int64

============================================================
a7c
a7c
-9      3
 2      8
 3    116
 4    812
 5    569
 6     11
Name: count, dtype: int64

============================================================
a7d
a7d
-9       3
 1      59
 2    1457
Name: count, dtype: int64

============================================================
e3g
e3g
-9       3
 1     126
 2    1390
Name: count, dtype: int64

============================================================
b5b
b5b
1.0     54
2.0    356
3.0    926
4.0     22
5.0    114
6.0     30
NaN     17
Name: count, dtype: int64

============================================================
b13a
b13a
1    1251
2     268
Name: count, dtype: int64

============================================================
d5e
d5e
-9.0     11
 1.0    154
 2.0    384
 3.0    107
 4.0    473
 5.0      2
 NaN    388
Name: count, dtype: int64

============================================================
d7c
d7c
1.0      45
2.0      57
3.0     167
4.0      13
5.0     145
6.0       9
NaN    1083
Name: count, dtype: int64

In [347]:
selected_features = [
    # Firm characteristics
    "s7",
    "a5a",
    "a6",
    
    # Manager characteristics
    "a7a",
    "a7b",
    "a7c",
    "a7d",
    
    # Digital infrastructure
    "b5a",
    "b5b",
    "b5c",
    "b5d",
    "b5e",
    "b5f",
    "b5g",
    "b5h",
    
    # Digital business activity
    "b13a",
    "b13b4",
    "b13b5",
    
    # Finance
    "d3a",
    "d3b",
    "d3c",
    
    # Government support
    "d7a",
    "d7b",
    
    # Technology capability
    "e1a",
    "e3g",
    "e4c"
]

expanded_df = df[selected_features].copy()

print("Expanded dataset created successfully!")
print("Shape:", expanded_df.shape)

print("\nColumns:")
print(expanded_df.columns.tolist())

Expanded dataset created successfully!
Shape: (1519, 26)

Columns:
['s7', 'a5a', 'a6', 'a7a', 'a7b', 'a7c', 'a7d', 'b5a', 'b5b', 'b5c', 'b5d', 'b5e', 'b5f', 'b5g', 'b5h', 'b13a', 'b13b4', 'b13b5', 'd3a', 'd3b', 'd3c', 'd7a', 'd7b', 'e1a', 'e3g', 'e4c']

In [348]:
print("EXPANDED DATASET HEALTH CHECK")
print("=" * 60)

print("Rows:", expanded_df.shape[0])
print("Columns:", expanded_df.shape[1])

print("\nMissing values:")
missing = expanded_df.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))

print("\nTotal missing values:", expanded_df.isnull().sum().sum())

print("\nDuplicate rows:", expanded_df.duplicated().sum())

EXPANDED DATASET HEALTH CHECK
============================================================
Rows: 1519
Columns: 26

Missing values:
d3b    1082
b5e     153
b5d     153
b5c      17
b5b      17
b5f      17
b5h      17
dtype: int64

Total missing values: 1456

Duplicate rows: 0

In [349]:
print("NEGATIVE / SPECIAL VALUES")
print("=" * 60)

for col in expanded_df.columns:
    negative_values = expanded_df[col][expanded_df[col] < 0].value_counts()

    if len(negative_values) > 0:
        print(f"\n{col}")
        print(negative_values)

NEGATIVE / SPECIAL VALUES
============================================================

a6
a6
-9    7
Name: count, dtype: int64

a7a
a7a
-9    5
Name: count, dtype: int64

a7c
a7c
-9    3
Name: count, dtype: int64

a7d
a7d
-9    3
Name: count, dtype: int64

b5c
b5c
-100.0    144
-9.0       29
Name: count, dtype: int64

b5d
b5d
-9.0    2
Name: count, dtype: int64

b5e
b5e
-9.0    4
Name: count, dtype: int64

b5g
b5g
-9    1
Name: count, dtype: int64

b5h
b5h
-9.0    2
Name: count, dtype: int64

b13b4
b13b4
-9    3
Name: count, dtype: int64

b13b5
b13b5
-9    1
Name: count, dtype: int64

d3a
d3a
-9    61
Name: count, dtype: int64

d3b
d3b
-9.0    28
Name: count, dtype: int64

d3c
d3c
-9    182
Name: count, dtype: int64

d7b
d7b
-9    23
Name: count, dtype: int64

e1a
e1a
-9    1
Name: count, dtype: int64

e3g
e3g
-9    3
Name: count, dtype: int64

e4c
e4c
-9    9
Name: count, dtype: int64

In [350]:
# Create a copy for preprocessing
model_df = expanded_df.copy()

# Convert "Don't Know" code (-9) to missing value
model_df = model_df.replace(-9, pd.NA)

print("Preprocessing copy created successfully!")
print("Shape:", model_df.shape)

print("\nMissing values after converting -9:")
missing = model_df.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))

Preprocessing copy created successfully!
Shape: (1519, 26)

Missing values after converting -9:
d3b      1110
d3c       182
b5e       157
b5d       155
d3a        61
b5c        46
d7b        23
b5h        19
b5f        17
b5b        17
e4c         9
a6          7
a7a         5
a7c         3
a7d         3
b13b4       3
e3g         3
b5g         1
b13b5       1
e1a         1
dtype: int64

In [351]:
# Remove d3b because most of its values are missing
model_df = model_df.drop(columns=["d3b"])

print("Removed d3b due to high missingness.")
print("New shape:", model_df.shape)

print("\nRemaining columns:")
print(model_df.columns.tolist())

Removed d3b due to high missingness.
New shape: (1519, 25)

Remaining columns:
['s7', 'a5a', 'a6', 'a7a', 'a7b', 'a7c', 'a7d', 'b5a', 'b5b', 'b5c', 'b5d', 'b5e', 'b5f', 'b5g', 'b5h', 'b13a', 'b13b4', 'b13b5', 'd3a', 'd3c', 'd7a', 'd7b', 'e1a', 'e3g', 'e4c']

In [352]:
print("DATA TYPE & UNIQUE VALUE CHECK")
print("=" * 70)

for col in model_df.columns:
    print(
        f"{col:8} | "
        f"dtype: {str(model_df[col].dtype):8} | "
        f"unique: {model_df[col].nunique(dropna=True):4}"
    )

DATA TYPE & UNIQUE VALUE CHECK
======================================================================
s7       | dtype: int64    | unique:  149
a5a      | dtype: int64    | unique:   12
a6       | dtype: object   | unique:  104
a7a      | dtype: object   | unique:   42
a7b      | dtype: int64    | unique:    2
a7c      | dtype: object   | unique:    5
a7d      | dtype: object   | unique:    2
b5a      | dtype: int64    | unique:    2
b5b      | dtype: float64  | unique:    6
b5c      | dtype: object   | unique:   13
b5d      | dtype: object   | unique:    9
b5e      | dtype: object   | unique:   18
b5f      | dtype: float64  | unique:    2
b5g      | dtype: object   | unique:    2
b5h      | dtype: object   | unique:    2
b13a     | dtype: int64    | unique:    2
b13b4    | dtype: object   | unique:    2
b13b5    | dtype: object   | unique:    2
d3a      | dtype: object   | unique:    2
d3c      | dtype: object   | unique:   13
d7a      | dtype: int64    | unique:    2
d7b      | dtype: object   | unique:    2
e1a      | dtype: object   | unique:  138
e3g      | dtype: object   | unique:    2
e4c      | dtype: object   | unique:   48

In [353]:
print("UNIQUE VALUES OF ALL 25 FEATURES")
print("=" * 80)

for col in model_df.columns:
    values = model_df[col].dropna().unique()

    print(f"\n{col}")
    print("-" * 40)
    print(values[:30])

UNIQUE VALUES OF ALL 25 FEATURES
================================================================================

s7
----------------------------------------
[ 12  15  17 210  44  10  56  80  28  25  32   7 120 140   5  40 170 335
  65 986 300  18 155 750  60  70  35  20  30  48]

a5a
----------------------------------------
[ 11   6   3   4 101   5 102   7   8  10   9  12]

a6
----------------------------------------
[2004 1953 1981 2005 2008 1987 1984 1983 1966 1989 2010 2003 2006 1969
 1997 1994 1996 2009 2012 2000 1990 1998 1995 2015 1980 2011 2001 1960
 1993 1956]

a7a
----------------------------------------
[16 30 35 8 12 15 10 33 7 14 20 5 3 23 1 11 25 4 17 6 9 28 40 45 2 13 36
 18 19 24]

a7b
----------------------------------------
[2 1]

a7c
----------------------------------------
[3 5 4 2 6]

a7d
----------------------------------------
[2 1]

b5a
----------------------------------------
[1 2]

b5b
----------------------------------------
[3. 2. 5. 4. 1. 6.]

b5c
----------------------------------------
[1.0 2.0 -100.0 0.0 6.0 5.0 3.0 4.0 10.0 12.0 7.0 8.0 20.0]

b5d
----------------------------------------
[0.0 1.0 3.0 2.0 24.0 6.0 5.0 14.0 4.0]

b5e
----------------------------------------
[10.0 20.0 25.0 15.0 30.0 35.0 0.0 40.0 1.0 5.0 45.0 50.0 2.0 8.0 32.0
 22.0 3.0 28.0]

b5f
----------------------------------------
[2. 1.]

b5g
----------------------------------------
[1 2]

b5h
----------------------------------------
[2.0 1.0]

b13a
----------------------------------------
[2 1]

b13b4
----------------------------------------
[2 1]

b13b5
----------------------------------------
[2 1]

d3a
----------------------------------------
[2 1]

d3c
----------------------------------------
[0 1 2 3 7 10 5 4 15 8 18 31 6]

d7a
----------------------------------------
[1 2]

d7b
----------------------------------------
[2 1]

e1a
----------------------------------------
[12 15 17 210 44 10 56 70 5 32 7 120 140 40 170 335 45 986 25 105 18 155
 600 80 60 35 14 20 30 50]

e3g
----------------------------------------
[2 1]

e4c
----------------------------------------
[1 0 2 8 4 3 5 12 30 80 16 35 90 10 6 275 15 140 7 25 18 150 60 50 200 20
 11 22 40 14]

In [354]:
target_cols = ["b14a4", "b14a5", "b14a6"]

print("TARGET VARIABLE CHECK")
print("=" * 60)

for col in target_cols:
    print(f"\n{col}")
    print("-" * 40)
    print(df[col].value_counts(dropna=False))

TARGET VARIABLE CHECK
============================================================

b14a4
----------------------------------------
b14a4
 1    932
 2    585
-9      2
Name: count, dtype: int64

b14a5
----------------------------------------
b14a5
 1    1066
 2     452
-9       1
Name: count, dtype: int64

b14a6
----------------------------------------
b14a6
 1    854
 2    663
-9      2
Name: count, dtype: int64

In [355]:
# Target variables
target_cols = ["b14a4", "b14a5", "b14a6"]

# Keep only firms with known answers for all target components
target_df = df[target_cols].copy()

target_df = target_df.replace(-9, pd.NA)

# Remove firms with unknown target information
valid_target = target_df.notna().all(axis=1)

print("Total firms:", len(df))
print("Firms with complete target information:", valid_target.sum())
print("Firms removed due to unknown target:", (~valid_target).sum())

# Create Digital Payment Adoption target
y = target_df.loc[valid_target].max(axis=1).astype(int)

print("\nTarget created successfully!")
print("\nDigital Payment Adoption distribution:")
print(y.value_counts())

print("\nPercentage distribution:")
print((y.value_counts(normalize=True) * 100).round(2))

Total firms: 1519
Firms with complete target information: 1515
Firms removed due to unknown target: 4

Target created successfully!

Digital Payment Adoption distribution:
2    1021
1     494
Name: count, dtype: int64

Percentage distribution:
2    67.39
1    32.61
Name: proportion, dtype: float64

In [356]:
# Convert payment responses:
# 1 = Yes  -> 1
# 2 = No   -> 0
# -9 = Don't Know -> missing

target_df = df[target_cols].replace({
    1: 1,
    2: 0,
    -9: pd.NA
})

# Keep only firms with complete target information
valid_target = target_df.notna().all(axis=1)

# Digital Payment Adoption:
# 1 = uses at least one digital payment method
# 0 = uses none of the three
y = target_df.loc[valid_target].max(axis=1).astype(int)

print("Target created correctly!")
print("Valid firms:", len(y))

print("\nDigital Payment Adoption:")
print(y.value_counts().sort_index())

print("\nPercentage:")
print((y.value_counts(normalize=True).sort_index() * 100).round(2))

Target created correctly!
Valid firms: 1515

Digital Payment Adoption:
0     161
1    1354
Name: count, dtype: int64

Percentage:
0    10.63
1    89.37
Name: proportion, dtype: float64

In [357]:
print("FEATURE-TARGET ALIGNMENT")
print("=" * 60)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nSame number of rows:", len(X) == len(y))
print("Same indices:", X.index.equals(y.index))

FEATURE-TARGET ALIGNMENT
============================================================
X shape: (1515, 16)
y shape: (1515,)

Same number of rows: True
Same indices: True

In [358]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train-Test Split Completed!")
print("=" * 50)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Train-Test Split Completed!
==================================================
X_train: (1212, 16)
X_test : (303, 16)
y_train: (1212,)
y_test : (303,)

Training target distribution:
1    1083
0     129
Name: count, dtype: int64

Testing target distribution:
1    271
0     32
Name: count, dtype: int64

In [359]:
print("Features used for the model:")
print("=" * 50)

for i, col in enumerate(X.columns, start=1):
    print(i, "→", col)

Features used for the model:
==================================================
1 → s7
2 → a5a
3 → a6
4 → b5a
5 → b5f
6 → b5g
7 → b5h
8 → b13b4
9 → b13b5
10 → b14a4
11 → b14a5
12 → b14a6
13 → d3a
14 → d3c
15 → d7a
16 → d7b

In [360]:
# Remove target-related columns to avoid target leakage

leakage_columns = ["b14a4", "b14a5", "b14a6"]

X = X.drop(columns=leakage_columns)

print("Target leakage columns removed!")
print("=" * 50)

print("New X shape:", X.shape)

print("\nRemaining features:")
for i, col in enumerate(X.columns, start=1):
    print(i, "→", col)

Target leakage columns removed!
==================================================
New X shape: (1515, 13)

Remaining features:
1 → s7
2 → a5a
3 → a6
4 → b5a
5 → b5f
6 → b5g
7 → b5h
8 → b13b4
9 → b13b5
10 → d3a
11 → d3c
12 → d7a
13 → d7b

In [361]:
# Separate numerical and categorical features

numerical_features = [
    "s7",
    "a6",
    "d3c"
]

categorical_features = [
    "a5a",
    "b5a",
    "b5f",
    "b5g",
    "b5h",
    "b13b4",
    "b13b5",
    "d3a",
    "d7a",
    "d7b"
]

print("Numerical Features:")
print("=" * 40)
for col in numerical_features:
    print("→", col)

print("\nCategorical Features:")
print("=" * 40)
for col in categorical_features:
    print("→", col)

print("\nTotal features:", len(numerical_features) + len(categorical_features))

Numerical Features:
========================================
→ s7
→ a6
→ d3c

Categorical Features:
========================================
→ a5a
→ b5a
→ b5f
→ b5g
→ b5h
→ b13b4
→ b13b5
→ d3a
→ d7a
→ d7b

Total features: 13

In [362]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Numerical preprocessing
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

# Categorical preprocessing
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine both preprocessing pipelines
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

print("Preprocessing pipeline created successfully! ✅")

Preprocessing pipeline created successfully! ✅

In [363]:
# Create final ML dataset with features + target

ml_dataset = X.copy()
ml_dataset["Digital_Payment_Adoption"] = y

# Save the dataset
output_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"

ml_dataset.to_csv(output_path, index=False)

print("Final ML dataset saved successfully! ✅")
print("=" * 60)
print("File:", output_path)
print("Shape:", ml_dataset.shape)

print("\nTarget distribution:")
print(ml_dataset["Digital_Payment_Adoption"].value_counts())

Final ML dataset saved successfully! ✅
============================================================
File: E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv
Shape: (1515, 14)

Target distribution:
Digital_Payment_Adoption
1    1354
0     161
Name: count, dtype: int64

In [364]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Model 1: Logistic Regression with balanced class weights
logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

# Train the model
logistic_model.fit(X_train, y_train)

print("Model 1 trained successfully! ✅")
print("=" * 60)
print("Model: Logistic Regression")
print("Class Weight: balanced")
print("Training samples:", len(X_train))

Model 1 trained successfully! ✅
============================================================
Model: Logistic Regression
Class Weight: balanced
Training samples: 1212

d:\FinTech_AI_Project\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [365]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
import time

# Numerical preprocessing
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical preprocessing
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine preprocessing
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

# Model 1: Logistic Regression + Balanced Class Weight
logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Start training timer
start_time = time.perf_counter()

# Train model
logistic_model.fit(X_train, y_train)

# End training timer
training_time = time.perf_counter() - start_time

print("Model 1 retrained successfully! ✅")
print("=" * 60)
print("Model       : Logistic Regression")
print("Class Weight: balanced")
print("Max Iter    : 2000")
print(f"Training Time: {training_time:.4f} seconds")

Model 1 retrained successfully! ✅
============================================================
Model       : Logistic Regression
Class Weight: balanced
Max Iter    : 2000
Training Time: 0.0583 seconds

In [366]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)
import pandas as pd
import time

# -----------------------------
# TRAINING DATA EVALUATION
# -----------------------------
train_start = time.perf_counter()

y_train_pred = logistic_model.predict(X_train)
y_train_prob = logistic_model.predict_proba(X_train)[:, 1]

train_wall_time = time.perf_counter() - train_start

train_cm = confusion_matrix(y_train, y_train_pred)

train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, zero_division=0)
train_recall = recall_score(y_train, y_train_pred, zero_division=0)
train_f1 = f1_score(y_train, y_train_pred, zero_division=0)
train_roc_auc = roc_auc_score(y_train, y_train_prob)
train_pr_auc = average_precision_score(y_train, y_train_prob)


# -----------------------------
# TESTING DATA EVALUATION
# -----------------------------
test_start = time.perf_counter()

y_test_pred = logistic_model.predict(X_test)
y_test_prob = logistic_model.predict_proba(X_test)[:, 1]

test_wall_time = time.perf_counter() - test_start

test_cm = confusion_matrix(y_test, y_test_pred)

test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, zero_division=0)
test_recall = recall_score(y_test, y_test_pred, zero_division=0)
test_f1 = f1_score(y_test, y_test_pred, zero_division=0)
test_roc_auc = roc_auc_score(y_test, y_test_prob)
test_pr_auc = average_precision_score(y_test, y_test_prob)


# -----------------------------
# RESULTS TABLE
# -----------------------------
results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Class_Weight": "balanced",
        "Dataset": "Training",
        "Samples": len(y_train),
        "Accuracy": train_accuracy,
        "Precision": train_precision,
        "Recall": train_recall,
        "F1_Score": train_f1,
        "ROC_AUC": train_roc_auc,
        "PR_AUC": train_pr_auc,
        "TN": train_cm[0, 0],
        "FP": train_cm[0, 1],
        "FN": train_cm[1, 0],
        "TP": train_cm[1, 1],
        "Wall_Time_Seconds": train_wall_time,
        "Training_Time_Seconds": training_time
    },
    {
        "Model": "Logistic Regression",
        "Class_Weight": "balanced",
        "Dataset": "Testing",
        "Samples": len(y_test),
        "Accuracy": test_accuracy,
        "Precision": test_precision,
        "Recall": test_recall,
        "F1_Score": test_f1,
        "ROC_AUC": test_roc_auc,
        "PR_AUC": test_pr_auc,
        "TN": test_cm[0, 0],
        "FP": test_cm[0, 1],
        "FN": test_cm[1, 0],
        "TP": test_cm[1, 1],
        "Wall_Time_Seconds": test_wall_time,
        "Training_Time_Seconds": training_time
    }
])


# -----------------------------
# SAVE RESULTS
# -----------------------------
results_path = r"E:\Pep_Projectdetails\selected_dataset\model_results.csv"

results.to_csv(results_path, index=False)


# -----------------------------
# DISPLAY RESULTS
# -----------------------------
print("MODEL 1 EVALUATION COMPLETED! ✅")
print("=" * 70)

print("\nResults:")
print(results.to_string(index=False))

print("\n\nConfusion Matrix - Training:")
print(train_cm)

print("\nConfusion Matrix - Testing:")
print(test_cm)

print("\nResults saved to:")
print(results_path)

MODEL 1 EVALUATION COMPLETED! ✅
======================================================================

Results:
              Model Class_Weight  Dataset  Samples  Accuracy  Precision   Recall  F1_Score  ROC_AUC   PR_AUC  TN  FP  FN  TP  Wall_Time_Seconds  Training_Time_Seconds
Logistic Regression     balanced Training     1212  0.759901   0.966981 0.757156  0.849301 0.834353 0.974751 101  28 263 820           0.022795               0.058313
Logistic Regression     balanced  Testing      303  0.778878   0.963636 0.782288  0.863544 0.863699 0.982125  24   8  59 212           0.014330               0.058313


Confusion Matrix - Training:
[[101  28]
 [263 820]]

Confusion Matrix - Testing:
[[ 24   8]
 [ 59 212]]

Results saved to:
E:\Pep_Projectdetails\selected_dataset\model_results.csv

In [367]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)
import time
import pandas as pd

# ==========================================
# MODEL 2: RANDOM FOREST
# ==========================================

random_forest_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

# ------------------------------------------
# Training
# ------------------------------------------

start_time = time.perf_counter()

random_forest_model.fit(X_train, y_train)

training_time_rf = time.perf_counter() - start_time

print("Model 2 trained successfully! ✅")
print("=" * 60)
print("Model        : Random Forest")
print("Trees        : 300")
print("Class Weight : balanced")
print(f"Training Time: {training_time_rf:.4f} seconds")


# ==========================================
# FUNCTION TO CALCULATE METRICS
# ==========================================

def evaluate_model(model, X_data, y_data):

    start = time.perf_counter()

    predictions = model.predict(X_data)
    probabilities = model.predict_proba(X_data)[:, 1]

    wall_time = time.perf_counter() - start

    cm = confusion_matrix(y_data, predictions)

    return {
        "Accuracy": accuracy_score(y_data, predictions),
        "Precision": precision_score(y_data, predictions, zero_division=0),
        "Recall": recall_score(y_data, predictions, zero_division=0),
        "F1_Score": f1_score(y_data, predictions, zero_division=0),
        "ROC_AUC": roc_auc_score(y_data, probabilities),
        "PR_AUC": average_precision_score(y_data, probabilities),
        "TN": cm[0, 0],
        "FP": cm[0, 1],
        "FN": cm[1, 0],
        "TP": cm[1, 1],
        "Wall_Time_Seconds": wall_time
    }


# ==========================================
# TRAINING RESULTS
# ==========================================

rf_train = evaluate_model(
    random_forest_model,
    X_train,
    y_train
)

# ==========================================
# TESTING RESULTS
# ==========================================

rf_test = evaluate_model(
    random_forest_model,
    X_test,
    y_test
)


# ==========================================
# CREATE RESULTS TABLE
# ==========================================

rf_results = pd.DataFrame([
    {
        "Model": "Random Forest",
        "Class_Weight": "balanced",
        "Dataset": "Training",
        "Samples": len(y_train),
        **rf_train,
        "Training_Time_Seconds": training_time_rf
    },
    {
        "Model": "Random Forest",
        "Class_Weight": "balanced",
        "Dataset": "Testing",
        "Samples": len(y_test),
        **rf_test,
        "Training_Time_Seconds": training_time_rf
    }
])


# ==========================================
# APPEND TO EXISTING RESULTS
# ==========================================

results_path = r"E:\Pep_Projectdetails\selected_dataset\model_results.csv"

try:
    old_results = pd.read_csv(results_path)
    all_results = pd.concat(
        [old_results, rf_results],
        ignore_index=True
    )
except FileNotFoundError:
    all_results = rf_results

all_results.to_csv(results_path, index=False)


# ==========================================
# DISPLAY
# ==========================================

print("\n" + "=" * 70)
print("RANDOM FOREST RESULTS")
print("=" * 70)

print(rf_results.to_string(index=False))

print("\nTesting Confusion Matrix:")
print(
    [[rf_test["TN"], rf_test["FP"]],
     [rf_test["FN"], rf_test["TP"]]]
)

print("\nAll model results saved to:")
print(results_path)

Model 2 trained successfully! ✅
============================================================
Model        : Random Forest
Trees        : 300
Class Weight : balanced
Training Time: 0.5656 seconds

PermissionError: [Errno 13] Permission denied: 'E:\\Pep_Projectdetails\\selected_dataset\\model_results.csv'

In [368]:
# Save Model 2 results into the existing results CSV

results_path = r"E:\Pep_Projectdetails\selected_dataset\model_results.csv"

old_results = pd.read_csv(results_path)

all_results = pd.concat(
    [old_results, rf_results],
    ignore_index=True
)

all_results.to_csv(results_path, index=False)

print("Model 2 results saved successfully! ✅")
print("=" * 60)
print("Total result rows:", len(all_results))
print("\nSaved file:")
print(results_path)

print("\nAll saved results:")
print(all_results.to_string(index=False))

Model 2 results saved successfully! ✅
============================================================
Total result rows: 4

Saved file:
E:\Pep_Projectdetails\selected_dataset\model_results.csv

All saved results:
              Model Class_Weight  Dataset  Samples  Accuracy  Precision   Recall  F1_Score  ROC_AUC   PR_AUC  TN  FP  FN   TP  Wall_Time_Seconds  Training_Time_Seconds
Logistic Regression     balanced Training     1212  0.759901   0.966981 0.757156  0.849301 0.834353 0.974751 101  28 263  820           0.022795               0.058313
Logistic Regression     balanced  Testing      303  0.778878   0.963636 0.782288  0.863544 0.863699 0.982125  24   8  59  212           0.014330               0.058313
      Random Forest     balanced Training     1212  0.996700   1.000000 0.996307  0.998150 1.000000 1.000000 129   0   4 1079           0.210702               0.565647
      Random Forest     balanced  Testing      303  0.861386   0.922509 0.922509  0.922509 0.852226 0.980174  11  21  21  250           0.180475               0.565647

In [369]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Clean Train/Test Split")
print("----------------------")
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Clean Train/Test Split
----------------------
X_train: (1212, 13)
X_test : (303, 13)
y_train: (1212,)
y_test : (303,)

Training target distribution:
1    1083
0     129
Name: count, dtype: int64

Testing target distribution:
1    271
0     32
Name: count, dtype: int64

In [370]:
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, precision_score, recall_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# 5-Fold Stratified Cross-Validation
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Metrics
scoring = {
    "f1_macro": "f1_macro",
    "roc_auc": "roc_auc",
    "pr_auc": "average_precision",
    "class0_precision": make_scorer(
        precision_score,
        pos_label=0,
        zero_division=0
    ),
    "class0_recall": make_scorer(
        recall_score,
        pos_label=0,
        zero_division=0
    )
}

# Fresh Logistic Regression model for CV
lr_cv_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Run 5-Fold CV on TRAINING DATA only
lr_cv_results = cross_validate(
    lr_cv_model,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    return_train_score=True,
    n_jobs=-1
)

print("5-Fold Cross-Validation - Logistic Regression")
print("-----------------------------------------------")

for metric in scoring.keys():
    test_scores = lr_cv_results[f"test_{metric}"]
    
    print(
        f"{metric}: "
        f"Mean = {test_scores.mean():.4f}, "
        f"Std = {test_scores.std():.4f}"
    )

5-Fold Cross-Validation - Logistic Regression
-----------------------------------------------
f1_macro: Mean = 0.6042, Std = 0.0361
roc_auc: Mean = 0.7937, Std = 0.0475
pr_auc: Mean = 0.9654, Std = 0.0110
class0_precision: Mean = 0.2513, Std = 0.0385
class0_recall: Mean = 0.7062, Std = 0.0810

In [371]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

# Fresh Random Forest model for CV
rf_cv_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

# Run 5-Fold CV on TRAINING DATA ONLY
rf_cv_results = cross_validate(
    rf_cv_model,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    return_train_score=True,
    n_jobs=-1
)

print("5-Fold Cross-Validation - Random Forest")
print("----------------------------------------")

for metric in scoring.keys():
    test_scores = rf_cv_results[f"test_{metric}"]
    
    print(
        f"{metric}: "
        f"Mean = {test_scores.mean():.4f}, "
        f"Std = {test_scores.std():.4f}"
    )

5-Fold Cross-Validation - Random Forest
----------------------------------------
f1_macro: Mean = 0.6278, Std = 0.0298
roc_auc: Mean = 0.7732, Std = 0.0449
pr_auc: Mean = 0.9607, Std = 0.0125
class0_precision: Mean = 0.3292, Std = 0.0516
class0_recall: Mean = 0.3492, Std = 0.0569

In [372]:
import pandas as pd

# Create CV summary
cv_summary = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "F1_Macro_Mean": lr_cv_results["test_f1_macro"].mean(),
        "F1_Macro_Std": lr_cv_results["test_f1_macro"].std(),
        "ROC_AUC_Mean": lr_cv_results["test_roc_auc"].mean(),
        "ROC_AUC_Std": lr_cv_results["test_roc_auc"].std(),
        "PR_AUC_Mean": lr_cv_results["test_pr_auc"].mean(),
        "PR_AUC_Std": lr_cv_results["test_pr_auc"].std(),
        "Class0_Precision_Mean": lr_cv_results["test_class0_precision"].mean(),
        "Class0_Precision_Std": lr_cv_results["test_class0_precision"].std(),
        "Class0_Recall_Mean": lr_cv_results["test_class0_recall"].mean(),
        "Class0_Recall_Std": lr_cv_results["test_class0_recall"].std(),
        "Folds": 5
    },
    {
        "Model": "Random Forest",
        "F1_Macro_Mean": rf_cv_results["test_f1_macro"].mean(),
        "F1_Macro_Std": rf_cv_results["test_f1_macro"].std(),
        "ROC_AUC_Mean": rf_cv_results["test_roc_auc"].mean(),
        "ROC_AUC_Std": rf_cv_results["test_roc_auc"].std(),
        "PR_AUC_Mean": rf_cv_results["test_pr_auc"].mean(),
        "PR_AUC_Std": rf_cv_results["test_pr_auc"].std(),
        "Class0_Precision_Mean": rf_cv_results["test_class0_precision"].mean(),
        "Class0_Precision_Std": rf_cv_results["test_class0_precision"].std(),
        "Class0_Recall_Mean": rf_cv_results["test_class0_recall"].mean(),
        "Class0_Recall_Std": rf_cv_results["test_class0_recall"].std(),
        "Folds": 5
    }
])

# Save CSV
cv_output_path = r"E:\Pep_Projectdetails\selected_dataset\cv_results.csv"
cv_summary.to_csv(cv_output_path, index=False)

print("CV results saved successfully!")
print("File:", cv_output_path)
print("Shape:", cv_summary.shape)

print("\nSaved CV Results:")
display(cv_summary)

CV results saved successfully!
File: E:\Pep_Projectdetails\selected_dataset\cv_results.csv
Shape: (2, 12)

Saved CV Results:

,Model,F1_Macro_Mean,F1_Macro_Std,ROC_AUC_Mean,ROC_AUC_Std,PR_AUC_Mean,PR_AUC_Std,Class0_Precision_Mean,Class0_Precision_Std,Class0_Recall_Mean,Class0_Recall_Std,Folds
0,Logistic Regression,0.604213,0.036098,0.793735,0.047480,0.965437,0.010984,0.251321,0.038540,0.706154,0.081029,5
1,Random Forest,0.627778,0.029817,0.773224,0.044927,0.960684,0.012454,0.329192,0.051563,0.349231,0.056861,5

In [373]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score, precision_score, recall_score
import numpy as np
import pandas as pd

# Generate out-of-fold probabilities using TRAINING DATA only
lr_oof_prob = cross_val_predict(
    lr_cv_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

# Thresholds to test
thresholds = np.arange(0.10, 0.91, 0.01)

threshold_results = []

for threshold in thresholds:
    y_pred = (lr_oof_prob >= threshold).astype(int)

    threshold_results.append({
        "Threshold": threshold,
        "Macro_F1": f1_score(y_train, y_pred, average="macro"),
        "Class0_Precision": precision_score(
            y_train, y_pred, pos_label=0, zero_division=0
        ),
        "Class0_Recall": recall_score(
            y_train, y_pred, pos_label=0, zero_division=0
        )
    })

threshold_df = pd.DataFrame(threshold_results)

# Select threshold with highest Macro-F1
best_row = threshold_df.loc[
    threshold_df["Macro_F1"].idxmax()
]

best_threshold = best_row["Threshold"]

print("Logistic Regression Threshold Tuning")
print("------------------------------------")
print(f"Best Threshold: {best_threshold:.2f}")
print(f"Macro F1: {best_row['Macro_F1']:.4f}")
print(f"Class 0 Precision: {best_row['Class0_Precision']:.4f}")
print(f"Class 0 Recall: {best_row['Class0_Recall']:.4f}")

print("\nTop 10 Thresholds by Macro-F1:")
display(
    threshold_df
    .sort_values("Macro_F1", ascending=False)
    .head(10)
)

Logistic Regression Threshold Tuning
------------------------------------
Best Threshold: 0.36
Macro F1: 0.6673
Class 0 Precision: 0.3443
Class 0 Recall: 0.5659

Top 10 Thresholds by Macro-F1:

    Threshold  Macro_F1  Class0_Precision  Class0_Recall
26       0.36  0.667269          0.344340       0.565891
27       0.37  0.666770          0.339286       0.589147
28       0.38  0.666382          0.336207       0.604651
29       0.39  0.665096          0.331950       0.620155
30       0.40  0.657348          0.318898       0.627907
23       0.33  0.653318          0.336957       0.480620
32       0.42  0.653273          0.310219       0.658915
31       0.41  0.653081          0.311787       0.635659
25       0.35  0.652722          0.328358       0.511628
21       0.31  0.651273          0.337079       0.465116

In [374]:
import time
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

# Fit Logistic Regression on the complete training data
start_time = time.perf_counter()

lr_cv_model.fit(X_train, y_train)

training_time = time.perf_counter() - start_time

# Get probability predictions for the untouched test set
start_time = time.perf_counter()

test_prob = lr_cv_model.predict_proba(X_test)[:, 1]

wall_time = time.perf_counter() - start_time

# Apply tuned threshold
tuned_threshold = 0.36
y_test_pred_tuned = (test_prob >= tuned_threshold).astype(int)

# Metrics
accuracy = accuracy_score(y_test, y_test_pred_tuned)
precision = precision_score(y_test, y_test_pred_tuned, zero_division=0)
recall = recall_score(y_test, y_test_pred_tuned, zero_division=0)
f1 = f1_score(y_test, y_test_pred_tuned, zero_division=0)

macro_f1 = f1_score(
    y_test,
    y_test_pred_tuned,
    average="macro"
)

roc_auc = roc_auc_score(y_test, test_prob)
pr_auc = average_precision_score(y_test, test_prob)

class0_precision = precision_score(
    y_test,
    y_test_pred_tuned,
    pos_label=0,
    zero_division=0
)

class0_recall = recall_score(
    y_test,
    y_test_pred_tuned,
    pos_label=0,
    zero_division=0
)

cm = confusion_matrix(y_test, y_test_pred_tuned)

tn, fp, fn, tp = cm.ravel()

print("Logistic Regression - Tuned Threshold Test")
print("-------------------------------------------")
print(f"Threshold       : {tuned_threshold:.2f}")
print(f"Accuracy        : {accuracy:.4f}")
print(f"Precision       : {precision:.4f}")
print(f"Recall          : {recall:.4f}")
print(f"F1 Score        : {f1:.4f}")
print(f"Macro F1        : {macro_f1:.4f}")
print(f"ROC-AUC         : {roc_auc:.4f}")
print(f"PR-AUC          : {pr_auc:.4f}")
print(f"Class 0 Precision: {class0_precision:.4f}")
print(f"Class 0 Recall   : {class0_recall:.4f}")

print("\nConfusion Matrix:")
print(cm)

print(f"\nTraining Time   : {training_time:.4f} seconds")
print(f"Prediction Time : {wall_time:.4f} seconds")

Logistic Regression - Tuned Threshold Test
-------------------------------------------
Threshold       : 0.36
Accuracy        : 0.8416
Precision       : 0.9478
Recall          : 0.8708
F1 Score        : 0.9077
Macro F1        : 0.6748
ROC-AUC         : 0.8637
PR-AUC          : 0.9821
Class 0 Precision: 0.3519
Class 0 Recall   : 0.5938

Confusion Matrix:
[[ 19  13]
 [ 35 236]]

Training Time   : 0.0291 seconds
Prediction Time : 0.0046 seconds

In [375]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score, precision_score, recall_score
import numpy as np
import pandas as pd

# Generate out-of-fold probabilities using TRAINING DATA only
rf_oof_prob = cross_val_predict(
    rf_cv_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

# Thresholds to test
thresholds = np.arange(0.10, 0.91, 0.01)

rf_threshold_results = []

for threshold in thresholds:
    y_pred = (rf_oof_prob >= threshold).astype(int)

    rf_threshold_results.append({
        "Threshold": threshold,
        "Macro_F1": f1_score(
            y_train,
            y_pred,
            average="macro"
        ),
        "Class0_Precision": precision_score(
            y_train,
            y_pred,
            pos_label=0,
            zero_division=0
        ),
        "Class0_Recall": recall_score(
            y_train,
            y_pred,
            pos_label=0,
            zero_division=0
        )
    })

rf_threshold_df = pd.DataFrame(rf_threshold_results)

# Select threshold with highest Macro-F1
best_rf_row = rf_threshold_df.loc[
    rf_threshold_df["Macro_F1"].idxmax()
]

best_rf_threshold = best_rf_row["Threshold"]

print("Random Forest Threshold Tuning")
print("------------------------------")
print(f"Best Threshold     : {best_rf_threshold:.2f}")
print(f"Macro F1           : {best_rf_row['Macro_F1']:.4f}")
print(f"Class 0 Precision  : {best_rf_row['Class0_Precision']:.4f}")
print(f"Class 0 Recall     : {best_rf_row['Class0_Recall']:.4f}")

print("\nTop 10 Thresholds by Macro-F1:")

display(
    rf_threshold_df
    .sort_values("Macro_F1", ascending=False)
    .head(10)
)

Random Forest Threshold Tuning
------------------------------
Best Threshold     : 0.44
Macro F1           : 0.6330
Class 0 Precision  : 0.3786
Class 0 Recall     : 0.3023

Top 10 Thresholds by Macro-F1:

    Threshold  Macro_F1  Class0_Precision  Class0_Recall
34       0.44  0.632976          0.378641       0.302326
58       0.68  0.631783          0.285714       0.573643
33       0.43  0.630122          0.376238       0.294574
50       0.60  0.629783          0.296482       0.457364
39       0.49  0.629490          0.335878       0.341085
40       0.50  0.629283          0.330882       0.348837
35       0.45  0.629148          0.364486       0.302326
32       0.42  0.629140          0.381443       0.286822
36       0.46  0.629017          0.350427       0.317829
43       0.53  0.628518          0.317881       0.372093

In [376]:
import time
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

# Fit Random Forest on the complete training data
start_time = time.perf_counter()

rf_cv_model.fit(X_train, y_train)

training_time_rf_tuned = time.perf_counter() - start_time

# Get probability predictions for the untouched test set
start_time = time.perf_counter()

rf_test_prob = rf_cv_model.predict_proba(X_test)[:, 1]

prediction_time_rf_tuned = time.perf_counter() - start_time

# Apply tuned threshold
tuned_rf_threshold = 0.44
y_test_pred_rf_tuned = (
    rf_test_prob >= tuned_rf_threshold
).astype(int)

# Metrics
accuracy_rf = accuracy_score(
    y_test,
    y_test_pred_rf_tuned
)

precision_rf = precision_score(
    y_test,
    y_test_pred_rf_tuned,
    zero_division=0
)

recall_rf = recall_score(
    y_test,
    y_test_pred_rf_tuned,
    zero_division=0
)

f1_rf = f1_score(
    y_test,
    y_test_pred_rf_tuned,
    zero_division=0
)

macro_f1_rf = f1_score(
    y_test,
    y_test_pred_rf_tuned,
    average="macro"
)

roc_auc_rf = roc_auc_score(
    y_test,
    rf_test_prob
)

pr_auc_rf = average_precision_score(
    y_test,
    rf_test_prob
)

class0_precision_rf = precision_score(
    y_test,
    y_test_pred_rf_tuned,
    pos_label=0,
    zero_division=0
)

class0_recall_rf = recall_score(
    y_test,
    y_test_pred_rf_tuned,
    pos_label=0,
    zero_division=0
)

# Confusion matrix
cm_rf = confusion_matrix(
    y_test,
    y_test_pred_rf_tuned
)

tn_rf, fp_rf, fn_rf, tp_rf = cm_rf.ravel()

print("Random Forest - Tuned Threshold Test")
print("------------------------------------")
print(f"Threshold        : {tuned_rf_threshold:.2f}")
print(f"Accuracy         : {accuracy_rf:.4f}")
print(f"Precision        : {precision_rf:.4f}")
print(f"Recall           : {recall_rf:.4f}")
print(f"F1 Score         : {f1_rf:.4f}")
print(f"Macro F1         : {macro_f1_rf:.4f}")
print(f"ROC-AUC          : {roc_auc_rf:.4f}")
print(f"PR-AUC           : {pr_auc_rf:.4f}")
print(f"Class 0 Precision: {class0_precision_rf:.4f}")
print(f"Class 0 Recall   : {class0_recall_rf:.4f}")

print("\nConfusion Matrix:")
print(cm_rf)

print(f"\nTraining Time    : {training_time_rf_tuned:.4f} seconds")
print(f"Prediction Time  : {prediction_time_rf_tuned:.4f} seconds")

Random Forest - Tuned Threshold Test
------------------------------------
Threshold        : 0.44
Accuracy         : 0.8878
Precision        : 0.9247
Recall           : 0.9520
F1 Score         : 0.9382
Macro F1         : 0.6655
ROC-AUC          : 0.8522
PR-AUC           : 0.9802
Class 0 Precision: 0.4583
Class 0 Recall   : 0.3438

Confusion Matrix:
[[ 11  21]
 [ 13 258]]

Training Time    : 0.3424 seconds
Prediction Time  : 0.1688 seconds

In [377]:
import pandas as pd

# Create threshold experiment summary
threshold_summary = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Threshold": 0.50,
        "Accuracy": 0.778878,
        "Precision": 0.963636,
        "Recall": 0.782288,
        "F1_Score": 0.863544,
        "Macro_F1": None,
        "ROC_AUC": 0.863699,
        "PR_AUC": 0.982125,
        "Class0_Precision": 0.288889,
        "Class0_Recall": 0.750000,
        "TN": 24,
        "FP": 8,
        "FN": 59,
        "TP": 212,
        "Training_Time_Seconds": 0.058313,
        "Prediction_Time_Seconds": 0.014330
    },
    {
        "Model": "Logistic Regression",
        "Threshold": 0.36,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1_Score": f1,
        "Macro_F1": macro_f1,
        "ROC_AUC": roc_auc,
        "PR_AUC": pr_auc,
        "Class0_Precision": class0_precision,
        "Class0_Recall": class0_recall,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp,
        "Training_Time_Seconds": training_time,
        "Prediction_Time_Seconds": wall_time
    },
    {
        "Model": "Random Forest",
        "Threshold": 0.50,
        "Accuracy": 0.861386,
        "Precision": 0.922509,
        "Recall": 0.922509,
        "F1_Score": 0.922509,
        "Macro_F1": None,
        "ROC_AUC": 0.852226,
        "PR_AUC": 0.980174,
        "Class0_Precision": 0.343750,
        "Class0_Recall": 0.343750,
        "TN": 11,
        "FP": 21,
        "FN": 21,
        "TP": 250,
        "Training_Time_Seconds": 0.565647,
        "Prediction_Time_Seconds": 0.180475
    },
    {
        "Model": "Random Forest",
        "Threshold": 0.44,
        "Accuracy": accuracy_rf,
        "Precision": precision_rf,
        "Recall": recall_rf,
        "F1_Score": f1_rf,
        "Macro_F1": macro_f1_rf,
        "ROC_AUC": roc_auc_rf,
        "PR_AUC": pr_auc_rf,
        "Class0_Precision": class0_precision_rf,
        "Class0_Recall": class0_recall_rf,
        "TN": tn_rf,
        "FP": fp_rf,
        "FN": fn_rf,
        "TP": tp_rf,
        "Training_Time_Seconds": training_time_rf_tuned,
        "Prediction_Time_Seconds": prediction_time_rf_tuned
    }
])

# Save CSV
threshold_output_path = r"E:\Pep_Projectdetails\selected_dataset\threshold_results.csv"

threshold_summary.to_csv(
    threshold_output_path,
    index=False
)

print("Threshold results saved successfully!")
print("File:", threshold_output_path)
print("Shape:", threshold_summary.shape)

print("\nSaved Threshold Results:")
display(threshold_summary)

Threshold results saved successfully!
File: E:\Pep_Projectdetails\selected_dataset\threshold_results.csv
Shape: (4, 17)

Saved Threshold Results:

,Model,Threshold,Accuracy,Precision,Recall,F1_Score,Macro_F1,ROC_AUC,PR_AUC,Class0_Precision,Class0_Recall,TN,FP,FN,TP,Training_Time_Seconds,Prediction_Time_Seconds
0,Logistic Regression,0.50,0.778878,0.963636,0.782288,0.863544,NaN,0.863699,0.982125,0.288889,0.75000,24,8,59,212,0.058313,0.014330
1,Logistic Regression,0.36,0.841584,0.947791,0.870849,0.907692,0.674776,0.863699,0.982125,0.351852,0.59375,19,13,35,236,0.029119,0.004562
2,Random Forest,0.50,0.861386,0.922509,0.922509,0.922509,NaN,0.852226,0.980174,0.343750,0.34375,11,21,21,250,0.565647,0.180475
3,Random Forest,0.44,0.887789,0.924731,0.952030,0.938182,0.665519,0.852226,0.980174,0.458333,0.34375,11,21,13,258,0.342414,0.168811

In [378]:
# Install imbalanced-learn if needed
%pip install -U imbalanced-learn

# Check installation
import imblearn

print("imbalanced-learn version:", imblearn.__version__)
print("Installation successful ✅")

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in d:\fintech_ai_project\venv\lib\site-packages (from imbalanced-learn) (2.5.3)
Requirement already satisfied: scipy<2,>=1.11.4 in d:\fintech_ai_project\venv\lib\site-packages (from imbalanced-learn) (1.18.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in d:\fintech_ai_project\venv\lib\site-packages (from imbalanced-learn) (1.9.1)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in d:\fintech_ai_project\venv\lib\site-packages (from imbalanced-learn) (1.6.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in d:\fintech_ai_project\venv\lib\site-packages (from imbalanced-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in d:\fintech_ai_project\venv\lib\site-packages (from joblib<2,>=1.2.0->imbalanced-learn) (3.1.2)
Requirement already satisfied: narwhals>=2.0.1 in d:\fintech_ai_project\venv\lib\site-packages (from scikit-learn<2,>=1.4.2->imbalanced-learn) (2.26.0)
Downloading imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Downloading sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.14.2 sklearn-compat-0.1.6
Note: you may need to restart the kernel to use updated packages.
imbalanced-learn version: 0.14.2
Installation successful ✅

In [379]:
import imblearn
import sklearn

print("imbalanced-learn:", imblearn.__version__)
print("scikit-learn:", sklearn.__version__)
print("Current variables are still available ✅")

imbalanced-learn: 0.14.2
scikit-learn: 1.9.1
Current variables are still available ✅

In [380]:
print("Training data shape:", X_train.shape)

print("\nTraining class distribution:")
print(y_train.value_counts().sort_index())

print("\nTraining class percentage:")
print((y_train.value_counts(normalize=True).sort_index() * 100).round(2))

Training data shape: (1212, 13)

Training class distribution:
0     129
1    1083
Name: count, dtype: int64

Training class percentage:
0    10.64
1    89.36
Name: proportion, dtype: float64

In [381]:
categorical_features = [
    "a5a",
    "b5a",
    "b5f",
    "b5g",
    "b5h",
    "b13b4",
    "b13b5",
    "d3a",
    "d7a",
    "d7b"
]

numerical_features = [
    "s7",
    "a6",
    "d3c"
]

print("Categorical features:", categorical_features)
print("Number of categorical features:", len(categorical_features))

print("\nNumerical features:", numerical_features)
print("Number of numerical features:", len(numerical_features))

Categorical features: ['a5a', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'd3a', 'd7a', 'd7b']
Number of categorical features: 10

Numerical features: ['s7', 'a6', 'd3c']
Number of numerical features: 3

In [382]:
from imblearn.over_sampling import SMOTENC

# Find the column positions of categorical features
categorical_indices = [
    X_train.columns.get_loc(col)
    for col in categorical_features
]

print("Categorical feature indices:")
print(categorical_indices)

print("\nTotal categorical indices:", len(categorical_indices))

Categorical feature indices:
[1, 3, 4, 5, 6, 7, 8, 9, 11, 12]

Total categorical indices: 10

In [383]:
smotenc = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)

print("SMOTENC created successfully ✅")
print(smotenc)

SMOTENC created successfully ✅
SMOTENC(categorical_features=[1, 3, 4, 5, 6, 7, 8, 9, 11, 12], random_state=42)

In [384]:
X_train_smote, y_train_smote = smotenc.fit_resample(
    X_train,
    y_train
)

print("Original training shape:", X_train.shape)
print("SMOTENC training shape :", X_train_smote.shape)

print("\nOriginal class distribution:")
print(y_train.value_counts().sort_index())

print("\nAfter SMOTENC:")
print(y_train_smote.value_counts().sort_index())

ValueError: Input contains NaN.

In [385]:
# Check missing values in training features
missing_counts = X_train.isnull().sum()

print("Total missing values:", missing_counts.sum())

print("\nColumns containing missing values:")
print(missing_counts[missing_counts > 0].sort_values(ascending=False))

Total missing values: 256

Columns containing missing values:
d3c      150
d3a       52
d7b       19
b5h       12
b5f       11
a6         7
b13b4      3
b5g        1
b13b5      1
dtype: int64

In [386]:
from sklearn.impute import SimpleImputer

# Numerical imputer
num_imputer_smote = SimpleImputer(strategy="median")

# Categorical imputer
cat_imputer_smote = SimpleImputer(strategy="most_frequent")

print("Numerical imputer created ✅")
print("Categorical imputer created ✅")

Numerical imputer created ✅
Categorical imputer created ✅

In [387]:
# Create a copy so the original X_train remains unchanged
X_train_imputed = X_train.copy()

# Impute numerical columns
X_train_imputed[numerical_features] = num_imputer_smote.fit_transform(
    X_train[numerical_features]
)

# Impute categorical columns
X_train_imputed[categorical_features] = cat_imputer_smote.fit_transform(
    X_train[categorical_features]
)

print("Missing values before:", X_train.isnull().sum().sum())
print("Missing values after :", X_train_imputed.isnull().sum().sum())

print("\nImputed training shape:", X_train_imputed.shape)

Missing values before: 256
Missing values after : 0

Imputed training shape: (1212, 13)

In [388]:
X_train_smote, y_train_smote = smotenc.fit_resample(
    X_train_imputed,
    y_train
)

print("Original training shape:", X_train.shape)
print("After SMOTENC shape     :", X_train_smote.shape)

print("\nOriginal class distribution:")
print(y_train.value_counts().sort_index())

print("\nAfter SMOTENC:")
print(y_train_smote.value_counts().sort_index())

Original training shape: (1212, 13)
After SMOTENC shape     : (2166, 13)

Original class distribution:
0     129
1    1083
Name: count, dtype: int64

After SMOTENC:
0    1083
1    1083
Name: count, dtype: int64

In [389]:
print("Test data shape:", X_test.shape)

print("\nTest class distribution:")
print(y_test.value_counts().sort_index())

print("\nTest missing values:", X_test.isnull().sum().sum())

Test data shape: (303, 13)

Test class distribution:
0     32
1    271
Name: count, dtype: int64

Test missing values: 52

In [390]:
# Keep X_test unchanged; create a separate imputed copy
X_test_imputed = X_test.copy()

# Apply the TRAIN-FITTED imputers to test data
X_test_imputed[numerical_features] = num_imputer_smote.transform(
    X_test[numerical_features]
)

X_test_imputed[categorical_features] = cat_imputer_smote.transform(
    X_test[categorical_features]
)

print("Test missing values before:", X_test.isnull().sum().sum())
print("Test missing values after :", X_test_imputed.isnull().sum().sum())

print("Test shape:", X_test_imputed.shape)

Test missing values before: 52
Test missing values after : 0
Test shape: (303, 13)

In [391]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

smote_logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        max_iter=2000,
        random_state=42
    ))
])

print("SMOTENC + Logistic Regression pipeline created ✅")

SMOTENC + Logistic Regression pipeline created ✅

In [392]:
import time

start_time = time.perf_counter()

smote_logistic_model.fit(
    X_train_smote,
    y_train_smote
)

smote_lr_training_time = time.perf_counter() - start_time

print("SMOTENC + Logistic Regression trained successfully ✅")
print(f"Training time: {smote_lr_training_time:.6f} seconds")

SMOTENC + Logistic Regression trained successfully ✅
Training time: 0.039129 seconds

In [393]:
import time

start_time = time.perf_counter()

y_pred_smote_lr = smote_logistic_model.predict(X_test_imputed)
y_prob_smote_lr = smote_logistic_model.predict_proba(X_test_imputed)[:, 1]

smote_lr_prediction_time = time.perf_counter() - start_time

print("Predictions generated successfully ✅")
print(f"Prediction time: {smote_lr_prediction_time:.6f} seconds")
print("Number of predictions:", len(y_pred_smote_lr))

Predictions generated successfully ✅
Prediction time: 0.015912 seconds
Number of predictions: 303

In [394]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

# Basic metrics
smote_lr_accuracy = accuracy_score(y_test, y_pred_smote_lr)
smote_lr_precision = precision_score(y_test, y_pred_smote_lr, zero_division=0)
smote_lr_recall = recall_score(y_test, y_pred_smote_lr, zero_division=0)
smote_lr_f1 = f1_score(y_test, y_pred_smote_lr, zero_division=0)
smote_lr_macro_f1 = f1_score(y_test, y_pred_smote_lr, average="macro", zero_division=0)

# Probability-based metrics
smote_lr_roc_auc = roc_auc_score(y_test, y_prob_smote_lr)
smote_lr_pr_auc = average_precision_score(y_test, y_prob_smote_lr)

# Class 0 metrics
smote_lr_class0_precision = precision_score(
    y_test, y_pred_smote_lr, pos_label=0, zero_division=0
)

smote_lr_class0_recall = recall_score(
    y_test, y_pred_smote_lr, pos_label=0, zero_division=0
)

# Confusion matrix
smote_lr_cm = confusion_matrix(y_test, y_pred_smote_lr)

print("===== SMOTENC + LOGISTIC REGRESSION =====")
print(f"Accuracy          : {smote_lr_accuracy:.4f}")
print(f"Precision         : {smote_lr_precision:.4f}")
print(f"Recall            : {smote_lr_recall:.4f}")
print(f"F1 Score          : {smote_lr_f1:.4f}")
print(f"Macro-F1          : {smote_lr_macro_f1:.4f}")
print(f"ROC-AUC           : {smote_lr_roc_auc:.4f}")
print(f"PR-AUC            : {smote_lr_pr_auc:.4f}")
print(f"Class 0 Precision : {smote_lr_class0_precision:.4f}")
print(f"Class 0 Recall    : {smote_lr_class0_recall:.4f}")

print("\nConfusion Matrix:")
print(smote_lr_cm)

print("\nTraining time     :", f"{smote_lr_training_time:.6f}", "seconds")
print("Prediction time   :", f"{smote_lr_prediction_time:.6f}", "seconds")

===== SMOTENC + LOGISTIC REGRESSION =====
Accuracy          : 0.8053
Precision         : 0.9609
Recall            : 0.8155
F1 Score          : 0.8822
Macro-F1          : 0.6602
ROC-AUC           : 0.8661
PR-AUC            : 0.9824
Class 0 Precision : 0.3151
Class 0 Recall    : 0.7188

Confusion Matrix:
[[ 23   9]
 [ 50 221]]

Training time     : 0.039129 seconds
Prediction time   : 0.015912 seconds

In [395]:
from sklearn.ensemble import RandomForestClassifier

smote_rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        class_weight=None,
        random_state=42,
        n_jobs=-1
    ))
])

print("SMOTENC + Random Forest pipeline created ✅")

SMOTENC + Random Forest pipeline created ✅

In [396]:
import time

start_time = time.perf_counter()

smote_rf_model.fit(
    X_train_smote,
    y_train_smote
)

smote_rf_training_time = time.perf_counter() - start_time

print("SMOTENC + Random Forest trained successfully ✅")
print(f"Training time: {smote_rf_training_time:.6f} seconds")

SMOTENC + Random Forest trained successfully ✅
Training time: 0.353564 seconds

In [397]:
start_time = time.perf_counter()

y_pred_smote_rf = smote_rf_model.predict(X_test_imputed)
y_prob_smote_rf = smote_rf_model.predict_proba(X_test_imputed)[:, 1]

smote_rf_prediction_time = time.perf_counter() - start_time

print("Predictions generated successfully ✅")
print(f"Prediction time: {smote_rf_prediction_time:.6f} seconds")
print("Number of predictions:", len(y_pred_smote_rf))

Predictions generated successfully ✅
Prediction time: 0.108707 seconds
Number of predictions: 303

In [398]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

smote_rf_accuracy = accuracy_score(y_test, y_pred_smote_rf)
smote_rf_precision = precision_score(y_test, y_pred_smote_rf)
smote_rf_recall = recall_score(y_test, y_pred_smote_rf)
smote_rf_f1 = f1_score(y_test, y_pred_smote_rf)

smote_rf_macro_f1 = f1_score(
    y_test,
    y_pred_smote_rf,
    average="macro"
)

smote_rf_roc_auc = roc_auc_score(
    y_test,
    y_prob_smote_rf
)

smote_rf_pr_auc = average_precision_score(
    y_test,
    y_prob_smote_rf
)

smote_rf_cm = confusion_matrix(
    y_test,
    y_pred_smote_rf
)

smote_rf_class0_precision = precision_score(
    y_test,
    y_pred_smote_rf,
    pos_label=0
)

smote_rf_class0_recall = recall_score(
    y_test,
    y_pred_smote_rf,
    pos_label=0
)

print("SMOTENC + Random Forest Metrics")
print("--------------------------------")
print(f"Accuracy       : {smote_rf_accuracy:.4f}")
print(f"Precision      : {smote_rf_precision:.4f}")
print(f"Recall         : {smote_rf_recall:.4f}")
print(f"F1 Score       : {smote_rf_f1:.4f}")
print(f"Macro-F1       : {smote_rf_macro_f1:.4f}")
print(f"ROC-AUC        : {smote_rf_roc_auc:.4f}")
print(f"PR-AUC         : {smote_rf_pr_auc:.4f}")
print(f"Class 0 Precision: {smote_rf_class0_precision:.4f}")
print(f"Class 0 Recall   : {smote_rf_class0_recall:.4f}")

print("\nConfusion Matrix:")
print(smote_rf_cm)

SMOTENC + Random Forest Metrics
--------------------------------
Accuracy       : 0.8548
Precision      : 0.9316
Recall         : 0.9041
F1 Score       : 0.9176
Macro-F1       : 0.6532
ROC-AUC        : 0.8458
PR-AUC         : 0.9798
Class 0 Precision: 0.3500
Class 0 Recall   : 0.4375

Confusion Matrix:
[[ 14  18]
 [ 26 245]]

In [399]:
import pandas as pd

comparison = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Accuracy": logistic_accuracy,
        "Precision": logistic_precision,
        "Recall": logistic_recall,
        "F1": logistic_f1,
        "Macro-F1": logistic_macro_f1,
        "ROC-AUC": logistic_roc_auc,
        "PR-AUC": logistic_pr_auc,
        "Class0 Recall": logistic_class0_recall
    },
    {
        "Model": "Random Forest",
        "Accuracy": rf_accuracy,
        "Precision": rf_precision,
        "Recall": rf_recall,
        "F1": rf_f1,
        "Macro-F1": rf_macro_f1,
        "ROC-AUC": rf_roc_auc,
        "PR-AUC": rf_pr_auc,
        "Class0 Recall": rf_class0_recall
    },
    {
        "Model": "LR + Threshold",
        "Accuracy": lr_threshold_accuracy,
        "Precision": lr_threshold_precision,
        "Recall": lr_threshold_recall,
        "F1": lr_threshold_f1,
        "Macro-F1": lr_threshold_macro_f1,
        "ROC-AUC": lr_threshold_roc_auc,
        "PR-AUC": lr_threshold_pr_auc,
        "Class0 Recall": lr_threshold_class0_recall
    },
    {
        "Model": "RF + Threshold",
        "Accuracy": rf_threshold_accuracy,
        "Precision": rf_threshold_precision,
        "Recall": rf_threshold_recall,
        "F1": rf_threshold_f1,
        "Macro-F1": rf_threshold_macro_f1,
        "ROC-AUC": rf_threshold_roc_auc,
        "PR-AUC": rf_threshold_pr_auc,
        "Class0 Recall": rf_threshold_class0_recall
    },
    {
        "Model": "SMOTENC + LR",
        "Accuracy": smote_lr_accuracy,
        "Precision": smote_lr_precision,
        "Recall": smote_lr_recall,
        "F1": smote_lr_f1,
        "Macro-F1": smote_lr_macro_f1,
        "ROC-AUC": smote_lr_roc_auc,
        "PR-AUC": smote_lr_pr_auc,
        "Class0 Recall": smote_lr_class0_recall
    },
    {
        "Model": "SMOTENC + RF",
        "Accuracy": smote_rf_accuracy,
        "Precision": smote_rf_precision,
        "Recall": smote_rf_recall,
        "F1": smote_rf_f1,
        "Macro-F1": smote_rf_macro_f1,
        "ROC-AUC": smote_rf_roc_auc,
        "PR-AUC": smote_rf_pr_auc,
        "Class0 Recall": smote_rf_class0_recall
    }
])

comparison.round(4)

NameError: name 'logistic_accuracy' is not defined

In [400]:
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score
)

def calculate_metrics(y_true, y_pred, y_prob):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
        "Macro-F1": f1_score(y_true, y_pred, average="macro"),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "PR-AUC": average_precision_score(y_true, y_prob),
        "Class0 Recall": recall_score(y_true, y_pred, pos_label=0)
    }


# 1. Logistic Regression
y_pred_lr = logistic_model.predict(X_test)
y_prob_lr = logistic_model.predict_proba(X_test)[:, 1]

lr_metrics = calculate_metrics(
    y_test, y_pred_lr, y_prob_lr
)


# 2. Random Forest
y_pred_rf = random_forest_model.predict(X_test)
y_prob_rf = random_forest_model.predict_proba(X_test)[:, 1]

rf_metrics = calculate_metrics(
    y_test, y_pred_rf, y_prob_rf
)


# 3. Logistic Regression + Threshold
y_pred_lr_threshold = (y_prob_lr >= 0.36).astype(int)

lr_threshold_metrics = calculate_metrics(
    y_test, y_pred_lr_threshold, y_prob_lr
)


# 4. Random Forest + Threshold
y_pred_rf_threshold = (y_prob_rf >= 0.44).astype(int)

rf_threshold_metrics = calculate_metrics(
    y_test, y_pred_rf_threshold, y_prob_rf
)


# 5. SMOTENC + Logistic Regression
y_pred_smote_lr = smote_logistic_model.predict(X_test_imputed)
y_prob_smote_lr = smote_logistic_model.predict_proba(X_test_imputed)[:, 1]

smote_lr_metrics = calculate_metrics(
    y_test, y_pred_smote_lr, y_prob_smote_lr
)


# 6. SMOTENC + Random Forest
y_pred_smote_rf = smote_rf_model.predict(X_test_imputed)
y_prob_smote_rf = smote_rf_model.predict_proba(X_test_imputed)[:, 1]

smote_rf_metrics = calculate_metrics(
    y_test, y_pred_smote_rf, y_prob_smote_rf
)


# Create final comparison table
comparison = pd.DataFrame([
    {"Model": "Logistic Regression", **lr_metrics},
    {"Model": "Random Forest", **rf_metrics},
    {"Model": "LR + Threshold", **lr_threshold_metrics},
    {"Model": "RF + Threshold", **rf_threshold_metrics},
    {"Model": "SMOTENC + LR", **smote_lr_metrics},
    {"Model": "SMOTENC + RF", **smote_rf_metrics}
])

comparison.round(4)

,Model,Accuracy,Precision,Recall,F1,Macro-F1,ROC-AUC,PR-AUC,Class0 Recall
0,Logistic Regression,0.7855,0.9558,0.7970,0.8692,0.6364,0.8569,0.9807,0.6875
1,Random Forest,0.8614,0.9354,0.9077,0.9213,0.6690,0.8622,0.9818,0.4688
2,LR + Threshold,0.8449,0.9480,0.8745,0.9098,0.6784,0.8569,0.9807,0.5938
3,RF + Threshold,0.8713,0.9265,0.9299,0.9282,0.6546,0.8622,0.9818,0.3750
4,SMOTENC + LR,0.8053,0.9609,0.8155,0.8822,0.6602,0.8661,0.9824,0.7188
5,SMOTENC + RF,0.8548,0.9316,0.9041,0.9176,0.6532,0.8458,0.9798,0.4375

In [1]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTENC

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


# --------------------------------------------------
# 1. Column positions
# --------------------------------------------------

# X has 13 features
# First 3 = numerical
# Remaining 10 = categorical

numerical_indices = [0, 1, 2]
categorical_indices = list(range(3, 13))


# --------------------------------------------------
# 2. Imputation BEFORE SMOTENC
# --------------------------------------------------

imputation_for_smote = ColumnTransformer([
    (
        "num_imputer",
        SimpleImputer(strategy="median"),
        numerical_indices
    ),
    (
        "cat_imputer",
        SimpleImputer(strategy="most_frequent"),
        categorical_indices
    )
])


# --------------------------------------------------
# 3. Preprocessing AFTER SMOTENC
# --------------------------------------------------

preprocessor_for_smote_cv = ColumnTransformer([
    (
        "num",
        StandardScaler(),
        numerical_indices
    ),
    (
        "cat",
        OneHotEncoder(handle_unknown="ignore"),
        categorical_indices
    )
])


# --------------------------------------------------
# 4. SMOTENC
# --------------------------------------------------

smotenc_cv = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)


# --------------------------------------------------
# 5. SMOTENC + Logistic Regression
# --------------------------------------------------

smotenc_lr_cv_pipeline = ImbPipeline([
    ("imputation", imputation_for_smote),
    ("smotenc", smotenc_cv),
    ("preprocessor", preprocessor_for_smote_cv),
    ("classifier", LogisticRegression(
        max_iter=2000,
        random_state=42
    ))
])


# --------------------------------------------------
# 6. SMOTENC + Random Forest
# --------------------------------------------------

smotenc_rf_cv_pipeline = ImbPipeline([
    ("imputation", imputation_for_smote),
    ("smotenc", smotenc_cv),
    ("preprocessor", preprocessor_for_smote_cv),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])


print("Proper SMOTENC CV pipelines created successfully ✅")

Proper SMOTENC CV pipelines created successfully ✅

In [2]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    f1_score,
    roc_auc_score,
    average_precision_score,
    recall_score
)
import numpy as np
import time

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

smotenc_lr_scores = {
    "Macro-F1": [],
    "ROC-AUC": [],
    "PR-AUC": [],
    "Class0 Recall": []
}

start_time = time.perf_counter()

for fold, (train_idx, val_idx) in enumerate(cv.split(X, y), start=1):

    X_fold_train = X.iloc[train_idx]
    X_fold_val = X.iloc[val_idx]

    y_fold_train = y.iloc[train_idx]
    y_fold_val = y.iloc[val_idx]

    # Fit only on the training fold
    smotenc_lr_cv_pipeline.fit(
        X_fold_train,
        y_fold_train
    )

    # Validation predictions
    y_fold_pred = smotenc_lr_cv_pipeline.predict(
        X_fold_val
    )

    y_fold_prob = smotenc_lr_cv_pipeline.predict_proba(
        X_fold_val
    )[:, 1]

    # Metrics
    macro_f1 = f1_score(
        y_fold_val,
        y_fold_pred,
        average="macro"
    )

    roc_auc = roc_auc_score(
        y_fold_val,
        y_fold_prob
    )

    pr_auc = average_precision_score(
        y_fold_val,
        y_fold_prob
    )

    class0_recall = recall_score(
        y_fold_val,
        y_fold_pred,
        pos_label=0
    )

    smotenc_lr_scores["Macro-F1"].append(macro_f1)
    smotenc_lr_scores["ROC-AUC"].append(roc_auc)
    smotenc_lr_scores["PR-AUC"].append(pr_auc)
    smotenc_lr_scores["Class0 Recall"].append(class0_recall)

    print(
        f"Fold {fold}: "
        f"Macro-F1={macro_f1:.4f}, "
        f"ROC-AUC={roc_auc:.4f}, "
        f"PR-AUC={pr_auc:.4f}, "
        f"Class0 Recall={class0_recall:.4f}"
    )

smotenc_lr_cv_time = time.perf_counter() - start_time

print("\nSMOTENC + Logistic Regression CV completed ✅")
print(f"Total CV time: {smotenc_lr_cv_time:.4f} seconds")

print("\nMean ± Standard Deviation:")
for metric, values in smotenc_lr_scores.items():
    print(
        f"{metric}: "
        f"{np.mean(values):.4f} ± {np.std(values):.4f}"
    )

NameError: name 'X' is not defined

In [3]:
import pandas as pd

file_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"

df_ml = pd.read_csv(file_path)

print("Dataset loaded successfully ✅")
print("Shape:", df_ml.shape)
print("\nColumns:")
print(df_ml.columns.tolist())
print("\nTarget distribution:")
print(df_ml["Digital_Payment_Adoption"].value_counts())

Dataset loaded successfully ✅
Shape: (1515, 14)

Columns:
['s7', 'a5a', 'a6', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'd3a', 'd3c', 'd7a', 'd7b', 'Digital_Payment_Adoption']

Target distribution:
Digital_Payment_Adoption
1    1354
0     161
Name: count, dtype: int64

In [4]:
X = df_ml.drop(
    columns=["Digital_Payment_Adoption"]
)

y = df_ml["Digital_Payment_Adoption"]

print("X and y recreated successfully ✅")
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nMissing values in X:", X.isnull().sum().sum())
print("Missing values in y:", y.isnull().sum())

X and y recreated successfully ✅
X shape: (1515, 13)
y shape: (1515,)

Missing values in X: 308
Missing values in y: 0

In [6]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTENC

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


# Numerical columns
numerical_features = ["s7", "a6", "d3c"]

# Categorical columns
categorical_features = [
    "a5a", "b5a", "b5f", "b5g", "b5h",
    "b13b4", "b13b5", "d3a", "d7a", "d7b"
]

# Their positions inside X
numerical_indices = [
    X.columns.get_loc(col)
    for col in numerical_features
]

categorical_indices = [
    X.columns.get_loc(col)
    for col in categorical_features
]


# Imputation
imputation_for_smote = ColumnTransformer([
    (
        "num_imputer",
        SimpleImputer(strategy="median"),
        numerical_indices
    ),
    (
        "cat_imputer",
        SimpleImputer(strategy="most_frequent"),
        categorical_indices
    )
])


# Preprocessing after SMOTENC
preprocessor_for_smote_cv = ColumnTransformer([
    (
        "num",
        StandardScaler(),
        numerical_indices
    ),
    (
        "cat",
        OneHotEncoder(handle_unknown="ignore"),
        categorical_indices
    )
])


# SMOTENC
smotenc_cv = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)


# SMOTENC + Logistic Regression
smotenc_lr_cv_pipeline = ImbPipeline([
    ("imputation", imputation_for_smote),
    ("smotenc", smotenc_cv),
    ("preprocessor", preprocessor_for_smote_cv),
    ("classifier", LogisticRegression(
        max_iter=2000,
        random_state=42
    ))
])


# SMOTENC + Random Forest
smotenc_rf_cv_pipeline = ImbPipeline([
    ("imputation", imputation_for_smote),
    ("smotenc", smotenc_cv),
    ("preprocessor", preprocessor_for_smote_cv),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])


print("SMOTENC CV pipelines recreated successfully ✅")
print("Numerical indices:", numerical_indices)
print("Categorical indices:", categorical_indices)

SMOTENC CV pipelines recreated successfully ✅
Numerical indices: [0, 2, 10]
Categorical indices: [1, 3, 4, 5, 6, 7, 8, 9, 11, 12]

In [7]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    f1_score,
    roc_auc_score,
    average_precision_score,
    recall_score
)
import numpy as np
import time

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

smotenc_lr_scores = {
    "Macro-F1": [],
    "ROC-AUC": [],
    "PR-AUC": [],
    "Class0 Recall": []
}

start_time = time.perf_counter()

for fold, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    X_fold_train = X.iloc[train_idx]
    X_fold_val = X.iloc[val_idx]

    y_fold_train = y.iloc[train_idx]
    y_fold_val = y.iloc[val_idx]

    # Fit pipeline ONLY on training fold
    smotenc_lr_cv_pipeline.fit(
        X_fold_train,
        y_fold_train
    )

    # Validation predictions
    y_fold_pred = smotenc_lr_cv_pipeline.predict(
        X_fold_val
    )

    y_fold_prob = smotenc_lr_cv_pipeline.predict_proba(
        X_fold_val
    )[:, 1]

    # Metrics
    macro_f1 = f1_score(
        y_fold_val,
        y_fold_pred,
        average="macro"
    )

    roc_auc = roc_auc_score(
        y_fold_val,
        y_fold_prob
    )

    pr_auc = average_precision_score(
        y_fold_val,
        y_fold_prob
    )

    class0_recall = recall_score(
        y_fold_val,
        y_fold_pred,
        pos_label=0
    )

    smotenc_lr_scores["Macro-F1"].append(macro_f1)
    smotenc_lr_scores["ROC-AUC"].append(roc_auc)
    smotenc_lr_scores["PR-AUC"].append(pr_auc)
    smotenc_lr_scores["Class0 Recall"].append(class0_recall)

    print(
        f"Fold {fold}: "
        f"Macro-F1={macro_f1:.4f}, "
        f"ROC-AUC={roc_auc:.4f}, "
        f"PR-AUC={pr_auc:.4f}, "
        f"Class0 Recall={class0_recall:.4f}"
    )

smotenc_lr_cv_time = time.perf_counter() - start_time

print("\nSMOTENC + Logistic Regression CV completed ✅")
print(f"Total CV time: {smotenc_lr_cv_time:.4f} seconds")

print("\nMean ± Standard Deviation:")

for metric, values in smotenc_lr_scores.items():
    print(
        f"{metric}: "
        f"{np.mean(values):.4f} ± {np.std(values):.4f}"
    )

Fold 1: Macro-F1=0.6455, ROC-AUC=0.8292, PR-AUC=0.9745, Class0 Recall=0.6667
Fold 2: Macro-F1=0.6228, ROC-AUC=0.7644, PR-AUC=0.9554, Class0 Recall=0.5938
Fold 3: Macro-F1=0.5614, ROC-AUC=0.7214, PR-AUC=0.9546, Class0 Recall=0.4375
Fold 4: Macro-F1=0.6020, ROC-AUC=0.7756, PR-AUC=0.9626, Class0 Recall=0.5312
Fold 5: Macro-F1=0.6162, ROC-AUC=0.7786, PR-AUC=0.9651, Class0 Recall=0.6875

SMOTENC + Logistic Regression CV completed ✅
Total CV time: 0.7899 seconds

Mean ± Standard Deviation:
Macro-F1: 0.6096 ± 0.0279
ROC-AUC: 0.7738 ± 0.0344
PR-AUC: 0.9625 ± 0.0073
Class0 Recall: 0.5833 ± 0.0915

In [8]:
smotenc_rf_scores = {
    "Macro-F1": [],
    "ROC-AUC": [],
    "PR-AUC": [],
    "Class0 Recall": []
}

start_time = time.perf_counter()

for fold, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    X_fold_train = X.iloc[train_idx]
    X_fold_val = X.iloc[val_idx]

    y_fold_train = y.iloc[train_idx]
    y_fold_val = y.iloc[val_idx]

    # Fit pipeline ONLY on training fold
    smotenc_rf_cv_pipeline.fit(
        X_fold_train,
        y_fold_train
    )

    # Validation predictions
    y_fold_pred = smotenc_rf_cv_pipeline.predict(
        X_fold_val
    )

    y_fold_prob = smotenc_rf_cv_pipeline.predict_proba(
        X_fold_val
    )[:, 1]

    # Metrics
    macro_f1 = f1_score(
        y_fold_val,
        y_fold_pred,
        average="macro"
    )

    roc_auc = roc_auc_score(
        y_fold_val,
        y_fold_prob
    )

    pr_auc = average_precision_score(
        y_fold_val,
        y_fold_prob
    )

    class0_recall = recall_score(
        y_fold_val,
        y_fold_pred,
        pos_label=0
    )

    smotenc_rf_scores["Macro-F1"].append(macro_f1)
    smotenc_rf_scores["ROC-AUC"].append(roc_auc)
    smotenc_rf_scores["PR-AUC"].append(pr_auc)
    smotenc_rf_scores["Class0 Recall"].append(class0_recall)

    print(
        f"Fold {fold}: "
        f"Macro-F1={macro_f1:.4f}, "
        f"ROC-AUC={roc_auc:.4f}, "
        f"PR-AUC={pr_auc:.4f}, "
        f"Class0 Recall={class0_recall:.4f}"
    )

smotenc_rf_cv_time = time.perf_counter() - start_time

print("\nSMOTENC + Random Forest CV completed ✅")
print(f"Total CV time: {smotenc_rf_cv_time:.4f} seconds")

print("\nMean ± Standard Deviation:")

for metric, values in smotenc_rf_scores.items():
    print(
        f"{metric}: "
        f"{np.mean(values):.4f} ± {np.std(values):.4f}"
    )

Fold 1: Macro-F1=0.7005, ROC-AUC=0.8224, PR-AUC=0.9716, Class0 Recall=0.5152
Fold 2: Macro-F1=0.5868, ROC-AUC=0.7723, PR-AUC=0.9675, Class0 Recall=0.2500
Fold 3: Macro-F1=0.5772, ROC-AUC=0.6993, PR-AUC=0.9520, Class0 Recall=0.2812
Fold 4: Macro-F1=0.6024, ROC-AUC=0.7684, PR-AUC=0.9601, Class0 Recall=0.3125
Fold 5: Macro-F1=0.5836, ROC-AUC=0.7444, PR-AUC=0.9553, Class0 Recall=0.2188

SMOTENC + Random Forest CV completed ✅
Total CV time: 3.6793 seconds

Mean ± Standard Deviation:
Macro-F1: 0.6101 ± 0.0460
ROC-AUC: 0.7613 ± 0.0401
PR-AUC: 0.9613 ± 0.0073
Class0 Recall: 0.3155 ± 0.1046

In [9]:
from sklearn.model_selection import StratifiedKFold, cross_val_predict

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# OOF probabilities for Logistic Regression
lr_oof_proba = cross_val_predict(
    logistic_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

# OOF probabilities for Random Forest
rf_oof_proba = cross_val_predict(
    random_forest_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

print("LR OOF probabilities:", lr_oof_proba.shape)
print("RF OOF probabilities:", rf_oof_proba.shape)

print("\nLR probability range:",
      lr_oof_proba.min(), "to", lr_oof_proba.max())

print("RF probability range:",
      rf_oof_proba.min(), "to", rf_oof_proba.max())

NameError: name 'logistic_model' is not defined

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Logistic Regression
logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Random Forest
random_forest_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

print("Logistic Regression model created:", logistic_model)
print("\nRandom Forest model created:", random_forest_model)

NameError: name 'preprocessor' is not defined

In [11]:
print("X_train:", "exists" if "X_train" in globals() else "missing")
print("X_test:", "exists" if "X_test" in globals() else "missing")
print("y_train:", "exists" if "y_train" in globals() else "missing")
print("y_test:", "exists" if "y_test" in globals() else "missing")

print("logistic_model:", "exists" if "logistic_model" in globals() else "missing")
print("random_forest_model:", "exists" if "random_forest_model" in globals() else "missing")
print("preprocessor:", "exists" if "preprocessor" in globals() else "missing")

X_train: missing
X_test: missing
y_train: missing
y_test: missing
logistic_model: missing
random_forest_model: missing
preprocessor: missing

In [12]:
import pandas as pd

file_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"

df_ml = pd.read_csv(file_path)

print("Dataset shape:", df_ml.shape)
print("\nColumns:")
print(df_ml.columns.tolist())

print("\nTarget distribution:")
print(df_ml["Digital_Payment_Adoption"].value_counts())

Dataset shape: (1515, 14)

Columns:
['s7', 'a5a', 'a6', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'd3a', 'd3c', 'd7a', 'd7b', 'Digital_Payment_Adoption']

Target distribution:
Digital_Payment_Adoption
1    1354
0     161
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df_ml.drop(columns=["Digital_Payment_Adoption"])
y = df_ml["Digital_Payment_Adoption"]

# Same 80/20 stratified split used earlier
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTraining set:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print(y_train.value_counts())

print("\nTest set:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)
print(y_test.value_counts())

X shape: (1515, 13)
y shape: (1515,)

Training set:
X_train: (1212, 13)
y_train: (1212,)
Digital_Payment_Adoption
1    1083
0     129
Name: count, dtype: int64

Test set:
X_test: (303, 13)
y_test: (303,)
Digital_Payment_Adoption
1    271
0     32
Name: count, dtype: int64

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Numerical features
numerical_features = [
    "s7",
    "a6",
    "d3c"
]

# Categorical features
categorical_features = [
    "a5a",
    "b5a",
    "b5f",
    "b5g",
    "b5h",
    "b13b4",
    "b13b5",
    "d3a",
    "d7a",
    "d7b"
]

# Numerical preprocessing
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical preprocessing
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine both
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

print("Numerical features:", numerical_features)
print("Categorical features:", categorical_features)
print("Preprocessor created successfully.")

Numerical features: ['s7', 'a6', 'd3c']
Categorical features: ['a5a', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'd3a', 'd7a', 'd7b']
Preprocessor created successfully.

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Logistic Regression
logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Random Forest
random_forest_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

print("Logistic Regression pipeline: created")
print("Random Forest pipeline: created")

Logistic Regression pipeline: created
Random Forest pipeline: created

In [16]:
from sklearn.model_selection import StratifiedKFold, cross_val_predict

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# OOF probabilities — Logistic Regression
lr_oof_proba = cross_val_predict(
    logistic_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

# OOF probabilities — Random Forest
rf_oof_proba = cross_val_predict(
    random_forest_model,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

print("LR OOF shape:", lr_oof_proba.shape)
print("RF OOF shape:", rf_oof_proba.shape)

print("\nLR probability range:")
print(lr_oof_proba.min(), "to", lr_oof_proba.max())

print("\nRF probability range:")
print(rf_oof_proba.min(), "to", rf_oof_proba.max())

LR OOF shape: (1212,)
RF OOF shape: (1212,)

LR probability range:
0.0047752031973267795 to 0.9999995369066128

RF probability range:
0.016666666666666666 to 1.0

In [17]:
import numpy as np
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score
)

thresholds = np.arange(0.10, 0.91, 0.01)

results = []

for threshold in thresholds:

    # Logistic Regression
    lr_pred = (lr_oof_proba >= threshold).astype(int)

    lr_macro_f1 = f1_score(
        y_train,
        lr_pred,
        average="macro"
    )

    lr_class0_precision = precision_score(
        y_train,
        lr_pred,
        pos_label=0,
        zero_division=0
    )

    lr_class0_recall = recall_score(
        y_train,
        lr_pred,
        pos_label=0,
        zero_division=0
    )

    # Random Forest
    rf_pred = (rf_oof_proba >= threshold).astype(int)

    rf_macro_f1 = f1_score(
        y_train,
        rf_pred,
        average="macro"
    )

    rf_class0_precision = precision_score(
        y_train,
        rf_pred,
        pos_label=0,
        zero_division=0
    )

    rf_class0_recall = recall_score(
        y_train,
        rf_pred,
        pos_label=0,
        zero_division=0
    )

    results.append([
        threshold,
        lr_macro_f1,
        lr_class0_precision,
        lr_class0_recall,
        rf_macro_f1,
        rf_class0_precision,
        rf_class0_recall
    ])

threshold_results_oof = pd.DataFrame(
    results,
    columns=[
        "Threshold",
        "LR_Macro_F1",
        "LR_Class0_Precision",
        "LR_Class0_Recall",
        "RF_Macro_F1",
        "RF_Class0_Precision",
        "RF_Class0_Recall"
    ]
)

# Best threshold for each model
best_lr = threshold_results_oof.loc[
    threshold_results_oof["LR_Macro_F1"].idxmax()
]

best_rf = threshold_results_oof.loc[
    threshold_results_oof["RF_Macro_F1"].idxmax()
]

print("BEST LOGISTIC REGRESSION THRESHOLD")
print(best_lr)

print("\nBEST RANDOM FOREST THRESHOLD")
print(best_rf)

BEST LOGISTIC REGRESSION THRESHOLD
Threshold              0.360000
LR_Macro_F1            0.667269
LR_Class0_Precision    0.344340
LR_Class0_Recall       0.565891
RF_Macro_F1            0.621525
RF_Class0_Precision    0.441176
RF_Class0_Recall       0.232558
Name: 26, dtype: float64

BEST RANDOM FOREST THRESHOLD
Threshold              0.440000
LR_Macro_F1            0.633813
LR_Class0_Precision    0.283828
LR_Class0_Recall       0.666667
RF_Macro_F1            0.632976
RF_Class0_Precision    0.378641
RF_Class0_Recall       0.302326
Name: 34, dtype: float64

In [18]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

# Train models on the complete training set
logistic_model.fit(X_train, y_train)
random_forest_model.fit(X_train, y_train)

# Test probabilities
lr_test_proba = logistic_model.predict_proba(X_test)[:, 1]
rf_test_proba = random_forest_model.predict_proba(X_test)[:, 1]

# Frozen thresholds selected from OOF
lr_threshold = 0.36
rf_threshold = 0.44

# Threshold-based predictions
lr_test_pred = (lr_test_proba >= lr_threshold).astype(int)
rf_test_pred = (rf_test_proba >= rf_threshold).astype(int)

# Function for evaluation
def evaluate_model(name, y_true, y_pred, y_proba):
    print(f"\n{'='*50}")
    print(name)
    print(f"{'='*50}")

    print("Accuracy :", round(accuracy_score(y_true, y_pred), 4))
    print("Precision:", round(precision_score(y_true, y_pred), 4))
    print("Recall   :", round(recall_score(y_true, y_pred), 4))
    print("F1       :", round(f1_score(y_true, y_pred), 4))
    print("Macro-F1 :", round(f1_score(y_true, y_pred, average="macro"), 4))
    print("ROC-AUC  :", round(roc_auc_score(y_true, y_proba), 4))
    print("PR-AUC   :", round(average_precision_score(y_true, y_proba), 4))

    print("\nClass 0 Precision:",
          round(precision_score(
              y_true, y_pred,
              pos_label=0,
              zero_division=0
          ), 4))

    print("Class 0 Recall   :",
          round(recall_score(
              y_true, y_pred,
              pos_label=0,
              zero_division=0
          ), 4))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))


evaluate_model(
    "LOGISTIC REGRESSION — THRESHOLD 0.36",
    y_test,
    lr_test_pred,
    lr_test_proba
)

evaluate_model(
    "RANDOM FOREST — THRESHOLD 0.44",
    y_test,
    rf_test_pred,
    rf_test_proba
)

==================================================
LOGISTIC REGRESSION — THRESHOLD 0.36
==================================================
Accuracy : 0.8416
Precision: 0.9478
Recall   : 0.8708
F1       : 0.9077
Macro-F1 : 0.6748
ROC-AUC  : 0.8637
PR-AUC   : 0.9821

Class 0 Precision: 0.3519
Class 0 Recall   : 0.5938

Confusion Matrix:
[[ 19  13]
 [ 35 236]]

==================================================
RANDOM FOREST — THRESHOLD 0.44
==================================================
Accuracy : 0.8878
Precision: 0.9247
Recall   : 0.952
F1       : 0.9382
Macro-F1 : 0.6655
ROC-AUC  : 0.8522
PR-AUC   : 0.9802

Class 0 Precision: 0.4583
Class 0 Recall   : 0.3438

Confusion Matrix:
[[ 11  21]
 [ 13 258]]

In [19]:
final_results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Threshold": 0.36,
        "Accuracy": accuracy_score(y_test, lr_test_pred),
        "Precision": precision_score(y_test, lr_test_pred),
        "Recall": recall_score(y_test, lr_test_pred),
        "F1": f1_score(y_test, lr_test_pred),
        "Macro_F1": f1_score(y_test, lr_test_pred, average="macro"),
        "ROC_AUC": roc_auc_score(y_test, lr_test_proba),
        "PR_AUC": average_precision_score(y_test, lr_test_proba),
        "Class0_Precision": precision_score(
            y_test, lr_test_pred, pos_label=0, zero_division=0
        ),
        "Class0_Recall": recall_score(
            y_test, lr_test_pred, pos_label=0, zero_division=0
        )
    },
    {
        "Model": "Random Forest",
        "Threshold": 0.44,
        "Accuracy": accuracy_score(y_test, rf_test_pred),
        "Precision": precision_score(y_test, rf_test_pred),
        "Recall": recall_score(y_test, rf_test_pred),
        "F1": f1_score(y_test, rf_test_pred),
        "Macro_F1": f1_score(y_test, rf_test_pred, average="macro"),
        "ROC_AUC": roc_auc_score(y_test, rf_test_proba),
        "PR_AUC": average_precision_score(y_test, rf_test_proba),
        "Class0_Precision": precision_score(
            y_test, rf_test_pred, pos_label=0, zero_division=0
        ),
        "Class0_Recall": recall_score(
            y_test, rf_test_pred, pos_label=0, zero_division=0
        )
    }
])

output_path = r"E:\Pep_Projectdetails\selected_dataset\final_model_results.csv"

final_results.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path)

print("\nFinal results:")
display(final_results.round(4))

Saved successfully:
E:\Pep_Projectdetails\selected_dataset\final_model_results.csv

Final results:

,Model,Threshold,Accuracy,Precision,Recall,F1,Macro_F1,ROC_AUC,PR_AUC,Class0_Precision,Class0_Recall
0,Logistic Regression,0.36,0.8416,0.9478,0.8708,0.9077,0.6748,0.8637,0.9821,0.3519,0.5938
1,Random Forest,0.44,0.8878,0.9247,0.9520,0.9382,0.6655,0.8522,0.9802,0.4583,0.3438

In [20]:
import joblib

# Save the final Logistic Regression pipeline
model_path = r"E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib"

joblib.dump(logistic_model, model_path)

print("Model saved successfully:")
print(model_path)

Model saved successfully:
E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib

In [21]:
import json

threshold_path = r"E:\Pep_Projectdetails\selected_dataset\final_model_threshold.json"

final_config = {
    "model": "Logistic Regression",
    "target": "Digital_Payment_Adoption",
    "threshold": 0.36
}

with open(threshold_path, "w") as f:
    json.dump(final_config, f, indent=4)

print("Threshold configuration saved successfully:")
print(threshold_path)

print("\nConfiguration:")
print(final_config)

Threshold configuration saved successfully:
E:\Pep_Projectdetails\selected_dataset\final_model_threshold.json

Configuration:
{'model': 'Logistic Regression', 'target': 'Digital_Payment_Adoption', 'threshold': 0.36}

In [22]:
# Inspect the first technology-adoption obstacle variable

print("d8a value counts:")
print(df_ml["d8a"].value_counts(dropna=False).sort_index())

print("\nNumber of unique values:")
print(df_ml["d8a"].nunique(dropna=True))

print("\nMissing values:")
print(df_ml["d8a"].isna().sum())

d8a value counts:

KeyError: 'd8a'

In [23]:
import pandas as pd

working_path = r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"

df_policy = pd.read_csv(working_path)

print("Shape:", df_policy.shape)
print("d8a exists:", "d8a" in df_policy.columns)

Shape: (1519, 837)
d8a exists: True

In [24]:
print("d8a value counts:")
print(df_policy["d8a"].value_counts(dropna=False).sort_index())

d8a value counts:
d8a
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
Don't know                                                          11
Electricity, water, or Internet connection are too expensive         4
It is difficult or costly to comply with government regulations     29
Lack of information                                                282
Lack of knowledge on acquiring                                      19
Lack of technical skills                                           248
Other                                                                9
Too costly or not convinced of the economic benefit                333
Uncertainty of demand                                              464
Name: count, dtype: int64

In [25]:
# Compare adoption status with the main technology barriers

policy_check = df_policy[[
    "d8a"
]].copy()

print("Total firms:", len(policy_check))
print("\nBarrier distribution:")
print(policy_check["d8a"].value_counts())

Total firms: 1519

Barrier distribution:
d8a
Uncertainty of demand                                              464
Too costly or not convinced of the economic benefit                333
Lack of information                                                282
Lack of technical skills                                           248
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
It is difficult or costly to comply with government regulations     29
Lack of knowledge on acquiring                                      19
Don't know                                                          11
Other                                                                9
Electricity, water, or Internet connection are too expensive         4
Name: count, dtype: int64

In [26]:
# Load the ML target
df_target = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"
)

# Combine adoption status with policy/barrier data
df_analysis = df_policy[["d8a", "d7a", "d7b", "d3a", "d3c"]].copy()

df_analysis["Digital_Payment_Adoption"] = df_target[
    "Digital_Payment_Adoption"
].values

print("Shape:", df_analysis.shape)

print("\nAdoption distribution:")
print(df_analysis["Digital_Payment_Adoption"].value_counts())

print("\nNon-adopting SMEs:")
print(
    df_analysis[df_analysis["Digital_Payment_Adoption"] == 0]["d8a"]
    .value_counts()
)

ValueError: Length of values (1515) does not match length of index (1519)

In [27]:
print("df_policy ID columns:")
print([col for col in df_policy.columns if "id" in col.lower()][:10])

print("\nTarget dataset ID columns:")
print([col for col in df_target.columns if "id" in col.lower()][:10])

df_policy ID columns:
['firm_id', 'firmid']

Target dataset ID columns:
[]

In [28]:
print("firm_id sample:")
print(df_policy["firm_id"].head())

print("\nfirmid sample:")
print(df_policy["firmid"].head())

print("\nAre firm_id values unique?")
print(df_policy["firm_id"].is_unique)

print("\nAre firmid values unique?")
print(df_policy["firmid"].is_unique)

firm_id sample:
0    2000030
1    2000031
2    2000110
3    2000515
4    2000768
Name: firm_id, dtype: int64

firmid sample:
0    500001
1    500002
2    500003
3    500004
4    500005
Name: firmid, dtype: int64

Are firm_id values unique?
True

Are firmid values unique?
True

In [29]:
# Recreate the Digital Payment Adoption target from the original dataset

payment_cols = ["b14a4", "b14a5", "b14a6"]

# Convert -9 to missing for the payment variables
payment_data = df_policy[payment_cols].replace(-9, pd.NA)

# Keep only firms with valid information for all 3 payment variables
valid_payment = payment_data.notna().all(axis=1)

# Create the same target used in the ML dataset
df_policy["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1)
).astype(int)

# Set target to missing where payment information was incomplete
df_policy.loc[~valid_payment, "Digital_Payment_Adoption"] = pd.NA

print("Total firms:", len(df_policy))
print("Valid target firms:", df_policy["Digital_Payment_Adoption"].notna().sum())
print("\nTarget distribution:")
print(df_policy["Digital_Payment_Adoption"].value_counts(dropna=False))

Total firms: 1519
Valid target firms: 1515

Target distribution:
Digital_Payment_Adoption
1.0    1354
0.0     161
NaN       4
Name: count, dtype: int64

C:\Users\Krishna\AppData\Local\Temp\ipykernel_20060\2414654762.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_policy["Digital_Payment_Adoption"] = (

In [30]:
# Select valid non-adopting SMEs
non_adopters = df_policy[
    df_policy["Digital_Payment_Adoption"] == 0
].copy()

print("Number of non-adopting SMEs:", len(non_adopters))

print("\nMain barriers among non-adopting SMEs:")
print(
    non_adopters["d8a"]
    .value_counts()
)

Number of non-adopting SMEs: 161

Main barriers among non-adopting SMEs:
d8a
Uncertainty of demand                                              48
Lack of information                                                42
Too costly or not convinced of the economic benefit                28
Lack of technical skills                                           26
Difficulty in obtaining financing                                   8
Consumer preferences do not value quality of products               5
Lack of knowledge on acquiring                                      1
It is difficult or costly to comply with government regulations     1
Don't know                                                          1
Other                                                               1
Name: count, dtype: int64

In [31]:
print("d7a — Government support awareness")
print(
    df_policy.groupby("d7a", dropna=False)["Digital_Payment_Adoption"]
    .agg(["count", "mean"])
)

d7a — Government support awareness
     count      mean
d7a
1     1139  0.889377
2      376  0.906915

In [32]:
print(df_policy["d7a"].value_counts(dropna=False))

d7a
1    1140
2     379
Name: count, dtype: int64

In [33]:
print("d7a dtype:", df_policy["d7a"].dtype)
print("d7a unique values:", df_policy["d7a"].unique())

d7a dtype: int64
d7a unique values: [1 2]

In [34]:
print("d7b value counts:")
print(df_policy["d7b"].value_counts(dropna=False).sort_index())

d7b value counts:
d7b
-9      23
 1     436
 2    1060
Name: count, dtype: int64

In [35]:
print(df_policy["d7b"].describe())
print("\nUnique values:")
print(sorted(df_policy["d7b"].dropna().unique()))

count    1519.000000
mean        1.546412
std         1.383718
min        -9.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         2.000000
Name: d7b, dtype: float64

Unique values:
[np.int64(-9), np.int64(1), np.int64(2)]

In [36]:
# Clean d7b for policy analysis
policy_d7b = df_policy.copy()

policy_d7b["d7b_clean"] = policy_d7b["d7b"].replace(-9, pd.NA)

print(
    policy_d7b.groupby("d7b_clean")["Digital_Payment_Adoption"]
    .agg(["count", "mean"])
)

           count      mean
d7b_clean
1            436  0.894495
2           1057  0.891202

In [37]:
# Non-adopters who already benefited from government support

supported_non_adopters = df_policy[
    (df_policy["Digital_Payment_Adoption"] == 0) &
    (df_policy["d7b"] == 1)
].copy()

print("Non-adopters who benefited from government support:",
      len(supported_non_adopters))

print("\nTheir main barriers:")
print(
    supported_non_adopters["d8a"]
    .value_counts()
)

Non-adopters who benefited from government support: 46

Their main barriers:
d8a
Lack of information                                      26
Uncertainty of demand                                     6
Lack of technical skills                                  5
Consumer preferences do not value quality of products     3
Too costly or not convinced of the economic benefit       3
Difficulty in obtaining financing                         2
Other                                                     1
Name: count, dtype: int64

In [38]:
import pandas as pd
import joblib

# 1. Load the saved final model
model_path = r"E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib"
final_model = joblib.load(model_path)

# 2. Use the same ML dataset used during training
df_ml = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"
)

# 3. Separate features
X_all = df_ml.drop(columns=["Digital_Payment_Adoption"])

# 4. Get probability of class 0 = Non-Adoption
non_adoption_probability = final_model.predict_proba(X_all)[:, 0]

# 5. Create ranking
risk_ranking = df_ml.copy()

risk_ranking["Non_Adoption_Probability"] = non_adoption_probability

# Highest risk first
risk_ranking = risk_ranking.sort_values(
    "Non_Adoption_Probability",
    ascending=False
).reset_index(drop=True)

# 6. Add risk rank
risk_ranking["Non_Adoption_Risk_Rank"] = (
    risk_ranking.index + 1
)

# 7. Display top 20 highest-risk firms
risk_ranking[
    [
        "Non_Adoption_Risk_Rank",
        "Non_Adoption_Probability",
        "Digital_Payment_Adoption"
    ]
].head(20)

    Non_Adoption_Risk_Rank  Non_Adoption_Probability  Digital_Payment_Adoption
0                        1                  0.992902                         0
1                        2                  0.982395                         0
2                        3                  0.978209                         0
3                        4                  0.975556                         0
4                        5                  0.975232                         1
5                        6                  0.975120                         0
6                        7                  0.971916                         0
7                        8                  0.970503                         1
8                        9                  0.968223                         0
9                       10                  0.968034                         1
10                      11                  0.965417                         0
11                      12                  0.963871                         1
12                      13                  0.963557                         1
13                      14                  0.962639                         0
14                      15                  0.957888                         0
15                      16                  0.954252                         1
16                      17                  0.953192                         1
17                      18                  0.948398                         1
18                      19                  0.945439                         1
19                      20                  0.944965                         0

In [39]:
import pandas as pd
import numpy as np

# Work only with firms having a valid digital-payment adoption label
barrier_df = df_policy[
    df_policy["Digital_Payment_Adoption"].notna()
].copy()

# Clean barrier variable
barrier_df["d8a_clean"] = barrier_df["d8a"].replace(
    [-9, "-9"],
    pd.NA
)

# Remove firms with no reported barrier
barrier_df = barrier_df[
    barrier_df["d8a_clean"].notna()
].copy()

# Total number in each adoption group
n_non = (barrier_df["Digital_Payment_Adoption"] == 0).sum()
n_adopt = (barrier_df["Digital_Payment_Adoption"] == 1).sum()

results = []

for barrier in barrier_df["d8a_clean"].unique():

    # Counts
    non_count = (
        (barrier_df["Digital_Payment_Adoption"] == 0) &
        (barrier_df["d8a_clean"] == barrier)
    ).sum()

    adopt_count = (
        (barrier_df["Digital_Payment_Adoption"] == 1) &
        (barrier_df["d8a_clean"] == barrier)
    ).sum()

    # Proportions
    non_prop = non_count / n_non
    adopt_prop = adopt_count / n_adopt

    # Difference in proportions
    difference = non_prop - adopt_prop

    # Approximate 95% CI for difference
    se = np.sqrt(
        (non_prop * (1 - non_prop) / n_non) +
        (adopt_prop * (1 - adopt_prop) / n_adopt)
    )

    ci_low = difference - 1.96 * se
    ci_high = difference + 1.96 * se

    results.append({
        "Barrier": barrier,
        "Non_Adopters_n": non_count,
        "Non_Adopters_%": non_prop * 100,
        "Adopters_n": adopt_count,
        "Adopters_%": adopt_prop * 100,
        "Difference_pp": difference * 100,
        "CI_95_Lower_pp": ci_low * 100,
        "CI_95_Upper_pp": ci_high * 100
    })

barrier_comparison = pd.DataFrame(results)

# Show barriers where they are most common among non-adopters
barrier_comparison = barrier_comparison.sort_values(
    "Difference_pp",
    ascending=False
).reset_index(drop=True)

pd.set_option("display.max_colwidth", 100)

barrier_comparison

,Barrier,Non_Adopters_n,Non_Adopters_%,Adopters_n,Adopters_%,Difference_pp,CI_95_Lower_pp,CI_95_Upper_pp
0,Lack of information,42,26.086957,239,17.651403,8.435553,1.355170,15.515936
1,Difficulty in obtaining financing,8,4.968944,48,3.545052,1.423892,-2.074300,4.922085
2,Other,1,0.621118,8,0.590842,0.030276,-1.250146,1.310698
3,Don't know,1,0.621118,9,0.664697,-0.043579,-1.332056,1.244898
4,Lack of technical skills,26,16.149068,221,16.322009,-0.172941,-6.188371,5.842490
5,"Electricity, water, or Internet connection are too expensive",0,0.000000,4,0.295421,-0.295421,-0.584506,-0.006336
6,Lack of knowledge on acquiring,1,0.621118,18,1.329394,-0.708276,-2.066585,0.650032
7,Uncertainty of demand,48,29.813665,416,30.723781,-0.910117,-8.391292,6.571058
8,Consumer preferences do not value quality of products,5,3.105590,59,4.357459,-1.251869,-4.143670,1.639932
9,It is difficult or costly to comply with government regulations,1,0.621118,27,1.994092,-1.372974,-2.796814,0.050867
10,Too costly or not convinced of the economic benefit,28,17.391304,305,22.525849,-5.134545,-11.398067,1.128977

In [40]:
# Work only with actual digital-payment non-adopters
non_adopter_policy = df_policy[
    df_policy["Digital_Payment_Adoption"] == 0
].copy()

# Treat -9 in d7b as missing/unknown
non_adopter_policy["d7b_clean"] = non_adopter_policy["d7b"].replace(
    -9, pd.NA
)

# Create readable support groups
non_adopter_policy["Support_Group"] = "Unknown"

non_adopter_policy.loc[
    (non_adopter_policy["d7b_clean"] == 1),
    "Support_Group"
] = "Benefited from government support"

non_adopter_policy.loc[
    (non_adopter_policy["d7b_clean"] == 2),
    "Support_Group"
] = "Did not benefit from government support"

# Count firms in each group
support_summary = (
    non_adopter_policy["Support_Group"]
    .value_counts()
    .rename_axis("Support_Group")
    .reset_index(name="Number_of_Non_Adopters")
)

print("Non-adopters by government-support status:")
display(support_summary)

# Barrier distribution within each support group
barrier_by_support = pd.crosstab(
    non_adopter_policy["d8a"],
    non_adopter_policy["Support_Group"]
)

# Convert counts to percentages within each group
barrier_by_support_pct = (
    barrier_by_support
    .div(barrier_by_support.sum(axis=0), axis=1)
    * 100
).round(2)

print("\nBarrier percentage within each government-support group:")
display(barrier_by_support_pct)

Non-adopters by government-support status:

                             Support_Group  Number_of_Non_Adopters
0  Did not benefit from government support                     115
1        Benefited from government support                      46

Barrier percentage within each government-support group:

Support_Group,Benefited from government support,Did not benefit from government support
d8a,,
Consumer preferences do not value quality of products,6.52,1.74
Difficulty in obtaining financing,4.35,5.22
Don't know,0.00,0.87
It is difficult or costly to comply with government regulations,0.00,0.87
Lack of information,56.52,13.91
Lack of knowledge on acquiring,0.00,0.87
Lack of technical skills,10.87,18.26
Other,2.17,0.00
Too costly or not convinced of the economic benefit,6.52,21.74
Uncertainty of demand,13.04,36.52

In [41]:
# ============================================
# d7a AWARENESS ANALYSIS — NON-ADOPTERS
# ============================================

# Work only with actual digital-payment non-adopters
non_adopter_awareness = df_policy[
    df_policy["Digital_Payment_Adoption"] == 0
].copy()

# Create readable awareness groups
# d7a:
# 1 = Yes, aware of government support/subsidy
# 2 = No, not aware
non_adopter_awareness["Awareness_Group"] = (
    non_adopter_awareness["d7a"]
    .map({
        1: "Aware of government support",
        2: "Not aware of government support"
    })
    .fillna("Unknown")
)

# --------------------------------------------
# 1. Count and percentage of each group
# --------------------------------------------

awareness_summary = (
    non_adopter_awareness["Awareness_Group"]
    .value_counts(dropna=False)
    .rename_axis("Awareness_Group")
    .reset_index(name="Number_of_Non_Adopters")
)

awareness_summary["Percentage"] = (
    awareness_summary["Number_of_Non_Adopters"]
    / len(non_adopter_awareness)
    * 100
).round(2)

print("Non-adopters by government-support awareness:")
display(awareness_summary)


# --------------------------------------------
# 2. Barrier distribution by awareness group
# --------------------------------------------

barrier_by_awareness = pd.crosstab(
    non_adopter_awareness["d8a"],
    non_adopter_awareness["Awareness_Group"]
)

# Convert counts into percentages within each awareness group
barrier_by_awareness_pct = (
    barrier_by_awareness
    .div(barrier_by_awareness.sum(axis=0), axis=1)
    * 100
).round(2)

print("\nBarrier percentage within each awareness group:")
display(barrier_by_awareness_pct)


# --------------------------------------------
# 3. Combine awareness + benefited status
# --------------------------------------------

non_adopter_awareness["Benefit_Group"] = (
    non_adopter_awareness["d7b"]
    .replace(-9, pd.NA)
    .map({
        1: "Benefited",
        2: "Did not benefit"
    })
    .fillna("Unknown")
)

non_adopter_awareness["Awareness_Benefit_Group"] = (
    non_adopter_awareness["Awareness_Group"]
    + " + "
    + non_adopter_awareness["Benefit_Group"]
)

print("\nCombined awareness + benefit groups:")
display(
    non_adopter_awareness["Awareness_Benefit_Group"]
    .value_counts()
    .rename_axis("Group")
    .reset_index(name="Number_of_Non_Adopters")
)

Non-adopters by government-support awareness:

                   Awareness_Group  Number_of_Non_Adopters  Percentage
0      Aware of government support                     126       78.26
1  Not aware of government support                      35       21.74

Barrier percentage within each awareness group:

Awareness_Group,Aware of government support,Not aware of government support
d8a,,
Consumer preferences do not value quality of products,3.17,2.86
Difficulty in obtaining financing,3.97,8.57
Don't know,0.00,2.86
It is difficult or costly to comply with government regulations,0.00,2.86
Lack of information,30.95,8.57
Lack of knowledge on acquiring,0.00,2.86
Lack of technical skills,15.08,20.00
Other,0.79,0.00
Too costly or not convinced of the economic benefit,18.25,14.29
Uncertainty of demand,27.78,37.14

Combined awareness + benefit groups:

                                               Group  Number_of_Non_Adopters
0      Aware of government support + Did not benefit                      80
1            Aware of government support + Benefited                      46
2  Not aware of government support + Did not benefit                      35

In [42]:
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

# ============================================================
# BOOTSTRAP 95% CI FOR NON-ADOPTER (CLASS 0) METRICS
# Final Logistic Regression, threshold = 0.36
# ============================================================

# Recreate the same test split
from sklearn.model_selection import train_test_split

df_ml = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"
)

X = df_ml.drop(columns=["Digital_Payment_Adoption"])
y = df_ml["Digital_Payment_Adoption"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Load the already-saved final model
import joblib

final_model = joblib.load(
    r"E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib"
)

# Get probabilities of NON-ADOPTION (class 0)
non_adoption_probability = final_model.predict_proba(X_test)[:, 0]

# Final selected threshold
threshold = 0.36

# Prediction:
# probability >= 0.36 -> non-adopter (class 0)
y_pred_non_adopter = (
    non_adoption_probability >= threshold
).astype(int)

# Convert back to normal class labels:
# 1 = adopter
# 0 = non-adopter
y_pred = 1 - y_pred_non_adopter

# Actual labels
y_test_array = y_test.to_numpy()


# ============================================================
# Original point estimates
# ============================================================

class0_precision = precision_score(
    y_test_array,
    y_pred,
    pos_label=0,
    zero_division=0
)

class0_recall = recall_score(
    y_test_array,
    y_pred,
    pos_label=0,
    zero_division=0
)

class0_f1 = f1_score(
    y_test_array,
    y_pred,
    pos_label=0,
    zero_division=0
)


# ============================================================
# Bootstrap
# ============================================================

rng = np.random.default_rng(42)

n_bootstrap = 10000

bootstrap_precision = []
bootstrap_recall = []
bootstrap_f1 = []

n_test = len(y_test_array)

for _ in range(n_bootstrap):

    # Sample test observations with replacement
    indices = rng.integers(
        0,
        n_test,
        size=n_test
    )

    y_true_sample = y_test_array[indices]
    y_pred_sample = y_pred[indices]

    # Skip samples where class 0 is absent
    if np.sum(y_true_sample == 0) == 0:
        continue

    bootstrap_precision.append(
        precision_score(
            y_true_sample,
            y_pred_sample,
            pos_label=0,
            zero_division=0
        )
    )

    bootstrap_recall.append(
        recall_score(
            y_true_sample,
            y_pred_sample,
            pos_label=0,
            zero_division=0
        )
    )

    bootstrap_f1.append(
        f1_score(
            y_true_sample,
            y_pred_sample,
            pos_label=0,
            zero_division=0
        )
    )


# ============================================================
# Calculate 95% confidence intervals
# ============================================================

def bootstrap_ci(values):
    return (
        np.percentile(values, 2.5),
        np.percentile(values, 97.5)
    )


precision_ci = bootstrap_ci(bootstrap_precision)
recall_ci = bootstrap_ci(bootstrap_recall)
f1_ci = bootstrap_ci(bootstrap_f1)


# ============================================================
# Final results table
# ============================================================

bootstrap_results = pd.DataFrame({
    "Metric": [
        "Class-0 Precision",
        "Class-0 Recall",
        "Class-0 F1"
    ],
    "Point_Estimate": [
        class0_precision,
        class0_recall,
        class0_f1
    ],
    "CI_95_Lower": [
        precision_ci[0],
        recall_ci[0],
        f1_ci[0]
    ],
    "CI_95_Upper": [
        precision_ci[1],
        recall_ci[1],
        f1_ci[1]
    ]
})

bootstrap_results[
    ["Point_Estimate", "CI_95_Lower", "CI_95_Upper"]
] = (
    bootstrap_results[
        ["Point_Estimate", "CI_95_Lower", "CI_95_Upper"]
    ] * 100
).round(2)

print("Test set size:", n_test)
print("Actual non-adopters in test set:", np.sum(y_test_array == 0))
print("Predicted non-adopters:", np.sum(y_pred == 0))
print("\nBootstrap results:")
display(bootstrap_results)

Test set size: 303
Actual non-adopters in test set: 32
Predicted non-adopters: 135

Bootstrap results:

              Metric  Point_Estimate  CI_95_Lower  CI_95_Upper
0  Class-0 Precision           22.22        15.27        29.50
1     Class-0 Recall           93.75        84.21       100.00
2         Class-0 F1           35.93        26.19        45.05

In [43]:
print("Model classes:", final_model.classes_)
print("Probability shape:", final_model.predict_proba(X_test).shape)

Model classes: [0 1]
Probability shape: (303, 2)

In [44]:
# Reproduce the frozen final model evaluation exactly

adoption_probability = final_model.predict_proba(X_test)[:, 1]

threshold = 0.36

y_pred = (adoption_probability >= threshold).astype(int)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Confusion Matrix:
[[ 19  13]
 [ 35 236]]

Classification Report:

NameError: name 'classification_report' is not defined

In [45]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# Original test predictions are already correct
# y_test and y_pred are from the previous cell

y_test_np = np.asarray(y_test)
y_pred_np = np.asarray(y_pred)

rng = np.random.default_rng(42)
n_bootstrap = 5000

class0_precision = []
class0_recall = []
class0_f1 = []

for _ in range(n_bootstrap):
    # Resample test observations with replacement
    indices = rng.integers(0, len(y_test_np), len(y_test_np))

    y_true_b = y_test_np[indices]
    y_pred_b = y_pred_np[indices]

    # zero_division=0 prevents errors in rare bootstrap samples
    class0_precision.append(
        precision_score(
            y_true_b,
            y_pred_b,
            pos_label=0,
            zero_division=0
        )
    )

    class0_recall.append(
        recall_score(
            y_true_b,
            y_pred_b,
            pos_label=0,
            zero_division=0
        )
    )

    class0_f1.append(
        f1_score(
            y_true_b,
            y_pred_b,
            pos_label=0,
            zero_division=0
        )
    )


def bootstrap_ci(values):
    lower = np.percentile(values, 2.5)
    upper = np.percentile(values, 97.5)
    return lower, upper


p_low, p_high = bootstrap_ci(class0_precision)
r_low, r_high = bootstrap_ci(class0_recall)
f_low, f_high = bootstrap_ci(class0_f1)

print("CLASS 0 — NON-ADOPTION")

print(f"\nPrecision : {precision_score(y_test_np, y_pred_np, pos_label=0):.4f}")
print(f"95% CI    : [{p_low:.4f}, {p_high:.4f}]")

print(f"\nRecall    : {recall_score(y_test_np, y_pred_np, pos_label=0):.4f}")
print(f"95% CI    : [{r_low:.4f}, {r_high:.4f}]")

print(f"\nF1-score  : {f1_score(y_test_np, y_pred_np, pos_label=0):.4f}")
print(f"95% CI    : [{f_low:.4f}, {f_high:.4f}]")

CLASS 0 — NON-ADOPTION

Precision : 0.3519
95% CI    : [0.2222, 0.4898]

Recall    : 0.5938
95% CI    : [0.4242, 0.7587]

F1-score  : 0.4419
95% CI    : [0.3014, 0.5714]

In [46]:
import pandas as pd

bootstrap_results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Target_Class": "Non-Adoption (Class 0)",
        "Threshold": 0.36,
        "Metric": "Precision",
        "Value": 0.3519,
        "CI_Lower_95": 0.2222,
        "CI_Upper_95": 0.4898
    },
    {
        "Model": "Logistic Regression",
        "Target_Class": "Non-Adoption (Class 0)",
        "Threshold": 0.36,
        "Metric": "Recall",
        "Value": 0.5938,
        "CI_Lower_95": 0.4242,
        "CI_Upper_95": 0.7587
    },
    {
        "Model": "Logistic Regression",
        "Target_Class": "Non-Adoption (Class 0)",
        "Threshold": 0.36,
        "Metric": "F1-score",
        "Value": 0.4419,
        "CI_Lower_95": 0.3014,
        "CI_Upper_95": 0.5714
    }
])

output_path = r"E:\Pep_Projectdetails\selected_dataset\bootstrap_class0_results.csv"

bootstrap_results.to_csv(output_path, index=False)

print("Saved successfully!")
print(output_path)
print("\nSaved results:")
display(bootstrap_results)

Saved successfully!
E:\Pep_Projectdetails\selected_dataset\bootstrap_class0_results.csv

Saved results:

,Model,Target_Class,Threshold,Metric,Value,CI_Lower_95,CI_Upper_95
0,Logistic Regression,Non-Adoption (Class 0),0.36,Precision,0.3519,0.2222,0.4898
1,Logistic Regression,Non-Adoption (Class 0),0.36,Recall,0.5938,0.4242,0.7587
2,Logistic Regression,Non-Adoption (Class 0),0.36,F1-score,0.4419,0.3014,0.5714

In [47]:
import pandas as pd
import numpy as np

# Use the already verified test-set predictions
risk_test = pd.DataFrame({
    "Actual": y_test_np,
    "Adoption_Probability": adoption_probability
})

# Non-adoption probability
risk_test["Non_Adoption_Probability"] = 1 - risk_test["Adoption_Probability"]

# Sort highest-risk firms first
risk_test = risk_test.sort_values(
    "Non_Adoption_Probability",
    ascending=False
).reset_index(drop=True)

n = len(risk_test)

# Overall non-adoption rate
overall_non_adoption_rate = (risk_test["Actual"] == 0).mean()

print("Overall non-adoption rate:",
      f"{overall_non_adoption_rate:.4f}",
      f"({overall_non_adoption_rate*100:.2f}%)")

print("\n--- TOP 10% ---")

top10_n = int(np.ceil(n * 0.10))
top10 = risk_test.head(top10_n)

top10_non_adopters = (top10["Actual"] == 0).sum()
top10_rate = top10_non_adopters / len(top10)
top10_lift = top10_rate / overall_non_adoption_rate

print("Firms:", len(top10))
print("Actual non-adopters:", top10_non_adopters)
print("Non-adoption rate:", f"{top10_rate:.4f} ({top10_rate*100:.2f}%)")
print("Lift:", f"{top10_lift:.2f}x")

print("\n--- TOP 20% ---")

top20_n = int(np.ceil(n * 0.20))
top20 = risk_test.head(top20_n)

top20_non_adopters = (top20["Actual"] == 0).sum()
top20_rate = top20_non_adopters / len(top20)
top20_lift = top20_rate / overall_non_adoption_rate

print("Firms:", len(top20))
print("Actual non-adopters:", top20_non_adopters)
print("Non-adoption rate:", f"{top20_rate:.4f} ({top20_rate*100:.2f}%)")
print("Lift:", f"{top20_lift:.2f}x")

Overall non-adoption rate: 0.1056 (10.56%)

--- TOP 10% ---
Firms: 31
Actual non-adopters: 15
Non-adoption rate: 0.4839 (48.39%)
Lift: 4.58x

--- TOP 20% ---
Firms: 61
Actual non-adopters: 21
Non-adoption rate: 0.3443 (34.43%)
Lift: 3.26x

In [48]:
lift_results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Threshold": 0.36,
        "Group": "Overall Test Set",
        "Screened_Firms": 303,
        "Actual_Non_Adopters": 32,
        "Non_Adoption_Rate": 0.1056,
        "Lift": 1.00
    },
    {
        "Model": "Logistic Regression",
        "Threshold": 0.36,
        "Group": "Top 10% Highest Risk",
        "Screened_Firms": 31,
        "Actual_Non_Adopters": 15,
        "Non_Adoption_Rate": 0.4839,
        "Lift": 4.58
    },
    {
        "Model": "Logistic Regression",
        "Threshold": 0.36,
        "Group": "Top 20% Highest Risk",
        "Screened_Firms": 61,
        "Actual_Non_Adopters": 21,
        "Non_Adoption_Rate": 0.3443,
        "Lift": 3.26
    }
])

lift_path = r"E:\Pep_Projectdetails\selected_dataset\lift_results.csv"

lift_results.to_csv(lift_path, index=False)

print("Saved successfully!")
print(lift_path)

display(lift_results)

Saved successfully!
E:\Pep_Projectdetails\selected_dataset\lift_results.csv

,Model,Threshold,Group,Screened_Firms,Actual_Non_Adopters,Non_Adoption_Rate,Lift
0,Logistic Regression,0.36,Overall Test Set,303,32,0.1056,1.00
1,Logistic Regression,0.36,Top 10% Highest Risk,31,15,0.4839,4.58
2,Logistic Regression,0.36,Top 20% Highest Risk,61,21,0.3443,3.26

In [49]:
import pandas as pd
import numpy as np

# Load the FAT India working dataset
df_barrier = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"
)

print("Dataset shape:", df_barrier.shape)

# Show the variables needed for the controlled analysis
required_cols = [
    "firm_id",
    "firmid",
    "s7",       # Number of employees
    "a5a",      # Sector
    "d8a",      # First obstacle to technology adoption
    "b14a4",    # Payment - Cards
    "b14a5",    # Payment - Online/electronic
    "b14a6"     # Payment - Online platforms
]

available_cols = [c for c in required_cols if c in df_barrier.columns]

print("\nAvailable required columns:")
print(available_cols)

print("\nMissing required columns:")
print([c for c in required_cols if c not in df_barrier.columns])

Dataset shape: (1519, 837)

Available required columns:
['firm_id', 'firmid', 's7', 'a5a', 'd8a', 'b14a4', 'b14a5', 'b14a6']

Missing required columns:
[]

In [50]:
# Find columns that may represent state/location

state_candidates = [
    col for col in df_barrier.columns
    if any(word in col.lower() for word in [
        "state", "province", "location", "region"
    ])
]

print("Possible state/location columns:")
print(state_candidates)

Possible state/location columns:
[]

In [52]:
# Check the official state variable

print("s2e data type:")
print(df_barrier["s2e"].dtype)

print("\nState values and counts:")
print(df_barrier["s2e"].value_counts(dropna=False))

print("\nNumber of unique states:")
print(df_barrier["s2e"].nunique())

s2e data type:
str

State values and counts:
s2e
Tamil Nadu       766
Uttar Pradesh    753
Name: count, dtype: int64

Number of unique states:
2

In [53]:
# Create controlled barrier-analysis variables

analysis = df_barrier.copy()

# --------------------------------------------------
# 1. Digital Payment Adoption
# --------------------------------------------------

payment_data = analysis[
    ["b14a4", "b14a5", "b14a6"]
].replace(-9, np.nan)

valid_payment = payment_data.notna().all(axis=1)

analysis["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1).astype(float)
)

# Remove firms with missing target information
analysis.loc[
    ~valid_payment,
    "Digital_Payment_Adoption"
] = np.nan


# --------------------------------------------------
# 2. Non-adoption target
# --------------------------------------------------

analysis["Non_Adoption"] = (
    analysis["Digital_Payment_Adoption"] == 0
).astype(int)


# --------------------------------------------------
# 3. Lack-of-information barrier
# --------------------------------------------------

analysis["Lack_of_Information"] = (
    analysis["d8a"].astype(str).str.strip().str.lower()
    == "lack of information"
).astype(int)


# --------------------------------------------------
# 4. Select variables for analysis
# --------------------------------------------------

analysis = analysis[
    [
        "Non_Adoption",
        "Lack_of_Information",
        "s7",
        "a5a",
        "s2e"
    ]
].copy()


# --------------------------------------------------
# 5. Remove missing values
# --------------------------------------------------

analysis = analysis.dropna()


# --------------------------------------------------
# Check results
# --------------------------------------------------

print("Analysis dataset shape:", analysis.shape)

print("\nNon-adoption:")
print(analysis["Non_Adoption"].value_counts())

print("\nLack of information:")
print(analysis["Lack_of_Information"].value_counts())

print("\nStates:")
print(analysis["s2e"].value_counts())

print("\nSectors:")
print(analysis["a5a"].value_counts())

print("\nFirst 5 rows:")
display(analysis.head())

Analysis dataset shape: (1519, 5)

Non-adoption:
Non_Adoption
0    1358
1     161
Name: count, dtype: int64

Lack of information:
Lack_of_Information
0    1237
1     282
Name: count, dtype: int64

States:
s2e
Tamil Nadu       766
Uttar Pradesh    753
Name: count, dtype: int64

Sectors:
a5a
7      196
101    186
102    173
4      129
3      122
10     121
11     120
8      120
6      117
5      117
9       80
12      38
Name: count, dtype: int64

First 5 rows:

   Non_Adoption  Lack_of_Information   s7  a5a            s2e
0             1                    0   12   11     Tamil Nadu
1             1                    0   15    6  Uttar Pradesh
2             1                    1   17    3  Uttar Pradesh
3             0                    0  210    4  Uttar Pradesh
4             0                    0   44    4  Uttar Pradesh

In [54]:
# Check the raw payment variables and identify the 4 questionable firms

print("b14a4 values:")
print(df_barrier["b14a4"].value_counts(dropna=False))

print("\nb14a5 values:")
print(df_barrier["b14a5"].value_counts(dropna=False))

print("\nb14a6 values:")
print(df_barrier["b14a6"].value_counts(dropna=False))

print("\nRows containing missing/-9 payment information:")
print(
    df_barrier[
        ["firm_id", "firmid", "b14a4", "b14a5", "b14a6"]
    ][
        df_barrier[["b14a4", "b14a5", "b14a6"]]
        .isin([-9])
        .any(axis=1)
        |
        df_barrier[["b14a4", "b14a5", "b14a6"]]
        .isna()
        .any(axis=1)
    ]
)

b14a4 values:
b14a4
 1    932
 2    585
-9      2
Name: count, dtype: int64

b14a5 values:
b14a5
 1    1066
 2     452
-9       1
Name: count, dtype: int64

b14a6 values:
b14a6
 1    854
 2    663
-9      2
Name: count, dtype: int64

Rows containing missing/-9 payment information:
       firm_id  firmid  b14a4  b14a5  b14a6
103    2028619  500104      1     -9     -9
184    2047363  500185      1      1     -9
704    2210204  500705     -9      1      2
1346  10226341  501347     -9      2      2

In [55]:
# Rebuild the target correctly using numeric conversion

payment_cols = ["b14a4", "b14a5", "b14a6"]

payment_data = (
    df_barrier[payment_cols]
    .apply(pd.to_numeric, errors="coerce")
    .replace(-9, np.nan)
)

# A firm is valid only if all 3 payment questions have valid answers
valid_payment = payment_data.notna().all(axis=1)

# Digital Payment Adoption:
# 1 = uses at least one digital payment method
# 0 = uses none of the three
digital_payment_adoption = payment_data.eq(1).any(axis=1).astype(float)

# Remove the 4 firms with incomplete payment information
digital_payment_adoption.loc[~valid_payment] = np.nan

# Add target
df_barrier["Digital_Payment_Adoption"] = digital_payment_adoption

print("Total firms:", len(df_barrier))
print("Valid target firms:", df_barrier["Digital_Payment_Adoption"].notna().sum())

print("\nTarget distribution:")
print(df_barrier["Digital_Payment_Adoption"].value_counts(dropna=False))

print("\nExcluded firms:")
print(df_barrier.loc[
    df_barrier["Digital_Payment_Adoption"].isna(),
    ["firm_id", "firmid", "b14a4", "b14a5", "b14a6"]
])

Total firms: 1519
Valid target firms: 1515

Target distribution:
Digital_Payment_Adoption
1.0    1354
0.0     161
NaN       4
Name: count, dtype: int64

Excluded firms:
       firm_id  firmid  b14a4  b14a5  b14a6
103    2028619  500104      1     -9     -9
184    2047363  500185      1      1     -9
704    2210204  500705     -9      1      2
1346  10226341  501347     -9      2      2

C:\Users\Krishna\AppData\Local\Temp\ipykernel_20060\2415919313.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_barrier["Digital_Payment_Adoption"] = digital_payment_adoption

In [56]:
# Prepare controlled barrier analysis dataset

analysis = df_barrier[
    [
        "Digital_Payment_Adoption",
        "d8a",
        "s7",
        "a5a",
        "s2e"
    ]
].copy()

# Keep only firms with valid digital-payment target
analysis = analysis.dropna(subset=["Digital_Payment_Adoption"])

# Convert target:
# 1 = non-adopter
# 0 = adopter
analysis["Non_Adoption"] = (
    analysis["Digital_Payment_Adoption"] == 0
).astype(int)

# Lack of Information indicator
analysis["Lack_of_Information"] = (
    analysis["d8a"]
    .astype(str)
    .str.strip()
    .str.lower()
    == "lack of information"
).astype(int)

# Make sure firm size is numeric
analysis["s7"] = pd.to_numeric(
    analysis["s7"],
    errors="coerce"
)

# Remove rows missing variables needed for the model
analysis = analysis.dropna(
    subset=[
        "Non_Adoption",
        "Lack_of_Information",
        "s7",
        "a5a",
        "s2e"
    ]
)

print("Analysis shape:", analysis.shape)

print("\nNon-adoption:")
print(analysis["Non_Adoption"].value_counts())

print("\nLack of information:")
print(analysis["Lack_of_Information"].value_counts())

print("\nState:")
print(analysis["s2e"].value_counts())

print("\nSector:")
print(analysis["a5a"].value_counts().sort_index())

print("\nFirm size:")
print(analysis["s7"].describe())

Analysis shape: (1515, 7)

Non-adoption:
Non_Adoption
0    1354
1     161
Name: count, dtype: int64

Lack of information:
Lack_of_Information
0    1234
1     281
Name: count, dtype: int64

State:
s2e
Tamil Nadu       766
Uttar Pradesh    749
Name: count, dtype: int64

Sector:
a5a
3      121
4      128
5      117
6      117
7      196
8      120
9       79
10     121
11     120
12      38
101    185
102    173
Name: count, dtype: int64

Firm size:
count    1515.000000
mean       79.041584
std       209.777712
min         5.000000
25%        14.000000
50%        25.000000
75%        70.000000
max      4000.000000
Name: s7, dtype: float64

In [57]:
# Create log-transformed firm size

analysis["Log_Firm_Size"] = np.log1p(analysis["s7"])

print("Original firm size:")
print(analysis["s7"].describe())

print("\nLog-transformed firm size:")
print(analysis["Log_Firm_Size"].describe())

Original firm size:
count    1515.000000
mean       79.041584
std       209.777712
min         5.000000
25%        14.000000
50%        25.000000
75%        70.000000
max      4000.000000
Name: s7, dtype: float64

Log-transformed firm size:
count    1515.000000
mean        3.511724
std         1.139873
min         1.791759
25%         2.708050
50%         3.258097
75%         4.262680
max         8.294300
Name: Log_Firm_Size, dtype: float64

In [58]:
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd

# Controlled logistic regression
controlled_model = smf.logit(
    "Non_Adoption ~ Lack_of_Information + Log_Firm_Size + C(a5a) + C(s2e)",
    data=analysis
).fit(disp=False)

print(controlled_model.summary())

ModuleNotFoundError: No module named 'statsmodels'

In [59]:
%pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.15.0-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Requirement already satisfied: numpy<3,>=1.23.5 in d:\fintech_ai_project\venv\lib\site-packages (from statsmodels) (2.5.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in d:\fintech_ai_project\venv\lib\site-packages (from statsmodels) (1.18.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in d:\fintech_ai_project\venv\lib\site-packages (from statsmodels) (3.0.6)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: packaging>=21.3 in d:\fintech_ai_project\venv\lib\site-packages (from statsmodels) (26.3)
Collecting formulaic>=1.1.0 (from statsmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in d:\fintech_ai_project\venv\lib\site-packages (from formulaic>=1.1.0->statsmodels) (2.26.0)
Requirement already satisfied: typing-extensions>=4.2.0 in d:\fintech_ai_project\venv\lib\site-packages (from formulaic>=1.1.0->statsmodels) (4.16.0)
Collecting wrapt>=1.0 (from formulaic>=1.1.0->statsmodels)
  Downloading wrapt-2.5.0-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\fintech_ai_project\venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\fintech_ai_project\venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.4)
Requirement already satisfied: six>=1.5 in d:\fintech_ai_project\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.15.0-cp312-cp312-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.3 MB 6.7 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.3 MB 6.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.3 MB 5.2 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.3 MB 4.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.3 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.9/11.3 MB 3.3 MB/s eta 0:00:03
   -------------- ------------------------- 4.2/11.3 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 4.7/11.3 MB 3.0 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.3 MB 3.0 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.3 MB 2.9 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.3 MB 2.9 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.3 MB 2.8 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.3 MB 2.9 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.3 MB 2.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.3 MB 2.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 2.9 MB/s eta 0:00:00
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading wrapt-2.5.0-cp312-cp312-win_amd64.whl (105 kB)
Installing collected packages: wrapt, patsy, interface-meta, formulaic, statsmodels
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 patsy-1.0.3 statsmodels-0.15.0 wrapt-2.5.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [60]:
import statsmodels.formula.api as smf

print("statsmodels is working!")

statsmodels is working!

In [61]:
import statsmodels
print(statsmodels.__version__)

0.15.0

In [62]:
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd

controlled_model = smf.logit(
    "Non_Adoption ~ Lack_of_Information + Log_Firm_Size + C(a5a) + C(s2e)",
    data=analysis
).fit(disp=False)

print(controlled_model.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:           Non_Adoption   No. Observations:                 1515
Model:                          Logit   Df Residuals:                     1500
Method:                           MLE   Df Model:                           14
Date:                Sun, 04 Oct 2026   Pseudo R-squ.:                  0.1088
Time:                        11:23:38   Log-Likelihood:                -457.25
converged:                       True   LL-Null:                       -513.05
Covariance Type:            nonrobust   LLR p-value:                 2.741e-17
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                  -0.5586      0.359     -1.554      0.120      -1.263       0.146
C(a5a)[T.4]                -0.0069      0.318     -0.022      0.983      -0.629       0.616
C(a5a)[T.5]                -1.4987      0.481     -3.119      0.002      -2.441      -0.557
C(a5a)[T.6]                -1.5435      0.477     -3.234      0.001      -2.479      -0.608
C(a5a)[T.7]                -2.4459      0.507     -4.825      0.000      -3.439      -1.452
C(a5a)[T.8]                -2.1771      0.558     -3.905      0.000      -3.270      -1.084
C(a5a)[T.9]                 0.1118      0.349      0.320      0.749      -0.573       0.796
C(a5a)[T.10]                0.0652      0.323      0.202      0.840      -0.567       0.698
C(a5a)[T.11]               -1.8808      0.560     -3.360      0.001      -2.978      -0.784
C(a5a)[T.12]               -2.4504      1.040     -2.356      0.018      -4.489      -0.412
C(a5a)[T.101]              -0.6605      0.317     -2.084      0.037      -1.282      -0.039
C(a5a)[T.102]              -1.1363      0.353     -3.215      0.001      -1.829      -0.444
C(s2e)[T.Uttar Pradesh]    -0.3955      0.184     -2.152      0.031      -0.756      -0.035
Lack_of_Information         0.5592      0.212      2.635      0.008       0.143       0.975
Log_Firm_Size              -0.1972      0.082     -2.405      0.016      -0.358      -0.036
===========================================================================================

In [63]:
# Extract controlled regression results and save to CSV

params = controlled_model.params
conf = controlled_model.conf_int()
pvalues = controlled_model.pvalues

controlled_results = pd.DataFrame({
    "Variable": params.index,
    "Coefficient": params.values,
    "Odds_Ratio": np.exp(params.values),
    "CI_Lower_95": np.exp(conf[0].values),
    "CI_Upper_95": np.exp(conf[1].values),
    "P_Value": pvalues.values
})

output_path = r"E:\Pep_Projectdetails\selected_dataset\controlled_barrier_logistic_results.csv"

controlled_results.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path)

print("\nMain result:")
print(
    controlled_results[
        controlled_results["Variable"] == "Lack_of_Information"
    ]
)

Saved successfully:
E:\Pep_Projectdetails\selected_dataset\controlled_barrier_logistic_results.csv

Main result:
               Variable  Coefficient  Odds_Ratio  CI_Lower_95  CI_Upper_95  \
13  Lack_of_Information     0.559152    1.749188     1.154024     2.651294

     P_Value
13  0.008412

In [64]:
# Inspect all d8a barrier categories in the controlled-analysis dataset

barrier_counts = (
    analysis.assign(
        Barrier=analysis["d8a"].astype(str).str.strip()
    )["Barrier"]
    .value_counts()
)

print("Number of barrier categories:", len(barrier_counts))
print("\nBarrier categories:")
print(barrier_counts)

Number of barrier categories: 11

Barrier categories:
Barrier
Uncertainty of demand                                              464
Too costly or not convinced of the economic benefit                333
Lack of information                                                281
Lack of technical skills                                           247
Consumer preferences do not value quality of products               64
Difficulty in obtaining financing                                   56
It is difficult or costly to comply with government regulations     28
Lack of knowledge on acquiring                                      19
Don't know                                                          10
Other                                                                9
Electricity, water, or Internet connection are too expensive         4
Name: count, dtype: int64

In [65]:
# Create binary indicators for the major barriers

barriers = [
    "Uncertainty of demand",
    "Too costly or not convinced of the economic benefit",
    "Lack of information",
    "Lack of technical skills",
    "Consumer preferences do not value quality of products",
    "Difficulty in obtaining financing",
    "It is difficult or costly to comply with government regulations",
    "Lack of knowledge on acquiring"
]

for barrier in barriers:
    column_name = (
        barrier
        .lower()
        .replace(" ", "_")
        .replace(",", "")
        .replace(".", "")
        .replace("'", "")
        .replace("/", "_")
    )

    analysis[column_name] = (
        analysis["d8a"].astype(str).str.strip() == barrier
    ).astype(int)

print("Barrier indicators created:\n")

for barrier in barriers:
    column_name = (
        barrier
        .lower()
        .replace(" ", "_")
        .replace(",", "")
        .replace(".", "")
        .replace("'", "")
        .replace("/", "_")
    )

    print(f"{column_name}: {analysis[column_name].sum()}")

Barrier indicators created:

uncertainty_of_demand: 464
too_costly_or_not_convinced_of_the_economic_benefit: 333
lack_of_information: 281
lack_of_technical_skills: 247
consumer_preferences_do_not_value_quality_of_products: 64
difficulty_in_obtaining_financing: 56
it_is_difficult_or_costly_to_comply_with_government_regulations: 28
lack_of_knowledge_on_acquiring: 19

In [66]:
# Multiple-barrier controlled logistic regression

formula = """
Non_Adoption ~
uncertainty_of_demand
+ too_costly_or_not_convinced_of_the_economic_benefit
+ lack_of_information
+ lack_of_technical_skills
+ consumer_preferences_do_not_value_quality_of_products
+ difficulty_in_obtaining_financing
+ it_is_difficult_or_costly_to_comply_with_government_regulations
+ lack_of_knowledge_on_acquiring
+ Log_Firm_Size
+ C(a5a)
+ C(s2e)
"""

multiple_barrier_model = smf.logit(
    formula,
    data=analysis
).fit(disp=False)

print(multiple_barrier_model.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:           Non_Adoption   No. Observations:                 1515
Model:                          Logit   Df Residuals:                     1493
Method:                           MLE   Df Model:                           21
Date:                Sun, 04 Oct 2026   Pseudo R-squ.:                  0.1168
Time:                        11:27:45   Log-Likelihood:                -453.15
converged:                       True   LL-Null:                       -513.05
Covariance Type:            nonrobust   LLR p-value:                 7.759e-16
===================================================================================================================================
                                                                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------------------------
Intercept                                                          -0.2480      0.874     -0.284      0.777      -1.962       1.466
C(a5a)[T.4]                                                        -0.0286      0.320     -0.089      0.929      -0.656       0.599
C(a5a)[T.5]                                                        -1.5615      0.482     -3.238      0.001      -2.507      -0.616
C(a5a)[T.6]                                                        -1.6149      0.480     -3.364      0.001      -2.556      -0.674
C(a5a)[T.7]                                                        -2.5076      0.508     -4.933      0.000      -3.504      -1.511
C(a5a)[T.8]                                                        -2.1942      0.560     -3.921      0.000      -3.291      -1.097
C(a5a)[T.9]                                                         0.0394      0.352      0.112      0.911      -0.651       0.730
C(a5a)[T.10]                                                        0.0505      0.326      0.155      0.877      -0.588       0.689
C(a5a)[T.11]                                                       -1.9008      0.562     -3.383      0.001      -3.002      -0.800
C(a5a)[T.12]                                                       -2.5064      1.042     -2.406      0.016      -4.548      -0.465
C(a5a)[T.101]                                                      -0.7248      0.319     -2.269      0.023      -1.351      -0.099
C(a5a)[T.102]                                                      -1.1976      0.356     -3.368      0.001      -1.895      -0.501
C(s2e)[T.Uttar Pradesh]                                            -0.4949      0.202     -2.452      0.014      -0.890      -0.099
uncertainty_of_demand                                              -0.0481      0.795     -0.061      0.952      -1.605       1.509
too_costly_or_not_convinced_of_the_economic_benefit                -0.4597      0.816     -0.564      0.573      -2.058       1.139
lack_of_information                                                 0.3671      0.796      0.461      0.645      -1.193       1.927
lack_of_technical_skills                                           -0.1402      0.818     -0.171      0.864      -1.744       1.463
consumer_preferences_do_not_value_quality_of_products              -0.6640      0.924     -0.719      0.472      -2.474       1.146
difficulty_in_obtaining_financing                                   0.3052      0.876      0.348      0.728      -1.412       2.022
it_is_difficult_or_costly_to_comply_with_government_regulations    -1.3990      1.289     -1.085      0.278      -3.926       1.128
lack_of_knowledge_on_acquiring                                     -1.2751      1.312     -0.972      0.331      -3.846       1.295
Log_Firm_Size                                                      -0.2003      0.082     -2.432      0.015      -0.362      -0.039
===================================================================================================================================

In [67]:
from statsmodels.stats.multitest import multipletests

# Barrier variables tested in the multiple-barrier model
barrier_variables = [
    "uncertainty_of_demand",
    "too_costly_or_not_convinced_of_the_economic_benefit",
    "lack_of_information",
    "lack_of_technical_skills",
    "consumer_preferences_do_not_value_quality_of_products",
    "difficulty_in_obtaining_financing",
    "it_is_difficult_or_costly_to_comply_with_government_regulations",
    "lack_of_knowledge_on_acquiring"
]

# Extract raw p-values
raw_pvalues = multiple_barrier_model.pvalues[barrier_variables]

# Holm correction
reject, holm_pvalues, _, _ = multipletests(
    raw_pvalues,
    method="holm"
)

# Create results table
holm_results = pd.DataFrame({
    "Barrier": barrier_variables,
    "Coefficient": multiple_barrier_model.params[barrier_variables].values,
    "Odds_Ratio": np.exp(
        multiple_barrier_model.params[barrier_variables].values
    ),
    "CI_Lower_95": np.exp(
        multiple_barrier_model.conf_int().loc[barrier_variables, 0].values
    ),
    "CI_Upper_95": np.exp(
        multiple_barrier_model.conf_int().loc[barrier_variables, 1].values
    ),
    "Raw_P_Value": raw_pvalues.values,
    "Holm_Adjusted_P_Value": holm_pvalues,
    "Significant_After_Holm": reject
})

print(holm_results.to_string(index=False))

                                                        Barrier  Coefficient  Odds_Ratio  CI_Lower_95  CI_Upper_95  Raw_P_Value  Holm_Adjusted_P_Value  Significant_After_Holm
                                          uncertainty_of_demand    -0.048103    0.953036     0.200808     4.523105     0.951725                    1.0                   False
            too_costly_or_not_convinced_of_the_economic_benefit    -0.459660    0.631499     0.127686     3.123211     0.573031                    1.0                   False
                                            lack_of_information     0.367061    1.443486     0.303301     6.869907     0.644695                    1.0                   False
                                       lack_of_technical_skills    -0.140164    0.869216     0.174873     4.320491     0.863973                    1.0                   False
          consumer_preferences_do_not_value_quality_of_products    -0.664047    0.514764     0.084229     3.145959     0.472141                    1.0                   False
                              difficulty_in_obtaining_financing     0.305204    1.356901     0.243712     7.554746     0.727542                    1.0                   False
it_is_difficult_or_costly_to_comply_with_government_regulations    -1.399002    0.246843     0.019729     3.088435     0.277823                    1.0                   False
                                 lack_of_knowledge_on_acquiring    -1.275122    0.279397     0.021371     3.652820     0.330944                    1.0                   False

In [68]:
# Save multiple-barrier + Holm correction results

holm_output_path = (
    r"E:\Pep_Projectdetails\selected_dataset"
    r"\multiple_barrier_holm_results.csv"
)

holm_results.to_csv(
    holm_output_path,
    index=False
)

print("Saved successfully:")
print(holm_output_path)

Saved successfully:
E:\Pep_Projectdetails\selected_dataset\multiple_barrier_holm_results.csv

In [69]:
# Government-benefit comparison:
# Compare adopters vs non-adopters among firms that benefited
# from a government program/subsidy.

gov = df_barrier.copy()

# Reconstruct the exact digital-payment target
payment_data = (
    gov[["b14a4", "b14a5", "b14a6"]]
    .apply(pd.to_numeric, errors="coerce")
    .replace(-9, np.nan)
)

valid_payment = payment_data.notna().all(axis=1)

gov["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1).astype(float)
)

gov.loc[~valid_payment, "Digital_Payment_Adoption"] = np.nan

# Keep only valid target firms
gov = gov.dropna(subset=["Digital_Payment_Adoption"])

# Government benefit:
# d7b = 1 → benefited
# d7b = 2 → did not benefit
gov["d7b_numeric"] = pd.to_numeric(
    gov["d7b"],
    errors="coerce"
)

# Keep only firms that benefited
benefited = gov[gov["d7b_numeric"] == 1].copy()

# Convert adoption to readable labels
benefited["Adoption_Group"] = np.where(
    benefited["Digital_Payment_Adoption"] == 1,
    "Adopter",
    "Non-adopter"
)

# Lack of information indicator
benefited["Lack_of_Information"] = (
    benefited["d8a"]
    .astype(str)
    .str.strip()
    .str.lower()
    == "lack of information"
).astype(int)

print("Benefited firms:", len(benefited))

print("\nAdoption group:")
print(benefited["Adoption_Group"].value_counts())

print("\nLack of information by adoption group:")
comparison = pd.crosstab(
    benefited["Adoption_Group"],
    benefited["Lack_of_Information"]
)

print(comparison)

print("\nPercentages:")
percentage_comparison = (
    pd.crosstab(
        benefited["Adoption_Group"],
        benefited["Lack_of_Information"],
        normalize="index"
    ) * 100
)

print(percentage_comparison)

Benefited firms: 436

Adoption group:
Adoption_Group
Adopter        390
Non-adopter     46
Name: count, dtype: int64

Lack of information by adoption group:
Lack_of_Information    0    1
Adoption_Group
Adopter              267  123
Non-adopter           20   26

Percentages:
Lack_of_Information          0          1
Adoption_Group
Adopter              68.461538  31.538462
Non-adopter          43.478261  56.521739

In [70]:
from scipy.stats import fisher_exact

# 2x2 table:
# Rows = adoption group
# Columns = lack of information
table = pd.crosstab(
    benefited["Adoption_Group"],
    benefited["Lack_of_Information"]
)

print("2x2 table:")
print(table)

# Ensure consistent ordering
adopter_no = table.loc["Adopter", 0]
adopter_yes = table.loc["Adopter", 1]
nonadopter_no = table.loc["Non-adopter", 0]
nonadopter_yes = table.loc["Non-adopter", 1]

contingency_table = np.array([
    [nonadopter_yes, nonadopter_no],
    [adopter_yes, adopter_no]
])

odds_ratio, fisher_p = fisher_exact(
    contingency_table,
    alternative="two-sided"
)

print("\nOdds Ratio:", odds_ratio)
print("Fisher's exact test p-value:", fisher_p)

# Percentage-point difference
nonadopter_pct = nonadopter_yes / (nonadopter_yes + nonadopter_no) * 100
adopter_pct = adopter_yes / (adopter_yes + adopter_no) * 100

difference_pp = nonadopter_pct - adopter_pct

print("\nNon-adopter information rate:", round(nonadopter_pct, 2), "%")
print("Adopter information rate:", round(adopter_pct, 2), "%")
print("Difference:", round(difference_pp, 2), "percentage points")

2x2 table:
Lack_of_Information    0    1
Adoption_Group
Adopter              267  123
Non-adopter           20   26

Odds Ratio: 2.821951219512195
Fisher's exact test p-value: 0.001505640706148687

Non-adopter information rate: 56.52 %
Adopter information rate: 31.54 %
Difference: 24.98 percentage points

In [71]:
# Save government-benefit comparison

government_benefit_result = pd.DataFrame([{
    "Group": "Government-benefit recipients",
    "Adopters_n": 390,
    "Non_Adopters_n": 46,
    "Adopter_Lack_Info_Percent": 31.538462,
    "Non_Adopter_Lack_Info_Percent": 56.521739,
    "Difference_Percentage_Points": 24.983277,
    "Odds_Ratio": 2.821951,
    "Fisher_Exact_P_Value": 0.001505641
}])

output_path = (
    r"E:\Pep_Projectdetails\selected_dataset"
    r"\government_benefit_information_comparison.csv"
)

government_benefit_result.to_csv(
    output_path,
    index=False
)

print("Saved successfully:")
print(output_path)

print("\nResult:")
print(government_benefit_result)

Saved successfully:
E:\Pep_Projectdetails\selected_dataset\government_benefit_information_comparison.csv

Result:
                           Group  Adopters_n  Non_Adopters_n  \
0  Government-benefit recipients         390              46

   Adopter_Lack_Info_Percent  Non_Adopter_Lack_Info_Percent  \
0                  31.538462                      56.521739

   Difference_Percentage_Points  Odds_Ratio  Fisher_Exact_P_Value
0                     24.983277    2.821951              0.001506

In [72]:
# Check whether d7c exists in the dataset

print("Does d7c exist?", "d7c" in df_barrier.columns)

if "d7c" in df_barrier.columns:
    print("\nd7c found!")
    print("\nData type:")
    print(df_barrier["d7c"].dtype)

    print("\nValue counts:")
    print(df_barrier["d7c"].value_counts(dropna=False))
else:
    print("\nd7c is NOT present in the dataset.")

Does d7c exist? True

d7c found!

Data type:
float64

Value counts:
d7c
NaN    1083
3.0     167
5.0     145
2.0      57
1.0      45
4.0      13
6.0       9
Name: count, dtype: int64

In [73]:
# Inspect d7c values and nearby variables

print("d7c unique values:")
print(sorted(df_barrier["d7c"].dropna().unique()))

print("\n--- d7a ---")
print(df_barrier["d7a"].value_counts(dropna=False))

print("\n--- d7b ---")
print(df_barrier["d7b"].value_counts(dropna=False))

print("\n--- d7c ---")
print(df_barrier["d7c"].value_counts(dropna=False).sort_index())

print("\n--- Columns around d7 ---")
d7_columns = [c for c in df_barrier.columns if c.startswith("d7")]
print(d7_columns)

d7c unique values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0)]

--- d7a ---
d7a
1    1140
2     379
Name: count, dtype: int64

--- d7b ---
d7b
 2    1060
 1     436
-9      23
Name: count, dtype: int64

--- d7c ---
d7c
1.0      45
2.0      57
3.0     167
4.0      13
5.0     145
6.0       9
NaN    1083
Name: count, dtype: int64

--- Columns around d7 ---
['d7a', 'd7b', 'd7c']

In [74]:
# Government support type (d7c) vs Digital Payment Adoption

d7c_analysis = df_barrier.copy()

# Reconstruct the correct Digital Payment Adoption target
payment_data = (
    d7c_analysis[["b14a4", "b14a5", "b14a6"]]
    .apply(pd.to_numeric, errors="coerce")
    .replace(-9, np.nan)
)

valid_payment = payment_data.notna().all(axis=1)

d7c_analysis["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1).astype(float)
)

d7c_analysis.loc[
    ~valid_payment,
    "Digital_Payment_Adoption"
] = np.nan

# Keep only firms that:
# 1. Have a valid adoption target
# 2. Benefited from government support (d7b = 1)
# 3. Have a valid d7c support type

d7c_analysis["d7b_numeric"] = pd.to_numeric(
    d7c_analysis["d7b"],
    errors="coerce"
)

d7c_analysis["d7c_numeric"] = pd.to_numeric(
    d7c_analysis["d7c"],
    errors="coerce"
)

d7c_valid = d7c_analysis[
    (d7c_analysis["Digital_Payment_Adoption"].notna()) &
    (d7c_analysis["d7b_numeric"] == 1) &
    (d7c_analysis["d7c_numeric"].notna())
].copy()

# Convert adoption to readable labels
d7c_valid["Adoption_Group"] = np.where(
    d7c_valid["Digital_Payment_Adoption"] == 1,
    "Adopter",
    "Non-adopter"
)

# Official d7c labels
support_labels = {
    1: "Information",
    2: "Technical assistance",
    3: "Tax incentive",
    4: "Grant",
    5: "Loan",
    6: "Other"
}

d7c_valid["Support_Type"] = d7c_valid["d7c_numeric"].map(
    support_labels
)

# Cross-tab
support_adoption_table = pd.crosstab(
    d7c_valid["Support_Type"],
    d7c_valid["Adoption_Group"]
)

print("Number of firms analysed:", len(d7c_valid))
print("\nSupport type × adoption:")
print(support_adoption_table)

# Add percentages within each support type
support_adoption_pct = pd.crosstab(
    d7c_valid["Support_Type"],
    d7c_valid["Adoption_Group"],
    normalize="index"
) * 100

print("\nAdoption percentages within each support type:")
print(support_adoption_pct.round(2))

Number of firms analysed: 436

Support type × adoption:
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                      11            2
Information                37            8
Loan                      143            2
Other                       5            4
Tax incentive             143           24
Technical assistance       51            6

Adoption percentages within each support type:
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                   84.62        15.38
Information             82.22        17.78
Loan                    98.62         1.38
Other                   55.56        44.44
Tax incentive           85.63        14.37
Technical assistance    89.47        10.53

In [75]:
from scipy.stats import chi2_contingency

# Create 2D contingency table
d7c_test_table = pd.crosstab(
    d7c_valid["Support_Type"],
    d7c_valid["Adoption_Group"]
)

print("Contingency table:")
print(d7c_test_table)

# Chi-square test
chi2, p_value, dof, expected = chi2_contingency(
    d7c_test_table
)

print("\nChi-square test")
print("----------------")
print("Chi-square statistic:", round(chi2, 4))
print("Degrees of freedom:", dof)
print("p-value:", round(p_value, 6))

print("\nExpected frequencies:")
expected_df = pd.DataFrame(
    expected,
    index=d7c_test_table.index,
    columns=d7c_test_table.columns
)

print(expected_df.round(2))

Contingency table:
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                      11            2
Information                37            8
Loan                      143            2
Other                       5            4
Tax incentive             143           24
Technical assistance       51            6

Chi-square test
----------------
Chi-square statistic: 29.2747
Degrees of freedom: 5
p-value: 2e-05

Expected frequencies:
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                   11.63         1.37
Information             40.25         4.75
Loan                   129.70        15.30
Other                    8.05         0.95
Tax incentive          149.38        17.62
Technical assistance    50.99         6.01

In [76]:
# Robustness check: exclude the very small "Other" category

d7c_robust = d7c_valid[
    d7c_valid["Support_Type"] != "Other"
].copy()

robust_table = pd.crosstab(
    d7c_robust["Support_Type"],
    d7c_robust["Adoption_Group"]
)

print("Support type × adoption (excluding Other):")
print(robust_table)

chi2_robust, p_robust, dof_robust, expected_robust = chi2_contingency(
    robust_table
)

print("\nRobustness chi-square test")
print("--------------------------")
print("Chi-square statistic:", round(chi2_robust, 4))
print("Degrees of freedom:", dof_robust)
print("p-value:", round(p_robust, 6))

print("\nExpected frequencies:")
print(
    pd.DataFrame(
        expected_robust,
        index=robust_table.index,
        columns=robust_table.columns
    ).round(2)
)

Support type × adoption (excluding Other):
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                      11            2
Information                37            8
Loan                      143            2
Tax incentive             143           24
Technical assistance       51            6

Robustness chi-square test
--------------------------
Chi-square statistic: 19.2481
Degrees of freedom: 4
p-value: 0.000702

Expected frequencies:
Adoption_Group        Adopter  Non-adopter
Support_Type
Grant                   11.72         1.28
Information             40.57         4.43
Loan                   130.74        14.26
Tax incentive          150.57        16.43
Technical assistance    51.39         5.61

In [77]:
# Save d7c government-support-type analysis

d7c_results = pd.DataFrame([
    {
        "Support_Type": "Grant",
        "Adopters": 11,
        "Non_Adopters": 2,
        "Non_Adoption_Percent": 15.38
    },
    {
        "Support_Type": "Information",
        "Adopters": 37,
        "Non_Adopters": 8,
        "Non_Adoption_Percent": 17.78
    },
    {
        "Support_Type": "Loan",
        "Adopters": 143,
        "Non_Adopters": 2,
        "Non_Adoption_Percent": 1.38
    },
    {
        "Support_Type": "Tax incentive",
        "Adopters": 143,
        "Non_Adopters": 24,
        "Non_Adoption_Percent": 14.37
    },
    {
        "Support_Type": "Technical assistance",
        "Adopters": 51,
        "Non_Adopters": 6,
        "Non_Adoption_Percent": 10.53
    }
])

d7c_results["Chi_Square"] = 19.2481
d7c_results["Degrees_of_Freedom"] = 4
d7c_results["P_Value"] = 0.000702

output_path = (
    r"E:\Pep_Projectdetails\selected_dataset"
    r"\government_support_type_adoption_analysis.csv"
)

d7c_results.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path)

print("\nSaved result:")
print(d7c_results)

Saved successfully:
E:\Pep_Projectdetails\selected_dataset\government_support_type_adoption_analysis.csv

Saved result:
           Support_Type  Adopters  Non_Adopters  Non_Adoption_Percent  \
0                 Grant        11             2                 15.38
1           Information        37             8                 17.78
2                  Loan       143             2                  1.38
3         Tax incentive       143            24                 14.37
4  Technical assistance        51             6                 10.53

   Chi_Square  Degrees_of_Freedom   P_Value
0     19.2481                   4  0.000702
1     19.2481                   4  0.000702
2     19.2481                   4  0.000702
3     19.2481                   4  0.000702
4     19.2481                   4  0.000702

In [1]:
# ============================================================
# FINTECH SME PROJECT - KERNEL RESTART / PROJECT RELOAD
# ============================================================
# Purpose:
# This cell reloads the libraries and important project files
# after restarting the Jupyter kernel.
#
# Run this cell FIRST whenever the kernel is restarted.
# ============================================================

import os
import pandas as pd
import numpy as np

# Main project folder
PROJECT_PATH = r"E:\Pep_Projectdetails"

# Dataset / results folder
DATA_PATH = os.path.join(
    PROJECT_PATH,
    "selected_dataset"
)

print("Project path:", PROJECT_PATH)
print("Data path:", DATA_PATH)

# ------------------------------------------------------------
# Load the working FAT India dataset
# ------------------------------------------------------------

df_barrier = pd.read_csv(
    os.path.join(
        DATA_PATH,
        "fat_india_working.csv"
    )
)

print("\nDataset loaded successfully.")
print("Dataset shape:", df_barrier.shape)

# Display first 5 rows
display(df_barrier.head())

Project path: E:\Pep_Projectdetails
Data path: E:\Pep_Projectdetails\selected_dataset

Dataset loaded successfully.
Dataset shape: (1519, 837)

,firm_id,s3a,s3b,s3c,s4,s4a,s7,a3a,a3b,a3c,...,d8d,d8e,d8f,b14a5_decoded,b14a4_decoded,b14a6_decoded,b5a_decoded,b5f_decoded,b5g_decoded,b5h_decoded
0,2000030,1,2,2,2,NaN,12,100,0,0,...,Consumer preferences do not value quality of p...,Lack of technical skills,Too costly or not convinced of the economic be...,No,No,No,Yes,No,Yes,No
1,2000031,1,2,2,2,NaN,15,100,0,0,...,Lack of information,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...,No,No,No,Yes,No,Yes,No
2,2000110,1,2,2,2,NaN,17,100,0,0,...,Too costly or not convinced of the economic be...,Lack of technical skills,It is difficult or costly to comply with gover...,No,No,No,Yes,Yes,Yes,No
3,2000515,1,2,2,2,NaN,210,100,0,0,...,Lack of technical skills,Consumer preferences do not value quality of p...,Lack of information,Yes,Yes,Yes,Yes,No,Yes,No
4,2000768,1,2,2,2,NaN,44,100,0,0,...,Too costly or not convinced of the economic be...,Consumer preferences do not value quality of p...,Lack of knowledge on acquiring,Yes,No,Yes,Yes,No,Yes,No

In [2]:
# ============================================================
# LOAD FINAL MACHINE LEARNING MODEL
# ============================================================

import joblib
import json

# Load the final Logistic Regression model
model_path = os.path.join(
    DATA_PATH,
    "final_logistic_regression_model.joblib"
)

final_model = joblib.load(model_path)

# Load the selected prediction threshold
threshold_path = os.path.join(
    DATA_PATH,
    "final_model_threshold.json"
)

with open(threshold_path, "r") as f:
    threshold_info = json.load(f)

FINAL_THRESHOLD = threshold_info["threshold"]

print("Final model loaded successfully.")
print("Model:", threshold_info["model"])
print("Target:", threshold_info["target"])
print("Threshold:", FINAL_THRESHOLD)

Final model loaded successfully.
Model: Logistic Regression
Target: Digital_Payment_Adoption
Threshold: 0.36

c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator SimpleImputer from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator ColumnTransformer from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.9.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
import sklearn

print("Current scikit-learn version:", sklearn.__version__)

Current scikit-learn version: 1.8.0

In [5]:
%pip install scikit-learn==1.9.1

Collecting scikit-learn==1.9.1
  Using cached scikit_learn-1.9.1-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (3.6.0)
Using cached scikit_learn-1.9.1-cp312-cp312-win_amd64.whl (8.3 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.8.0
    Uninstalling scikit-learn-1.8.0:
      Successfully uninstalled scikit-learn-1.8.0
Successfully installed scikit-learn-1.9.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages\~klearn'.
  You can safely remove it manually.

In [6]:
%pip install scikit-learn==1.9.1

Requirement already satisfied: scikit-learn==1.9.1 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Krishna\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn==1.9.1) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sklearn

print("scikit-learn version:", sklearn.__version__)

scikit-learn version: 1.9.1

In [2]:
import os
import pandas as pd
import numpy as np

PROJECT_PATH = r"E:\Pep_Projectdetails"
DATA_PATH = os.path.join(PROJECT_PATH, "selected_dataset")

df_barrier = pd.read_csv(
    os.path.join(DATA_PATH, "fat_india_working.csv")
)

print("Dataset loaded successfully.")
print("Shape:", df_barrier.shape)

Dataset loaded successfully.
Shape: (1519, 837)

In [3]:
import joblib
import json

# Load the final trained model
model_path = os.path.join(
    DATA_PATH,
    "final_logistic_regression_model.joblib"
)

final_model = joblib.load(model_path)

# Load the final threshold
threshold_path = os.path.join(
    DATA_PATH,
    "final_model_threshold.json"
)

with open(threshold_path, "r") as f:
    threshold_info = json.load(f)

FINAL_THRESHOLD = threshold_info["threshold"]

print("Final model loaded successfully.")
print("Model:", threshold_info["model"])
print("Target:", threshold_info["target"])
print("Threshold:", FINAL_THRESHOLD)

Final model loaded successfully.
Model: Logistic Regression
Target: Digital_Payment_Adoption
Threshold: 0.36

In [4]:
# Find columns that may contain survey/design weights

weight_candidates = [
    col for col in df_barrier.columns
    if any(word in col.lower() for word in [
        "weight", "wgt", "wt", "sampling", "sample_weight",
        "design_weight", "final_weight"
    ])
]

print("Possible weight columns:")
for col in weight_candidates:
    print("-", col)

Possible weight columns:
- base_wt

In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
df_barrier = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"
)

print("Dataset loaded successfully")
print("Shape:", df_barrier.shape)
print("\nColumns:", len(df_barrier.columns))

Dataset loaded successfully
Shape: (1519, 837)

Columns: 837

In [3]:
required_columns = [
    "s7",
    "a5a",
    "s2e",
    "d7a",
    "d7b",
    "d7c",
    "d8a",
    "b14a4",
    "b14a5",
    "b14a6"
]

missing_columns = [
    col for col in required_columns
    if col not in df_barrier.columns
]

print("Missing columns:", missing_columns)

if not missing_columns:
    print("All required columns are available.")

Missing columns: []
All required columns are available.

In [4]:
# Search for columns that may contain survey weights

weight_candidates = [
    col for col in df_barrier.columns
    if any(word in col.lower() for word in [
        "weight",
        "wgt",
        "wt",
        "sampling",
        "sample"
    ])
]

print("Possible weight-related columns:")
print(weight_candidates)

Possible weight-related columns:
['base_wt']

In [5]:
# Inspect the survey weight variable

print("Data type:")
print(df_barrier["base_wt"].dtype)

print("\nBasic summary:")
print(df_barrier["base_wt"].describe())

print("\nMissing values:")
print(df_barrier["base_wt"].isna().sum())

print("\nZero or negative weights:")
print((df_barrier["base_wt"] <= 0).sum())

print("\nFirst 20 weight values:")
print(df_barrier["base_wt"].head(20).to_list())

Data type:
float64

Basic summary:
count    1519.000000
mean       60.606320
std        79.489803
min         1.807692
25%         7.529412
50%        31.142859
75%        63.190479
max       299.166656
Name: base_wt, dtype: float64

Missing values:
0

Zero or negative weights:
0

First 20 weight values:
[9.63157844543457, 7.52941179275513, 16.169490814209, 29.1428565979004, 8.35555553436279, 9.63157844543457, 299.166656494141, 60.4000015258789, 102.083335876465, 102.083335876465, 9.63157844543457, 225.709091186523, 5.38888883590698, 5.38888883590698, 8.35555553436279, 225.709091186523, 3.95238065719604, 7.41379356384277, 60.4000015258789, 8.35555553436279]

In [6]:
# Weighted vs unweighted Digital Payment Adoption

weighted_df = df_barrier.copy()

# Convert payment variables to numeric and treat -9 as missing
payment_data = (
    weighted_df[["b14a4", "b14a5", "b14a6"]]
    .apply(pd.to_numeric, errors="coerce")
    .replace(-9, np.nan)
)

# Keep only firms with complete target information
valid_payment = payment_data.notna().all(axis=1)

weighted_df["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1).astype(float)
)

weighted_df.loc[
    ~valid_payment,
    "Digital_Payment_Adoption"
] = np.nan

weighted_df = weighted_df.dropna(
    subset=["Digital_Payment_Adoption", "base_wt"]
)

# Unweighted adoption rate
unweighted_rate = weighted_df["Digital_Payment_Adoption"].mean()

# Weighted adoption rate
weighted_rate = np.average(
    weighted_df["Digital_Payment_Adoption"],
    weights=weighted_df["base_wt"]
)

print("Valid firms:", len(weighted_df))

print("\nUnweighted adoption rate:")
print(f"{unweighted_rate:.4%}")

print("\nWeighted adoption rate:")
print(f"{weighted_rate:.4%}")

print("\nDifference:")
print(f"{(weighted_rate - unweighted_rate) * 100:.2f} percentage points")

Valid firms: 1515

Unweighted adoption rate:
89.3729%

Weighted adoption rate:
90.1286%

Difference:
0.76 percentage points

In [1]:
# Weighted barrier distribution among digital-payment non-adopters

barrier_df = weighted_df[
    weighted_df["Digital_Payment_Adoption"] == 0
].copy()

# Calculate weighted percentage for each first-ranked barrier
weighted_barrier = (
    barrier_df
    .groupby("d8a")
    .apply(
        lambda group: group["base_wt"].sum()
        / barrier_df["base_wt"].sum() * 100,
        include_groups=False
    )
    .sort_values(ascending=False)
)

print("Weighted barrier distribution among non-adopters:")
print(weighted_barrier.round(2))

print("\nNumber of non-adopter firms:", len(barrier_df))
print(
    "Weighted non-adopter population:",
    round(barrier_df["base_wt"].sum(), 2)
)

NameError: name 'weighted_df' is not defined

In [8]:
# Compare unweighted and weighted barrier percentages

# Unweighted distribution
unweighted_barrier = (
    barrier_df["d8a"]
    .value_counts(normalize=True)
    .mul(100)
)

# Combine
barrier_comparison = pd.DataFrame({
    "Unweighted_%": unweighted_barrier,
    "Weighted_%": weighted_barrier
})

barrier_comparison["Difference_pp"] = (
    barrier_comparison["Weighted_%"]
    - barrier_comparison["Unweighted_%"]
)

barrier_comparison = barrier_comparison.sort_values(
    "Weighted_%",
    ascending=False
)

print(barrier_comparison.round(2))

                                                    Unweighted_%  Weighted_%  \
d8a
Uncertainty of demand                                      29.81       28.29
Too costly or not convinced of the economic ben...         17.39       22.15
Lack of information                                        26.09       20.33
Lack of technical skills                                   16.15       16.08
Difficulty in obtaining financing                           4.97        6.29
Consumer preferences do not value quality of pr...          3.11        5.53
Lack of knowledge on acquiring                              0.62        0.87
It is difficult or costly to comply with govern...          0.62        0.31
Don't know                                                  0.62        0.12
Other                                                       0.62        0.04

                                                    Difference_pp
d8a
Uncertainty of demand                                       -1.52
Too costly or not convinced of the economic ben...           4.76
Lack of information                                         -5.76
Lack of technical skills                                    -0.07
Difficulty in obtaining financing                            1.32
Consumer preferences do not value quality of pr...           2.42
Lack of knowledge on acquiring                               0.25
It is difficult or costly to comply with govern...          -0.31
Don't know                                                  -0.50
Other                                                       -0.58

In [2]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully")

Libraries loaded successfully

In [3]:
df_barrier = pd.read_csv(
    r"E:\Pep_Projectdetails\selected_dataset\fat_india_working.csv"
)

print("Dataset loaded successfully")
print("Shape:", df_barrier.shape)
print("\nColumns:", len(df_barrier.columns))

Dataset loaded successfully
Shape: (1519, 837)

Columns: 837

In [4]:
required_columns = [
    "s7",
    "a5a",
    "s2e",
    "d7a",
    "d7b",
    "d7c",
    "d8a",
    "b14a4",
    "b14a5",
    "b14a6"
]

missing_columns = [
    col for col in required_columns
    if col not in df_barrier.columns
]

print("Missing columns:", missing_columns)

if not missing_columns:
    print("All required columns are available.")

Missing columns: []
All required columns are available.

In [5]:
# Compare unweighted and weighted barrier percentages

# Unweighted distribution
unweighted_barrier = (
    barrier_df["d8a"]
    .value_counts(normalize=True)
    .mul(100)
)

# Combine
barrier_comparison = pd.DataFrame({
    "Unweighted_%": unweighted_barrier,
    "Weighted_%": weighted_barrier
})

barrier_comparison["Difference_pp"] = (
    barrier_comparison["Weighted_%"]
    - barrier_comparison["Unweighted_%"]
)

barrier_comparison = barrier_comparison.sort_values(
    "Weighted_%",
    ascending=False
)

print(barrier_comparison.round(2))

NameError: name 'barrier_df' is not defined

In [6]:
# Search for columns that may contain survey weights

weight_candidates = [
    col for col in df_barrier.columns
    if any(word in col.lower() for word in [
        "weight",
        "wgt",
        "wt",
        "sampling",
        "sample"
    ])
]

print("Possible weight-related columns:")
print(weight_candidates)

Possible weight-related columns:
['base_wt']

In [7]:
# Inspect the survey weight variable

print("Data type:")
print(df_barrier["base_wt"].dtype)

print("\nBasic summary:")
print(df_barrier["base_wt"].describe())

print("\nMissing values:")
print(df_barrier["base_wt"].isna().sum())

print("\nZero or negative weights:")
print((df_barrier["base_wt"] <= 0).sum())

print("\nFirst 20 weight values:")
print(df_barrier["base_wt"].head(20).to_list())

Data type:
float64

Basic summary:
count    1519.000000
mean       60.606320
std        79.489803
min         1.807692
25%         7.529412
50%        31.142859
75%        63.190479
max       299.166656
Name: base_wt, dtype: float64

Missing values:
0

Zero or negative weights:
0

First 20 weight values:
[9.63157844543457, 7.52941179275513, 16.169490814209, 29.1428565979004, 8.35555553436279, 9.63157844543457, 299.166656494141, 60.4000015258789, 102.083335876465, 102.083335876465, 9.63157844543457, 225.709091186523, 5.38888883590698, 5.38888883590698, 8.35555553436279, 225.709091186523, 3.95238065719604, 7.41379356384277, 60.4000015258789, 8.35555553436279]

In [8]:
# Weighted vs unweighted Digital Payment Adoption

weighted_df = df_barrier.copy()

# Convert payment variables to numeric and treat -9 as missing
payment_data = (
    weighted_df[["b14a4", "b14a5", "b14a6"]]
    .apply(pd.to_numeric, errors="coerce")
    .replace(-9, np.nan)
)

# Keep only firms with complete target information
valid_payment = payment_data.notna().all(axis=1)

weighted_df["Digital_Payment_Adoption"] = (
    payment_data.eq(1).any(axis=1).astype(float)
)

weighted_df.loc[
    ~valid_payment,
    "Digital_Payment_Adoption"
] = np.nan

weighted_df = weighted_df.dropna(
    subset=["Digital_Payment_Adoption", "base_wt"]
)

# Unweighted adoption rate
unweighted_rate = weighted_df["Digital_Payment_Adoption"].mean()

# Weighted adoption rate
weighted_rate = np.average(
    weighted_df["Digital_Payment_Adoption"],
    weights=weighted_df["base_wt"]
)

print("Valid firms:", len(weighted_df))

print("\nUnweighted adoption rate:")
print(f"{unweighted_rate:.4%}")

print("\nWeighted adoption rate:")
print(f"{weighted_rate:.4%}")

print("\nDifference:")
print(f"{(weighted_rate - unweighted_rate) * 100:.2f} percentage points")

Valid firms: 1515

Unweighted adoption rate:
89.3729%

Weighted adoption rate:
90.1286%

Difference:
0.76 percentage points

In [9]:
# Weighted barrier distribution among digital-payment non-adopters

barrier_df = weighted_df[
    weighted_df["Digital_Payment_Adoption"] == 0
].copy()

# Calculate weighted percentage for each first-ranked barrier
weighted_barrier = (
    barrier_df
    .groupby("d8a")
    .apply(
        lambda group: group["base_wt"].sum()
        / barrier_df["base_wt"].sum() * 100,
        include_groups=False
    )
    .sort_values(ascending=False)
)

print("Weighted barrier distribution among non-adopters:")
print(weighted_barrier.round(2))

print("\nNumber of non-adopter firms:", len(barrier_df))
print(
    "Weighted non-adopter population:",
    round(barrier_df["base_wt"].sum(), 2)
)

Weighted barrier distribution among non-adopters:
d8a
Uncertainty of demand                                              28.29
Too costly or not convinced of the economic benefit                22.15
Lack of information                                                20.33
Lack of technical skills                                           16.08
Difficulty in obtaining financing                                   6.29
Consumer preferences do not value quality of products               5.53
Lack of knowledge on acquiring                                      0.87
It is difficult or costly to comply with government regulations     0.31
Don't know                                                          0.12
Other                                                               0.04
dtype: float64

Number of non-adopter firms: 161
Weighted non-adopter population: 9078.92

In [10]:
# Compare unweighted and weighted barrier percentages

# Unweighted distribution
unweighted_barrier = (
    barrier_df["d8a"]
    .value_counts(normalize=True)
    .mul(100)
)

# Combine
barrier_comparison = pd.DataFrame({
    "Unweighted_%": unweighted_barrier,
    "Weighted_%": weighted_barrier
})

barrier_comparison["Difference_pp"] = (
    barrier_comparison["Weighted_%"]
    - barrier_comparison["Unweighted_%"]
)

barrier_comparison = barrier_comparison.sort_values(
    "Weighted_%",
    ascending=False
)

print(barrier_comparison.round(2))

                                                    Unweighted_%  Weighted_%  \
d8a
Uncertainty of demand                                      29.81       28.29
Too costly or not convinced of the economic ben...         17.39       22.15
Lack of information                                        26.09       20.33
Lack of technical skills                                   16.15       16.08
Difficulty in obtaining financing                           4.97        6.29
Consumer preferences do not value quality of pr...          3.11        5.53
Lack of knowledge on acquiring                              0.62        0.87
It is difficult or costly to comply with govern...          0.62        0.31
Don't know                                                  0.62        0.12
Other                                                       0.62        0.04

                                                    Difference_pp
d8a
Uncertainty of demand                                       -1.52
Too costly or not convinced of the economic ben...           4.76
Lack of information                                         -5.76
Lack of technical skills                                    -0.07
Difficulty in obtaining financing                            1.32
Consumer preferences do not value quality of pr...           2.42
Lack of knowledge on acquiring                               0.25
It is difficult or costly to comply with govern...          -0.31
Don't know                                                  -0.50
Other                                                       -0.58

In [11]:
# Prepare dataset for controlled barrier analysis

controlled_df = weighted_df.copy()

# Outcome:
# 1 = digital-payment non-adopter
# 0 = digital-payment adopter
controlled_df["Non_Adoption"] = (
    controlled_df["Digital_Payment_Adoption"] == 0
).astype(int)

# Convert first-ranked barrier to text
controlled_df["d8a_clean"] = (
    controlled_df["d8a"]
    .astype(str)
    .str.strip()
)

# Create barrier indicator variables
controlled_df["Lack_of_information"] = (
    controlled_df["d8a_clean"]
    == "Lack of information"
).astype(int)

controlled_df["Uncertainty_of_demand"] = (
    controlled_df["d8a_clean"]
    == "Uncertainty of demand"
).astype(int)

controlled_df["Cost_Barrier"] = (
    controlled_df["d8a_clean"]
    == "Too costly or not convinced of the economic benefit"
).astype(int)

controlled_df["Technical_Skills"] = (
    controlled_df["d8a_clean"]
    == "Lack of technical skills"
).astype(int)

controlled_df["Financing_Barrier"] = (
    controlled_df["d8a_clean"]
    == "Difficulty in obtaining financing"
).astype(int)

# Keep variables needed for the controlled analysis
analysis_columns = [
    "Non_Adoption",
    "Lack_of_information",
    "Uncertainty_of_demand",
    "Cost_Barrier",
    "Technical_Skills",
    "Financing_Barrier",
    "s7",
    "a5a",
    "s2e",
    "base_wt"
]

controlled_df = controlled_df[analysis_columns].copy()

# Remove rows missing required control variables
controlled_df = controlled_df.dropna(
    subset=["s7", "a5a", "s2e", "base_wt"]
)

print("Controlled analysis dataset shape:", controlled_df.shape)

print("\nNon-adoption distribution:")
print(controlled_df["Non_Adoption"].value_counts())

print("\nBarrier indicator totals:")
print(
    controlled_df[
        [
            "Lack_of_information",
            "Uncertainty_of_demand",
            "Cost_Barrier",
            "Technical_Skills",
            "Financing_Barrier"
        ]
    ].sum()
)

print("\nMissing values:")
print(controlled_df.isna().sum())

Controlled analysis dataset shape: (1515, 10)

Non-adoption distribution:
Non_Adoption
0    1354
1     161
Name: count, dtype: int64

Barrier indicator totals:
Lack_of_information      281
Uncertainty_of_demand    464
Cost_Barrier             333
Technical_Skills         247
Financing_Barrier         56
dtype: int64

Missing values:
Non_Adoption             0
Lack_of_information      0
Uncertainty_of_demand    0
Cost_Barrier             0
Technical_Skills         0
Financing_Barrier        0
s7                       0
a5a                      0
s2e                      0
base_wt                  0
dtype: int64

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

# Predictor variables
barrier_features = [
    "Lack_of_information",
    "Uncertainty_of_demand",
    "Cost_Barrier",
    "Technical_Skills",
    "Financing_Barrier"
]

numerical_features = [
    "s7"
]

categorical_features = [
    "a5a",
    "s2e"
]

X_control = controlled_df[
    barrier_features + numerical_features + categorical_features
]

y_control = controlled_df["Non_Adoption"]

# Preprocessing
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        drop="first"
    ))
])

preprocessor_control = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

# Logistic regression
controlled_model = Pipeline([
    ("preprocessor", preprocessor_control),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Fit model
controlled_model.fit(X_control, y_control)

print("Controlled logistic regression fitted successfully.")

Controlled logistic regression fitted successfully.

In [13]:
# Extract controlled logistic regression results

from scipy.stats import norm

# Get transformed feature names
feature_names = (
    controlled_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

# Get coefficients
coefficients = (
    controlled_model
    .named_steps["classifier"]
    .coef_[0]
)

# Calculate standard errors using the fitted design matrix
X_transformed = (
    controlled_model
    .named_steps["preprocessor"]
    .transform(X_control)
)

# Convert sparse matrix if necessary
if hasattr(X_transformed, "toarray"):
    X_transformed = X_transformed.toarray()

X_transformed = np.asarray(X_transformed)

# Add intercept column
X_with_intercept = np.column_stack([
    np.ones(X_transformed.shape[0]),
    X_transformed
])

# Calculate covariance matrix
p = X_with_intercept.shape[1]
n = X_with_intercept.shape[0]

probs = controlled_model.predict_proba(X_control)[:, 1]

W = probs * (1 - probs)

XW = X_with_intercept.T * W

try:
    covariance = np.linalg.inv(
        XW @ X_with_intercept
    )

    standard_errors = np.sqrt(
        np.diag(covariance)
    )[1:]

    z_values = coefficients / standard_errors

    p_values = 2 * norm.sf(
        np.abs(z_values)
    )

    ci_lower = coefficients - 1.96 * standard_errors
    ci_upper = coefficients + 1.96 * standard_errors

    odds_ratios = np.exp(coefficients)
    or_lower = np.exp(ci_lower)
    or_upper = np.exp(ci_upper)

    controlled_results = pd.DataFrame({
        "Feature": feature_names,
        "Coefficient": coefficients,
        "Odds_Ratio": odds_ratios,
        "CI_Lower": or_lower,
        "CI_Upper": or_upper,
        "p_value": p_values
    })

    controlled_results = controlled_results.sort_values(
        "p_value"
    )

    print(controlled_results.round(4).to_string(index=False))

except np.linalg.LinAlgError:
    print("Could not calculate covariance matrix because it is singular.")

               Feature  Coefficient  Odds_Ratio  CI_Lower  CI_Upper  p_value
            cat__a5a_7      -2.0396      0.1301    0.0777    0.2177   0.0000
            cat__a5a_8      -1.7676      0.1707    0.0975    0.2990   0.0000
           cat__a5a_11      -1.6817      0.1861    0.1058    0.3270   0.0000
            cat__a5a_6      -1.3404      0.2618    0.1525    0.4493   0.0000
            cat__a5a_5      -1.3343      0.2633    0.1532    0.4527   0.0000
           cat__a5a_12      -1.7434      0.1749    0.0767    0.3988   0.0000
          cat__a5a_102      -0.8328      0.4348    0.2688    0.7035   0.0007
               num__s7      -0.2341      0.7913    0.6783    0.9230   0.0029
cat__s2e_Uttar Pradesh      -0.2481      0.7803    0.6245    0.9749   0.0290
          cat__a5a_101      -0.4340      0.6479    0.4037    1.0399   0.0722
            cat__a5a_9       0.5170      1.6771    0.8872    3.1699   0.1115
           cat__a5a_10       0.2805      1.3238    0.7656    2.2889   0.3154
            cat__a5a_4       0.1236      1.1316    0.6681    1.9166   0.6456

In [14]:
# Corrected controlled logistic regression
# Includes barrier variables + firm size + sector + state

barrier_features = [
    "Lack_of_information",
    "Uncertainty_of_demand",
    "Cost_Barrier",
    "Technical_Skills",
    "Financing_Barrier"
]

numerical_features = [
    "Lack_of_information",
    "Uncertainty_of_demand",
    "Cost_Barrier",
    "Technical_Skills",
    "Financing_Barrier",
    "s7"
]

categorical_features = [
    "a5a",
    "s2e"
]

X_control = controlled_df[
    barrier_features + ["s7", "a5a", "s2e"]
]

y_control = controlled_df["Non_Adoption"]

# Preprocessing
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        drop="first"
    ))
])

preprocessor_control = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

# Model
controlled_model = Pipeline([
    ("preprocessor", preprocessor_control),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

# Fit
controlled_model.fit(X_control, y_control)

# Verify that barrier variables are actually included
feature_names_check = (
    controlled_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

print("Controlled logistic regression fitted successfully.")

print("\nFeatures included:")
for feature in feature_names_check:
    print(feature)

Controlled logistic regression fitted successfully.

Features included:
num__Lack_of_information
num__Uncertainty_of_demand
num__Cost_Barrier
num__Technical_Skills
num__Financing_Barrier
num__s7
cat__a5a_4
cat__a5a_5
cat__a5a_6
cat__a5a_7
cat__a5a_8
cat__a5a_9
cat__a5a_10
cat__a5a_11
cat__a5a_12
cat__a5a_101
cat__a5a_102
cat__s2e_Uttar Pradesh

In [15]:
# Final controlled logistic regression
# Barrier variables remain binary (0/1)
# Firm size is standardized

numerical_features = ["s7"]

binary_barrier_features = [
    "Lack_of_information",
    "Uncertainty_of_demand",
    "Cost_Barrier",
    "Technical_Skills",
    "Financing_Barrier"
]

categorical_features = [
    "a5a",
    "s2e"
]

X_control = controlled_df[
    binary_barrier_features + numerical_features + categorical_features
]

y_control = controlled_df["Non_Adoption"]

# Preprocessing for firm size
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Binary barriers: impute only, NO scaling
barrier_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent"))
])

# Categorical variables
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        drop="first"
    ))
])

preprocessor_control = ColumnTransformer([
    ("barrier", barrier_pipeline, binary_barrier_features),
    ("size", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

controlled_model = Pipeline([
    ("preprocessor", preprocessor_control),
    ("classifier", LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ))
])

controlled_model.fit(X_control, y_control)

# Verify
feature_names = (
    controlled_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

print("Final controlled model fitted successfully.")

print("\nFeatures:")
for feature in feature_names:
    print(feature)

Final controlled model fitted successfully.

Features:
barrier__Lack_of_information
barrier__Uncertainty_of_demand
barrier__Cost_Barrier
barrier__Technical_Skills
barrier__Financing_Barrier
size__s7
cat__a5a_4
cat__a5a_5
cat__a5a_6
cat__a5a_7
cat__a5a_8
cat__a5a_9
cat__a5a_10
cat__a5a_11
cat__a5a_12
cat__a5a_101
cat__a5a_102
cat__s2e_Uttar Pradesh

In [16]:
# Extract Odds Ratios, 95% CI and p-values
# for the final controlled logistic regression

from scipy.stats import norm

# Get transformed data
X_transformed = (
    controlled_model
    .named_steps["preprocessor"]
    .transform(X_control)
)

if hasattr(X_transformed, "toarray"):
    X_transformed = X_transformed.toarray()

X_transformed = np.asarray(X_transformed)

# Add intercept
X_with_intercept = np.column_stack([
    np.ones(X_transformed.shape[0]),
    X_transformed
])

# Predicted probabilities
classifier = controlled_model.named_steps["classifier"]
probabilities = controlled_model.predict_proba(X_control)[:, 1]

# Logistic regression weights
W = probabilities * (1 - probabilities)

# Information matrix
XW = X_with_intercept.T * W

# Covariance matrix
covariance = np.linalg.inv(
    XW @ X_with_intercept
)

# Standard errors
standard_errors = np.sqrt(
    np.diag(covariance)
)[1:]

# Coefficients
coefficients = classifier.coef_[0]

# Statistics
z_values = coefficients / standard_errors

p_values = 2 * norm.sf(
    np.abs(z_values)
)

# 95% confidence intervals
ci_lower = coefficients - 1.96 * standard_errors
ci_upper = coefficients + 1.96 * standard_errors

# Convert coefficients to odds ratios
odds_ratios = np.exp(coefficients)
or_lower = np.exp(ci_lower)
or_upper = np.exp(ci_upper)

# Results table
controlled_results = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients,
    "Odds_Ratio": odds_ratios,
    "CI_Lower": or_lower,
    "CI_Upper": or_upper,
    "p_value": p_values
})

# Show only the five barrier variables
barrier_results = controlled_results[
    controlled_results["Feature"].str.startswith("barrier__")
].copy()

barrier_results["Barrier"] = (
    barrier_results["Feature"]
    .str.replace("barrier__", "", regex=False)
)

barrier_results = barrier_results[
    [
        "Barrier",
        "Odds_Ratio",
        "CI_Lower",
        "CI_Upper",
        "p_value"
    ]
].sort_values("p_value")

print("Controlled barrier analysis:")
print(
    barrier_results.round(4).to_string(index=False)
)

Controlled barrier analysis:
              Barrier  Odds_Ratio  CI_Lower  CI_Upper  p_value
  Lack_of_information      2.5361    1.5773    4.0779   0.0001
Uncertainty_of_demand      1.7082    1.0959    2.6625   0.0181
    Financing_Barrier      2.1140    1.0627    4.2055   0.0329
     Technical_Skills      1.4476    0.8958    2.3394   0.1309
         Cost_Barrier      1.1918    0.7521    1.8886   0.4551

In [17]:
import os

model_path = r"E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib"
data_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"

print("Model exists:", os.path.exists(model_path))
print("Dataset exists:", os.path.exists(data_path))

Model exists: True
Dataset exists: True

In [18]:
import joblib

model_path = r"E:\Pep_Projectdetails\selected_dataset\final_logistic_regression_model.joblib"

final_model = joblib.load(model_path)

print("Model loaded successfully!")
print(final_model)

Model loaded successfully!
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['s7', 'a6', 'd3c']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['a5a', 'b5a', 'b5f', 'b5g',
                                                   'b5h', 'b13b4', 'b13b5',
                                                   'd3a', 'd7a', 'd7b'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=2000,
                                    random_state=42))])

In [19]:
import pandas as pd

data_path = r"E:\Pep_Projectdetails\selected_dataset\fintech_ml_final.csv"

df = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset loaded successfully!
Shape: (1515, 14)

Columns:
['s7', 'a5a', 'a6', 'b5a', 'b5f', 'b5g', 'b5h', 'b13b4', 'b13b5', 'd3a', 'd3c', 'd7a', 'd7b', 'Digital_Payment_Adoption']

In [20]:
X = df.drop(columns=["Digital_Payment_Adoption"])
y = df["Digital_Payment_Adoption"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (1515, 13)
y shape: (1515,)

Target distribution:
Digital_Payment_Adoption
1    1354
0     161
Name: count, dtype: int64

In [21]:
# Predict probability of Digital Payment Adoption
probabilities = final_model.predict_proba(X)[:, 1]

# Apply your final threshold
threshold = 0.36

predictions = (probabilities >= threshold).astype(int)

print("Predictions generated successfully!")

print("\nFirst 10 probabilities:")
print(probabilities[:10])

print("\nFirst 10 predictions:")
print(predictions[:10])

print("\nPredicted class distribution:")
print(pd.Series(predictions).value_counts())

Predictions generated successfully!

First 10 probabilities:
[0.66370032 0.54248093 0.33675862 0.50786996 0.49009531 0.89458394
 0.60736756 0.82849284 0.44833738 0.19598418]

First 10 predictions:
[1 1 0 1 1 1 1 1 1 0]

Predicted class distribution:
1    1245
0     270
Name: count, dtype: int64